(in-package #:cl-nes/test)

(describe "MMC5 mapper bank mapping surface"
  (it "maps CPU PRG windows according to the selected MMC5 PRG mode"
    (with-mmc5-cartridge (cart)
      (labels ((write-register (address value)
                 (cl-nes::cartridge-write-expansion! cart address value))
               (sample-window (mode writes address expected)
                 (write-register #x5100 mode)
                 (dolist (write writes)
                   (write-register (+ #x5110 (first write)) (second write)))
                 (expect (cartridge-read-prg cart address) :to-be expected)))
        (sample-window 0 '((7 #x80)) #x8000 #x00)
        (sample-window 1 '((5 #x82) (7 #x83)) #x8000 #x02)
        (sample-window 2 '((5 #x84) (6 #x85) (7 #x87)) #xc000 #x05)
        (sample-window 3 '((4 #x86) (5 #x87) (6 #x88) (7 #x89))
                       #xe000 #x09))))

  (it "maps CHR windows according to the selected MMC5 CHR mode"
    (with-mmc5-cartridge (cart)
      (labels ((write-register (address value)
                 (cl-nes::cartridge-write-expansion! cart address value))
               (sample-window (mode writes address expected)
                 (write-register #x5101 mode)
                 (dolist (write writes)
                   (write-register (+ #x5120 (first write)) (second write)))
                 (expect (cartridge-read-chr cart address) :to-be expected)))
        (sample-window 0 '((7 #x08)) #x1fff #x0f)
        (sample-window 1 '((7 #x14)) #x1000 #x04)
        (sample-window 2 '((4 #x06)) #x0800 #x06)
        (sample-window 3 '((1 #x09)) #x0400 #x09))))

  (it "maps every PRG slot in each mode and preserves CPU window boundaries"
    (with-mmc5-cartridge (cart)
      (labels ((write-register (address value)
                 (cl-nes::cartridge-write-expansion! cart address value))
               (expect-layout (mode writes expected)
                 (write-register #x5100 mode)
                 (dolist (write writes)
                   (write-register (+ #x5110 (first write)) (second write)))
                 (expect-mmc5-prg-layout cart expected)))
        (expect-layout 0 '((7 #x80)) '(0 1 2 3))
        (expect-layout 1 '((5 #x82) (7 #x86)) '(2 3 6 7))
        (expect-layout 2 '((5 #x84) (6 #x86) (7 #x87)) '(4 5 6 7))
        (expect-layout 3 '((4 #x88) (5 #x89) (6 #x8a) (7 #x8b))
                       '(8 9 10 11))
        (expect (cartridge-read-prg cart #x8000) :to-be 8)
        (expect (cartridge-read-prg cart #xffff) :to-be 11))))

  (it "maps all CHR slots in each mode for sprite and background fetches"
    (with-mmc5-cartridge (cart)
      (labels ((write-register (address value)
                 (cl-nes::cartridge-write-expansion! cart address value))
               (expect-layout (mode writes sprite background)
                 (write-register #x5101 mode)
                 (dolist (write writes)
                   (write-register (+ #x5120 (first write)) (second write)))
                 (expect-mmc5-chr-layout cart sprite background)))
        (expect-layout 0 '((7 #x00) (11 #x08))
                       '(0 1 2 3 4 5 6 7)
                       '(8 9 10 11 12 13 14 15))
        (expect-layout 1 '((3 #x00) (7 #x0c) (11 #x08))
                       '(0 1 2 3 12 13 14 15)
                       '(8 9 10 11 8 9 10 11))
        (expect-layout 2 '((2 #x00) (4 #x02) (6 #x04) (7 #x06)
                           (10 #x08) (11 #x0a))
                       '(0 1 2 3 4 5 6 7)
                       '(8 9 10 11 10 11 10 11))
        (expect-layout 3 '((0 #x00) (1 #x01) (2 #x02) (3 #x03)
                           (4 #x04) (5 #x05) (6 #x06) (7 #x07)
                           (8 #x08) (9 #x09) (10 #x0a) (11 #x0b))
                       '(0 1 2 3 4 5 6 7)
                       '(8 9 10 11 8 9 10 11))))))
