(in-package #:cl-nes)

(defun make-controller ()
  (%make-controller))

(defun controller-set-buttons! (controller buttons)
  (setf (controller-buttons controller) (logand buttons #xFF))
  (when (controller-strobe controller)
    (setf (controller-shift controller) (controller-buttons controller)
          (controller-read-count controller) 0))
  controller)

(defun controller-write! (controller value &key (strobe-p t))
  (let ((new-strobe (and strobe-p (logbitp 0 value))))
    (when new-strobe
      (setf (controller-shift controller) (controller-buttons controller)
            (controller-read-count controller) 0))
    (when (and (controller-strobe controller) (not new-strobe))
      (setf (controller-shift controller) (controller-buttons controller)
            (controller-read-count controller) 0))
    (setf (controller-strobe controller) new-strobe))
  controller)

(defun controller-read (controller)
  (if (controller-strobe controller)
      (logand (controller-buttons controller) 1)
      (if (< (controller-read-count controller) 8)
          (prog1 (logand (controller-shift controller) 1)
            (setf (controller-shift controller)
                  (ash (controller-shift controller) -1)
                  (controller-read-count controller)
                  (1+ (controller-read-count controller))))
          1)))
