(in-package #:cl-nes)

(define-constant +nes-savestate-magic+ #(67 76 78 83))
(define-constant +nes-savestate-version+ 1)

(defun %savestate-append (output octets)
  (dotimes (index (length octets))
    (vector-push-extend (aref octets index) output)))

(defun %savestate-write-section (state-writer state output)
  (let ((section (funcall state-writer state)))
    (%state-write-u32 (length section) output)
    (%savestate-append output section)))

(defun %savestate-read-section (reader input position)
  (multiple-value-bind (length position) (%state-read-u32 input position)
    (let ((end (+ position length)))
      (when (> end (length input))
        (error 'invalid-savestate :reason :truncated))
      (let ((section (subseq input position end)))
        (multiple-value-bind (state state-position)
            (funcall reader section 0)
          (unless (= state-position length)
            (error 'invalid-savestate :reason :invalid-section))
          (values state end))))))

(defun nes-save-state (nes)
  "Return a deterministic octet vector containing the complete machine state."
  (let ((output (make-array 0 :adjustable t :fill-pointer 0
                            :element-type '(unsigned-byte 8))))
    (%savestate-append output +nes-savestate-magic+)
    (%state-write-u32 +nes-savestate-version+ output)
    (%savestate-write-section #'cpu-state-save (nes-cpu nes) output)
    (%savestate-write-section #'ppu-state-save (nes-ppu nes) output)
    (%savestate-write-section #'apu-state-save (nes-apu nes) output)
    (%savestate-write-section #'bus-state-save (nes-bus nes) output)
    (%savestate-write-section #'controller-state-save
                              (bus-controller-1 (nes-bus nes)) output)
    (%savestate-write-section #'controller-state-save
                              (bus-controller-2 (nes-bus nes)) output)
    (%state-write-value (bus-cartridge (nes-bus nes)) output)
    (%savestate-write-section #'nes-state-save nes output)
    output))

(defun %savestate-check-header (octets)
  (when (< (length octets) 8)
    (error 'invalid-savestate :reason :truncated))
  (dotimes (index 4)
    (unless (= (aref octets index) (aref +nes-savestate-magic+ index))
      (error 'invalid-savestate :reason :bad-magic)))
  (multiple-value-bind (version position) (%state-read-u32 octets 4)
    (declare (ignore position))
    (unless (= version +nes-savestate-version+)
      (error 'invalid-savestate :reason :unsupported-version))))

(defun nes-load-state (nes octets)
  "Restore NES from OCTETS and return NES.

The cartridge in NES is replaced only by its serialized mutable vector; the
bus, PPU, APU, and controller object identities remain stable."
  (unless (typep octets '(vector (unsigned-byte 8)))
    (error 'invalid-savestate :reason :not-octets))
  (%savestate-check-header octets)
  (let ((position 8))
    (multiple-value-bind (cpu position-next)
        (%savestate-read-section #'%cpu-read-state octets position)
      (setf position position-next)
      (multiple-value-bind (ppu position-next)
          (%savestate-read-section #'%ppu-read-state octets position)
        (setf position position-next)
        (multiple-value-bind (apu position-next)
            (%savestate-read-section #'%apu-read-state octets position)
          (setf position position-next)
          (multiple-value-bind (bus position-next)
              (%savestate-read-section #'%bus-read-state octets position)
            (setf position position-next)
            (multiple-value-bind (controller-1 position-next)
                (%savestate-read-section #'%controller-read-state octets position)
              (setf position position-next)
              (multiple-value-bind (controller-2 position-next)
                  (%savestate-read-section #'%controller-read-state octets position)
                (setf position position-next)
                (multiple-value-bind (cartridge position-next)
                    (%state-read-value octets position)
                  (unless (or (null cartridge) (typep cartridge 'cartridge))
                    (error 'invalid-savestate :reason :invalid-cartridge))
                  (setf position position-next)
                  (multiple-value-bind (machine position-next)
                      (%savestate-read-section #'%nes-read-state octets position)
                    (unless (= position-next (length octets))
                      (error 'invalid-savestate :reason :trailing-data))
                    (%cpu-apply-state (nes-cpu nes) cpu)
                    (%ppu-apply-state (nes-ppu nes) ppu)
                    (%apu-apply-state (nes-apu nes) apu)
                    (%bus-apply-state (nes-bus nes) bus)
                    (%controller-apply-state (bus-controller-1 (nes-bus nes)) controller-1)
                    (%controller-apply-state (bus-controller-2 (nes-bus nes)) controller-2)
                    (setf (bus-cartridge (nes-bus nes)) cartridge
                          (ppu-cartridge (nes-ppu nes)) cartridge)
                    (%nes-apply-state nes machine)
                    nes))))))))))
