(in-package #:cl-nes/frontend)

(defun %render-output-path (prefix frame format)
  (format nil "~A-~4,'0D.~(~A~)" prefix frame format))

(defun %crc32 (octets)
  (let ((crc #xffffffff))
    (loop for octet across octets
          do (setf crc (logxor crc octet))
             (dotimes (bit 8)
               (setf crc (if (logbitp 0 crc)
                             (logxor (ash crc -1) #xedb88320)
                             (ash crc -1)))))
    (logxor crc #xffffffff)))

(defun %write-u32-be (value stream)
  (dotimes (shift 4)
    (write-byte (ldb (byte 8 (* 8 (- 3 shift))) value) stream)))

(defun %png-chunk (type data stream)
  (%write-u32-be (length data) stream)
  (write-sequence type stream)
  (write-sequence data stream)
  (%write-u32-be (%crc32 (concatenate '(vector (unsigned-byte 8)) type data)) stream))

(defun %write-png (pathname framebuffer)
  (let* ((rgb (cl-nes:nes-framebuffer-rgb-octets framebuffer))
         (raw (make-array (* +nes-frame-height+ (1+ (* +nes-frame-width+ 3)))
                          :element-type '(unsigned-byte 8)))
         (cursor 0))
    (dotimes (y +nes-frame-height+)
      (setf (aref raw cursor) 0)
      (incf cursor)
      (replace raw rgb :start1 cursor :start2 (* y +nes-frame-width+ 3)
               :end2 (* (1+ y) +nes-frame-width+ 3))
      (incf cursor (* +nes-frame-width+ 3)))
    (with-open-file (stream pathname :direction :output :if-exists :supersede
                            :if-does-not-exist :create
                            :element-type '(unsigned-byte 8))
      (write-sequence #(137 80 78 71 13 10 26 10) stream)
      (let ((ihdr (make-array 13 :element-type '(unsigned-byte 8))))
        (setf (aref ihdr 0) 0 (aref ihdr 1) 0
              (aref ihdr 2) 1 (aref ihdr 3) 0
              (aref ihdr 4) 0 (aref ihdr 5) 0
              (aref ihdr 6) 0 (aref ihdr 7) 240)
        (setf (aref ihdr 8) 8 (aref ihdr 9) 2 (aref ihdr 10) 0
              (aref ihdr 11) 0 (aref ihdr 12) 0)
        (%png-chunk #(73 72 68 82) ihdr stream))
      ;; A zlib stream containing stored DEFLATE blocks.
      (let ((z (make-array (+ 6 (length raw) (* 5 (ceiling (length raw) 65535)))
                           :element-type '(unsigned-byte 8)))
            (at 0) (offset 0))
        (setf (aref z at) 120 (aref z (1+ at)) 1)
        (incf at 2)
        (loop while (< offset (length raw))
              for size = (min 65535 (- (length raw) offset))
              for final = (= (+ offset size) (length raw))
              do (setf (aref z at) (if final 1 0))
                 (incf at)
                 (setf (aref z at) (ldb (byte 8 0) size)
                       (aref z (1+ at)) (ldb (byte 8 8) size)
                       (aref z (+ at 2)) (ldb (byte 8 0) (logxor size #xffff))
                       (aref z (+ at 3)) (ldb (byte 8 8) (logxor size #xffff)))
                 (incf at 4)
                 (replace z raw :start1 at :start2 offset :end2 (+ offset size))
                 (incf at size)
                 (incf offset size))
        ;; Adler-32.
        (let ((a 1) (b 0))
          (loop for byte across raw do (setf a (mod (+ a byte) 65521)
                                               b (mod (+ b a) 65521)))
          (setf (aref z at) (ldb (byte 8 24) (logior (ash b 16) a))
                (aref z (1+ at)) (ldb (byte 8 16) (logior (ash b 16) a))
                (aref z (+ at 2)) (ldb (byte 8 8) (logior (ash b 16) a))
                (aref z (+ at 3)) (ldb (byte 8 0) (logior (ash b 16) a)))
          (incf at 4))
        (%png-chunk #(73 68 65 84) (subseq z 0 at) stream))
      (%png-chunk #(73 69 78 68) #() stream))
    pathname))

(defun run-render (rom frames prefix format)
  (let ((nes (make-nes :cartridge (load-cartridge rom))))
    (loop for frame from 1 to frames
          do (let ((framebuffer (nes-run-frame/k nes #'identity)))
               (ecase (intern (string-upcase format) :keyword)
                 (:ppm (nes-write-ppm (%render-output-path prefix frame format)
                                      framebuffer))
                 (:png (%write-png (%render-output-path prefix frame format)
                                   framebuffer)))))))
