(in-package #:cl-nes)

(defun %dispatch-cpu-opcode-00-7f (cpu bus opcode nmi-poll)
  (define-cpu-opcodes (cpu bus opcode)
    (:jam (#x02 #x12 #x22 #x32 #x42 #x52 #x62 #x72) %jam-op!)
    (#x00 (%brk-op! cpu bus nmi-poll))
    (:read #x01 :indx #'%ora! nil)
    (:rmw #x03 :indx #'%slo-value! 8)
    (:read #x05 :zp #'%ora! nil)
    (:rmw #x06 :zp #'%asl-value! 5)
    (:rmw #x07 :zp #'%slo-value! 5)
    (#x08 (%php-op! cpu bus))
    (:read #x09 :immediate #'%ora! nil)
    (:read #x0B :immediate #'%aac! nil)
    (:nop (#x04 #x44 #x64) :zp 3)
    (:nop (#x14 #x34 #x54 #x74) :zpx 4)
    (#x0A (%accumulator-rmw-op! cpu #'%asl-value!))
    (:read #x0D :abs #'%ora! nil)
    (:rmw #x0E :abs #'%asl-value! 6)
    (:nop #x0C :abs 4)
    (:rmw #x0F :abs #'%slo-value! 6)
    (:branch #x10 (not (%flag-set-p cpu +flag-negative+)))
    (:read #x11 :indy #'%ora! t)
    (:rmw #x13 :indy #'%slo-value! 8)
    (:read #x15 :zpx #'%ora! nil)
    (:rmw #x16 :zpx #'%asl-value! 6)
    (:rmw #x17 :zpx #'%slo-value! 6)
    (#x18 (%set-flag! cpu +flag-carry+ nil) 2)
    (:read #x19 :absy #'%ora! t)
    (:rmw #x1B :absy #'%slo-value! 7)
    ((#x1A #x3A #x5A #x7A) 2)
    (:nop (#x1C #x3C #x5C #x7C) :absx 4)
    (:read #x1D :absx #'%ora! t)
    (:rmw #x1E :absx #'%asl-value! 7)
    (:rmw #x1F :absx #'%slo-value! 7)

    (#x20 (%jsr-op! cpu bus))
    (:read #x21 :indx #'%and! nil)
    (:rmw #x23 :indx #'%rla-value! 8)
    (#x24
     (multiple-value-bind (operand ignored)
         (%address-for-mode cpu bus :zp)
       (declare (ignore ignored))
       (%bit! cpu (bus-read bus operand))
       3))
    (:read #x25 :zp #'%and! nil)
    (:rmw #x26 :zp #'%rol-value! 5)
    (:rmw #x27 :zp #'%rla-value! 5)
    (#x28 (%plp-op! cpu bus))
    (:read #x29 :immediate #'%and! nil)
    (:read #x2B :immediate #'%aac! nil)
    (#x2A (%accumulator-rmw-op! cpu #'%rol-value!))
    (#x2C
     (%bit! cpu (bus-read bus (%fetch-word cpu bus)))
     4)
    (:read #x2D :abs #'%and! nil)
    (:rmw #x2E :abs #'%rol-value! 6)
    (:rmw #x2F :abs #'%rla-value! 6)
    (:branch #x30 (%flag-set-p cpu +flag-negative+))
    (:read #x31 :indy #'%and! t)
    (:rmw #x33 :indy #'%rla-value! 8)
    (:read #x35 :zpx #'%and! nil)
    (:rmw #x36 :zpx #'%rol-value! 6)
    (:rmw #x37 :zpx #'%rla-value! 6)
    (#x38 (%set-flag! cpu +flag-carry+ t) 2)
    (:read #x39 :absy #'%and! t)
    (:rmw #x3B :absy #'%rla-value! 7)
    (:read #x3D :absx #'%and! t)
    (:rmw #x3E :absx #'%rol-value! 7)
    (:rmw #x3F :absx #'%rla-value! 7)

    (#x40 (%rti-op! cpu bus))
    (:read #x41 :indx #'%eor! nil)
    (:rmw #x43 :indx #'%sre-value! 8)
    (:read #x45 :zp #'%eor! nil)
    (:rmw #x46 :zp #'%lsr-value! 5)
    (:rmw #x47 :zp #'%sre-value! 5)
    (#x48 (%pha-op! cpu bus))
    (:read #x49 :immediate #'%eor! nil)
    (:read #x4B :immediate #'%asr! nil)
    (#x4A (%accumulator-rmw-op! cpu #'%lsr-value!))
    (#x4C
     (setf (cpu-pc cpu) (%fetch-word cpu bus))
     3)
    (:read #x4D :abs #'%eor! nil)
    (:rmw #x4E :abs #'%lsr-value! 6)
    (:rmw #x4F :abs #'%sre-value! 6)
    (:branch #x50 (not (%flag-set-p cpu +flag-overflow+)))
    (:read #x51 :indy #'%eor! t)
    (:rmw #x53 :indy #'%sre-value! 8)
    (:read #x55 :zpx #'%eor! nil)
    (:rmw #x56 :zpx #'%lsr-value! 6)
    (:rmw #x57 :zpx #'%sre-value! 6)
    (#x58 (%interrupt-disable-op! cpu nil))
    (:read #x59 :absy #'%eor! t)
    (:rmw #x5B :absy #'%sre-value! 7)
    (:read #x5D :absx #'%eor! t)
    (:rmw #x5E :absx #'%lsr-value! 7)
    (:rmw #x5F :absx #'%sre-value! 7)

    (#x60 (%rts-op! cpu bus))
    (:read #x61 :indx #'%adc! nil)
    (:rmw #x63 :indx #'%rra-value! 8)
    (:read #x65 :zp #'%adc! nil)
    (:rmw #x66 :zp #'%ror-value! 5)
    (:rmw #x67 :zp #'%rra-value! 5)
    (#x68 (%pla-op! cpu bus))
    (:read #x69 :immediate #'%adc! nil)
    (:read #x6B :immediate #'%arr! nil)
    (#x6A (%accumulator-rmw-op! cpu #'%ror-value!))
    (#x6C (%jump-indirect cpu bus))
    (:read #x6D :abs #'%adc! nil)
    (:rmw #x6E :abs #'%ror-value! 6)
    (:rmw #x6F :abs #'%rra-value! 6)
    (:branch #x70 (%flag-set-p cpu +flag-overflow+))
    (:read #x71 :indy #'%adc! t)
    (:rmw #x73 :indy #'%rra-value! 8)
    (:read #x75 :zpx #'%adc! nil)
    (:rmw #x76 :zpx #'%ror-value! 6)
    (:rmw #x77 :zpx #'%rra-value! 6)
    (#x78 (%interrupt-disable-op! cpu t))
    (:read #x79 :absy #'%adc! t)
    (:rmw #x7B :absy #'%rra-value! 7)
    (:read #x7D :absx #'%adc! t)
    (:rmw #x7E :absx #'%ror-value! 7)
    (:rmw #x7F :absx #'%rra-value! 7)
    (otherwise nil)))
