(in-package #:cl-nes/test)

(describe "Coverage: PPU mapper contracts"
  (it "clocks mapper A12 from CPU-visible address and data accesses"
    (with-mmc3-cartridge (cartridge)
      (let ((ppu (make-ppu cartridge)))
        (setf (cl-nes::cartridge-mapper4-ppu-a12-low-cycles cartridge) 24
              (cl-nes::cartridge-mapper4-ppu-a12-high-p cartridge) nil)
        (ppu-write-register! ppu 6 #x10)
        (expect (cl-nes::cartridge-mapper4-ppu-a12-low-cycles cartridge)
                :to-be 24)
        (expect (cl-nes::cartridge-mapper4-ppu-a12-high-p cartridge)
                :to-be nil)
        (ppu-write-register! ppu 6 #x00)
        (expect (cl-nes::ppu-vram-address ppu) :to-be #x1000)
        (expect (cl-nes::cartridge-mapper4-ppu-a12-high-p cartridge)
                :to-be t)
        (expect (cl-nes::cartridge-mapper4-ppu-a12-low-cycles cartridge)
                :to-be 0)
        (ppu-write-register! ppu 6 #x20)
        (ppu-write-register! ppu 6 #x00)
        (expect (cl-nes::ppu-vram-address ppu) :to-be #x2000)
        (expect (cl-nes::cartridge-mapper4-ppu-a12-high-p cartridge)
                :to-be nil)
        (expect (cl-nes::cartridge-mapper4-ppu-a12-low-cycles cartridge)
                :to-be 24)
        (ppu-write-register! ppu 7 #x12)
        (expect (cl-nes::ppu-vram-address ppu) :to-be #x2001)
        (expect (cl-nes::cartridge-mapper4-ppu-a12-high-p cartridge)
                :to-be nil)
        (expect (cl-nes::cartridge-mapper4-ppu-a12-low-cycles cartridge)
                :to-be 25)))))
