(in-package #:cl-nes/test)

(describe "PPU background rendering transitions"
  (it "selects background quadrants"
    (let* ((cartridge (make-fixture-cartridge))
           (ppu (make-ppu cartridge)))
      (ppu-write-register! ppu #x00 #x10)
      (ppu-write-register! ppu #x01 #x06)
      (ppu-write-vram! ppu #x2001 #x01)
      (ppu-write-vram! ppu #x1010 #x80)
      (ppu-write-vram! ppu #x3F01 #x22)
      (multiple-value-bind (color present)
          (cl-nes::%background-pixel ppu 8 0)
        (expect color :to-be #x22)
        (expect present :to-be t))
      (multiple-value-bind (color present)
          (cl-nes::%background-pixel ppu 0 0)
        (expect color :to-be 0)
        (expect present :to-be nil))
      (ppu-write-vram! ppu #x2042 #x01)
      (ppu-write-vram! ppu #x23C0 #xC0)
      (ppu-write-vram! ppu #x3F0D #x33)
      (multiple-value-bind (color present)
          (cl-nes::%background-pixel ppu 16 16)
        (expect color :to-be #x33)
        (expect present :to-be t))))
  (it "packs grayscale and emphasis into dot-rendered pixels"
    (let ((ppu (make-ppu (make-fixture-cartridge))))
      (setf (ppu-mask ppu) #xE1)
      (expect (cl-nes::%ppu-palette-pixel ppu #x2F)
              :to-be (logior #x20 (ash 7 6))))))
  (it "shows a scroll change at the following scanline boundary"
    (let ((ppu (make-ppu (make-fixture-cartridge))))
      (setf (ppu-mask ppu) #x02
            (cl-nes::ppu-rendering-mask-valid-p ppu) nil)
      (ppu-write-vram! ppu #x0000 #xFF)
      (ppu-write-vram! ppu #x0018 #xFF)
      (ppu-write-vram! ppu #x2000 0)
      (ppu-write-vram! ppu #x2001 1)
      (ppu-write-vram! ppu #x3F01 #x11)
      (ppu-write-vram! ppu #x3F02 #x22)
      (setf (cl-nes::ppu-vram-address ppu) 0
            (cl-nes::ppu-scanline ppu) 0
            (cl-nes::ppu-dot ppu) 0)
      (ppu-tick! ppu 100)
      (setf (cl-nes::ppu-temporary-address ppu) #x0401)
      (ppu-tick! ppu 241)
      (ppu-tick! ppu)
      (expect (aref (ppu-framebuffer ppu) 0) :to-be #x11)
      (expect (aref (ppu-framebuffer ppu) 256)
              :to-be #x22)))
