(in-package #:cl-nes)

(defun %apu-write-pulse-control! (pulse value)
  (setf (apu-pulse-duty pulse) (ldb (byte 2 6) value))
  (let ((envelope (apu-pulse-envelope pulse)))
    (setf (apu-envelope-loop-p envelope) (logbitp 5 value)
          (apu-envelope-constant-volume-p envelope) (logbitp 4 value)
          (apu-envelope-volume envelope) (logand value #x0F))))

(defun %apu-write-pulse-sweep! (pulse value)
  (setf (apu-pulse-sweep-enabled-p pulse) (logbitp 7 value)
        (apu-pulse-sweep-period pulse) (1+ (ldb (byte 3 4) value))
        (apu-pulse-sweep-negate-p pulse) (logbitp 3 value)
        (apu-pulse-sweep-shift pulse) (logand value 7)
        (apu-pulse-sweep-reload-p pulse) t))

(defun %apu-write-triangle-control! (triangle value)
  (setf (apu-triangle-control-p triangle) (logbitp 7 value)
        (apu-triangle-linear-reload-value triangle) (logand value #x7F)))

(defun %apu-write-noise-control! (noise value)
  (let ((envelope (apu-noise-envelope noise)))
    (setf (apu-envelope-loop-p envelope) (logbitp 5 value)
          (apu-envelope-constant-volume-p envelope) (logbitp 4 value)
          (apu-envelope-volume envelope) (logand value #x0F))))

(defun apu-write-register! (apu address value)
  (let ((value (logand value #xFF)))
    (case (logand address #xFFFF)
      (#x4000 (%apu-write-pulse-control! (apu-pulse-1 apu) value))
      (#x4001 (%apu-write-pulse-sweep! (apu-pulse-1 apu) value))
      (#x4002 (setf (apu-pulse-timer-period (apu-pulse-1 apu))
                    (logior (logand (apu-pulse-timer-period (apu-pulse-1 apu)) #x700)
                            value)))
      (#x4003 (let ((pulse (apu-pulse-1 apu)))
                (when (apu-pulse-enabled-p pulse)
                  (setf (apu-pulse-length-counter pulse) (%apu-length-value value)
                        (apu-pulse-length-reload-p pulse) t))
                (setf (apu-pulse-timer-period pulse)
                      (logior (ash (logand value 7) 8)
                              (logand (apu-pulse-timer-period pulse) #xFF))
                      (apu-pulse-sequence pulse) 0
                      (apu-envelope-start-p (apu-pulse-envelope pulse)) t)))
      (#x4004 (%apu-write-pulse-control! (apu-pulse-2 apu) value))
      (#x4005 (%apu-write-pulse-sweep! (apu-pulse-2 apu) value))
      (#x4006 (setf (apu-pulse-timer-period (apu-pulse-2 apu))
                    (logior (logand (apu-pulse-timer-period (apu-pulse-2 apu)) #x700)
                            value)))
      (#x4007 (let ((pulse (apu-pulse-2 apu)))
                (when (apu-pulse-enabled-p pulse)
                  (setf (apu-pulse-length-counter pulse) (%apu-length-value value)
                        (apu-pulse-length-reload-p pulse) t))
                (setf (apu-pulse-timer-period pulse)
                      (logior (ash (logand value 7) 8)
                              (logand (apu-pulse-timer-period pulse) #xFF))
                      (apu-pulse-sequence pulse) 0
                      (apu-envelope-start-p (apu-pulse-envelope pulse)) t)))
      (#x4008 (%apu-write-triangle-control! (apu-triangle apu) value))
      (#x400A (setf (apu-triangle-timer-period (apu-triangle apu))
                    (logior (logand (apu-triangle-timer-period (apu-triangle apu)) #x700)
                            value)))
      (#x400B (let ((triangle (apu-triangle apu)))
                (when (apu-triangle-enabled-p triangle)
                  (setf (apu-triangle-length-counter triangle)
                        (%apu-length-value value)
                        (apu-triangle-length-reload-p triangle) t))
                (setf (apu-triangle-timer-period triangle)
                      (logior (ash (logand value 7) 8)
                              (logand (apu-triangle-timer-period triangle) #xFF))
                      (apu-triangle-linear-reload-p triangle) t)))
      (#x400C (%apu-write-noise-control! (apu-noise apu) value))
      (#x400E (let ((noise (apu-noise apu)))
                (setf (apu-noise-mode-p noise) (logbitp 7 value)
                      (apu-noise-timer-period noise)
                      (aref +apu-noise-period-table+ (logand value #x0F)))))
      (#x400F (let ((noise (apu-noise apu)))
                (when (apu-noise-enabled-p noise)
                  (setf (apu-noise-length-counter noise) (%apu-length-value value)
                        (apu-noise-length-reload-p noise) t))
                (setf (apu-envelope-start-p (apu-noise-envelope noise)) t)))
      (#x4010 (let ((dmc (apu-dmc apu)))
                (setf (apu-dmc-irq-enabled-p dmc) (logbitp 7 value)
                      (apu-dmc-loop-p dmc) (logbitp 6 value)
                      (apu-dmc-rate-index dmc) (logand value #x0F)
                      (apu-dmc-timer-period dmc)
                      (aref +apu-dmc-rate-table+ (logand value #x0F)))
                (unless (apu-dmc-irq-enabled-p dmc)
                  (setf (apu-dmc-irq-pending-p dmc) nil))))
      (#x4011 (setf (apu-dmc-output (apu-dmc apu)) (logand value #x7F)))
      (#x4012 (setf (apu-dmc-sample-address (apu-dmc apu))
                    (+ #xC000 (ash value 6))))
      (#x4013 (setf (apu-dmc-sample-length (apu-dmc apu))
                    (1+ (ash value 4))))
      (#x4015 (%apu-write-status! apu value))
      (#x4017 (%apu-write-frame-counter! apu value)))
    value))
