(in-package #:cl-nes)

(defstruct (apu-envelope (:constructor %make-apu-envelope))
  (loop-p nil)
  (constant-volume-p nil)
  (volume 0 :type fixnum)
  (start-p nil)
  (divider 0 :type fixnum)
  (decay 0 :type fixnum))

(defstruct (apu-pulse (:constructor %make-apu-pulse))
  (enabled-p nil)
  (duty 0 :type fixnum)
  (sequence 0 :type fixnum)
  (timer 0 :type fixnum)
  (timer-period 0 :type fixnum)
  (length-counter 0 :type fixnum)
  (envelope (%make-apu-envelope))
  (sweep-enabled-p nil)
  (sweep-period 0 :type fixnum)
  (sweep-negate-p nil)
  (sweep-shift 0 :type fixnum)
  (sweep-divider 0 :type fixnum)
  (sweep-reload-p nil))

(defstruct (apu-triangle (:constructor %make-apu-triangle))
  (enabled-p nil)
  (timer 0 :type fixnum)
  (timer-period 0 :type fixnum)
  (length-counter 0 :type fixnum)
  (linear-counter 0 :type fixnum)
  (linear-reload-value 0 :type fixnum)
  (linear-reload-p nil)
  (control-p nil)
  (sequence 0 :type fixnum))

(defstruct (apu-noise (:constructor %make-apu-noise))
  (enabled-p nil)
  (mode-p nil)
  (timer 0 :type fixnum)
  (timer-period 4 :type fixnum)
  (length-counter 0 :type fixnum)
  (shift-register #x1 :type fixnum)
  (envelope (%make-apu-envelope)))

(defstruct (apu-dmc (:constructor %make-apu-dmc))
  (enabled-p nil)
  (irq-enabled-p nil)
  (loop-p nil)
  (irq-pending-p nil)
  (rate-index 0 :type fixnum)
  (timer 0 :type fixnum)
  (timer-period 428 :type fixnum)
  (output 0 :type fixnum)
  (sample-address #xC000 :type fixnum)
  (current-address #xC000 :type fixnum)
  (sample-length 1 :type fixnum)
  (bytes-remaining 0 :type fixnum)
  (sample-buffer 0 :type fixnum)
  (sample-buffer-empty-p t)
  (shift-register 0 :type fixnum)
  (bits-remaining 0 :type fixnum)
  (silence-p t))

(define-hardware-state apu
  ((pulse-1 (%make-apu-pulse :envelope (%make-apu-envelope)) apu-pulse)
   (pulse-2 (%make-apu-pulse :envelope (%make-apu-envelope)) apu-pulse)
   (triangle (%make-apu-triangle) apu-triangle)
   (noise (%make-apu-noise :envelope (%make-apu-envelope)) apu-noise)
   (dmc (%make-apu-dmc) apu-dmc)
   (frame-cycle 0 fixnum apu-frame-cycle)
   (frame-step 0 fixnum apu-frame-step)
   (five-step-p nil nil apu-five-step-p)
   (frame-last-five-step-p nil nil apu-frame-last-five-step-p)
   (frame-irq-inhibit-p nil nil apu-frame-irq-inhibit-p)
   (frame-irq-pending-p nil nil apu-frame-irq-pending-p)
   (frame-irq-repeat-count 0 fixnum apu-frame-irq-repeat-count)
   (frame-tail-step 0 fixnum apu-frame-tail-step)
   (frame-reset-delay 0 fixnum apu-frame-reset-delay)
   (frame-reset-five-step-p nil nil apu-frame-reset-five-step-p)
   (frame-reset-irq-inhibit-p nil nil apu-frame-reset-irq-inhibit-p)
   (cycle-parity 0 fixnum apu-cycle-parity)
   (memory-reader nil nil apu-memory-reader))
  :reset-preserve (memory-reader)
  :console-reset %apu-console-reset!
  :console-preserve
  ((frame-last-five-step-p)
   (pulse-1 apu-pulse-duty)
   (pulse-1 apu-pulse-timer-period)
   (pulse-1 apu-pulse-sweep-enabled-p)
   (pulse-1 apu-pulse-sweep-period)
   (pulse-1 apu-pulse-sweep-negate-p)
   (pulse-1 apu-pulse-sweep-shift)
   (pulse-1 apu-pulse-envelope apu-envelope-loop-p)
   (pulse-1 apu-pulse-envelope apu-envelope-constant-volume-p)
   (pulse-1 apu-pulse-envelope apu-envelope-volume)
   (pulse-2 apu-pulse-duty)
   (pulse-2 apu-pulse-timer-period)
   (pulse-2 apu-pulse-sweep-enabled-p)
   (pulse-2 apu-pulse-sweep-period)
   (pulse-2 apu-pulse-sweep-negate-p)
   (pulse-2 apu-pulse-sweep-shift)
   (pulse-2 apu-pulse-envelope apu-envelope-loop-p)
   (pulse-2 apu-pulse-envelope apu-envelope-constant-volume-p)
   (pulse-2 apu-pulse-envelope apu-envelope-volume)
   (triangle apu-triangle-timer-period)
   (triangle apu-triangle-linear-reload-value)
   (triangle apu-triangle-control-p)
   (noise apu-noise-mode-p)
   (noise apu-noise-timer-period)
   (noise apu-noise-envelope apu-envelope-loop-p)
   (noise apu-noise-envelope apu-envelope-constant-volume-p)
   (noise apu-noise-envelope apu-envelope-volume)
   (dmc apu-dmc-irq-enabled-p)
   (dmc apu-dmc-loop-p)
   (dmc apu-dmc-rate-index)
   (dmc apu-dmc-timer-period)
   (dmc apu-dmc-output)
   (dmc apu-dmc-sample-address)
   (dmc apu-dmc-sample-length)))
