(in-package #:cl-nes)

(define-hardware-state apu-envelope
  ((loop-p nil nil)
   (constant-volume-p nil nil)
   (volume 0 fixnum)
   (start-p nil nil)
   (divider 0 fixnum)
   (decay 0 fixnum))
  :constructor %make-apu-envelope)

(define-hardware-state apu-pulse
  ((enabled-p nil nil)
   (duty 0 fixnum)
   (sequence 0 fixnum)
   (timer 0 fixnum)
   (timer-period 0 fixnum)
   (length-counter 0 fixnum)
   (length-reload-p nil nil)
   (envelope (%make-apu-envelope) apu-envelope)
   (sweep-enabled-p nil nil)
   (sweep-period 0 fixnum)
   (sweep-negate-p nil nil)
   (sweep-shift 0 fixnum)
   (sweep-divider 0 fixnum)
   (sweep-reload-p nil nil))
  :constructor %make-apu-pulse)

(define-hardware-state apu-triangle
  ((enabled-p nil nil)
   (timer 0 fixnum)
   (timer-period 0 fixnum)
   (length-counter 0 fixnum)
   (length-reload-p nil nil)
   (linear-counter 0 fixnum)
   (linear-reload-value 0 fixnum)
   (linear-reload-p nil nil)
   (control-p nil nil)
   (sequence 0 fixnum)
   (dac-output 0 fixnum))
  :constructor %make-apu-triangle)

(define-hardware-state apu-noise
  ((enabled-p nil nil)
   (mode-p nil nil)
   (timer 0 fixnum)
   (timer-period 4 fixnum)
   (length-counter 0 fixnum)
   (length-reload-p nil nil)
   (shift-register #x1 fixnum)
   (envelope (%make-apu-envelope) apu-envelope))
  :constructor %make-apu-noise)

(define-hardware-state apu-dmc
  ((enabled-p nil nil)
   (irq-enabled-p nil nil)
   (loop-p nil nil)
   (irq-pending-p nil nil)
   (rate-index 0 fixnum)
   (timer 0 fixnum)
   (timer-period 428 fixnum)
   (output 0 fixnum)
   (sample-address #xC000 fixnum)
   (current-address #xC000 fixnum)
   (sample-length 1 fixnum)
   (bytes-remaining 0 fixnum)
   (sample-buffer 0 fixnum)
   (sample-buffer-empty-p t nil)
   (shift-register 0 fixnum)
   (bits-remaining 0 fixnum)
   (silence-p t nil))
  :constructor %make-apu-dmc)

(define-hardware-state apu
  ((pulse-1 (%make-apu-pulse :envelope (%make-apu-envelope)) apu-pulse)
   (pulse-2 (%make-apu-pulse :envelope (%make-apu-envelope)) apu-pulse)
   (triangle (%make-apu-triangle) apu-triangle)
   (noise (%make-apu-noise :envelope (%make-apu-envelope)) apu-noise)
   (dmc (%make-apu-dmc) apu-dmc)
   (frame-cycle 0 fixnum apu-frame-cycle)
   (frame-step 0 fixnum apu-frame-step)
   (five-step-p nil nil apu-five-step-p)
   (frame-last-five-step-p nil nil apu-frame-last-five-step-p)
   (frame-irq-inhibit-p nil nil apu-frame-irq-inhibit-p)
   (frame-irq-pending-p nil nil apu-frame-irq-pending-p)
   (frame-event-offset 0 fixnum apu-frame-event-offset)
   (frame-irq-repeat-count 0 fixnum apu-frame-irq-repeat-count)
   (frame-tail-step 0 fixnum apu-frame-tail-step)
   (frame-reset-delay 0 fixnum apu-frame-reset-delay)
   (frame-reset-five-step-p nil nil apu-frame-reset-five-step-p)
   (frame-reset-irq-inhibit-p nil nil apu-frame-reset-irq-inhibit-p)
   (cycle-parity 0 fixnum apu-cycle-parity)
   (memory-reader nil nil apu-memory-reader))
  :reset-preserve (memory-reader)
  :exclude (memory-reader)
  :console-reset apu-console-reset!
  :console-reset-values (((frame-reset-delay) 3))
  :console-preserve
  ((frame-last-five-step-p)
   (pulse-1 apu-pulse-duty)
   (pulse-1 apu-pulse-timer-period)
   (pulse-1 apu-pulse-sweep-enabled-p)
   (pulse-1 apu-pulse-sweep-period)
   (pulse-1 apu-pulse-sweep-negate-p)
   (pulse-1 apu-pulse-sweep-shift)
   (pulse-1 apu-pulse-envelope apu-envelope-loop-p)
   (pulse-1 apu-pulse-envelope apu-envelope-constant-volume-p)
   (pulse-1 apu-pulse-envelope apu-envelope-volume)
   (pulse-2 apu-pulse-duty)
   (pulse-2 apu-pulse-timer-period)
   (pulse-2 apu-pulse-sweep-enabled-p)
   (pulse-2 apu-pulse-sweep-period)
   (pulse-2 apu-pulse-sweep-negate-p)
   (pulse-2 apu-pulse-sweep-shift)
   (pulse-2 apu-pulse-envelope apu-envelope-loop-p)
   (pulse-2 apu-pulse-envelope apu-envelope-constant-volume-p)
   (pulse-2 apu-pulse-envelope apu-envelope-volume)
   (triangle apu-triangle-timer-period)
   (triangle apu-triangle-linear-reload-value)
   (triangle apu-triangle-control-p)
   (noise apu-noise-mode-p)
   (noise apu-noise-timer-period)
   (noise apu-noise-envelope apu-envelope-loop-p)
   (noise apu-noise-envelope apu-envelope-constant-volume-p)
   (noise apu-noise-envelope apu-envelope-volume)
   (dmc apu-dmc-irq-enabled-p)
   (dmc apu-dmc-loop-p)
   (dmc apu-dmc-rate-index)
   (dmc apu-dmc-timer-period)
   (dmc apu-dmc-output)
   (dmc apu-dmc-sample-address)
   (dmc apu-dmc-sample-length)))
