(in-package #:cl-nes)

(defconstant +ines-header-size+ 16)
(defconstant +ines-trainer-size+ 512)
(defconstant +prg-bank-size+ (* 16 1024))
(defconstant +prg-bank-8k-size+ (* 8 1024))
(defconstant +prg-ram-bank-size+ (* 8 1024))
(defconstant +chr-bank-1k-size+ 1024)
(defconstant +chr-bank-4k-size+ (* 4 1024))
(defconstant +chr-bank-size+ (* 8 1024))
(defconstant +mapper4-a12-low-filter-cycles+ 24)
(define-constant +mapper-definitions+
  '((69 :cpu-clock-required-p t)))

(define-hardware-state cartridge-mapper5-state
  ((prg-mode 3 nil)
   (chr-mode 3 nil)
   (prg-banks (make-array 8 :element-type '(unsigned-byte 8)
                          :initial-element 0) vector)
   (chr-banks (make-array 12 :element-type '(unsigned-byte 8)
                          :initial-element 0) vector)
   (prg-ram-protect-1 0 nil)
   (prg-ram-protect-2 0 nil)
   (exram-mode 0 nil)
   (nametable-mapping 0 nil)
   (fill-tile 0 nil)
   (fill-attribute 0 nil)
   (split-control 0 nil)
   (split-scroll 0 nil)
   (split-bank 0 nil)
   (irq-scanline 0 nil)
   (irq-enabled-p nil nil)
   (irq-pending-p nil nil)
   (in-frame-p nil nil)
   (multiplier-a 0 nil)
   (multiplier-b 0 nil)
   (exram (make-array #x400 :element-type '(unsigned-byte 8)
                      :initial-element 0) vector))
  :constructor %make-cartridge-mapper5-state-instance
  :reset %reset-cartridge-mapper5-state!)

(define-hardware-state mapper-state-core
  ((mapper-shift #x10 nil)
   (mapper-control #x0C nil)
   (mapper-chr-bank-0 0 nil)
   (mapper-chr-bank-1 0 nil)
   (mapper-prg-bank-1 0 nil)
   (mapper-registers (make-array 8 :element-type '(unsigned-byte 8)
                                 :initial-element 0) vector)
   (mapper-register-select 0 nil)
   (mapper-mode 0 nil)
   (mapper-outer-bank #xFF nil)
   (mapper69-command 0 nil)
   (mapper69-registers (make-array 16 :element-type '(unsigned-byte 8)
                                   :initial-element 0) vector)
   (mapper69-irq-counter 0 nil)
   (mapper69-irq-enabled-p nil nil)
   (mapper69-irq-pending-p nil nil)
   (mapper1-ppu-a12-high-p nil nil)
   (mapper1-last-write-cycle nil nil))
  :constructor %make-mapper-state-core-instance
  :reset %reset-mapper-state-core!)

(define-hardware-state cartridge-mapper4-state
  ((mapper4-bank-select 0 nil)
   (mapper4-registers (make-array 8 :element-type '(unsigned-byte 8)
                                  :initial-element 0) vector)
   (mapper4-variant :mmc3 nil)
   (mapper4-prg-ram-enabled-p t nil)
   (mapper4-prg-ram-write-protected-p nil nil)
   (mapper4-irq-latch 0 nil)
   (mapper4-irq-counter 0 nil)
   (mapper4-irq-reload-p nil nil)
   (mapper4-irq-enabled-p nil nil)
   (mapper4-irq-pending-p nil nil)
   (mapper4-ppu-a12-high-p nil nil)
   (mapper4-ppu-a12-low-cycles 0 nil))
  :constructor %make-cartridge-mapper4-state-instance
  :reset %reset-cartridge-mapper4-state!)

(deftype cartridge () 'simple-vector)

(defun %install-vector-accessor-pair (reader writer index)
  (setf (fdefinition reader)
        (lambda (state) (aref state index))
        (fdefinition writer)
        (lambda (state value) (setf (aref state index) value)))
  nil)

(defun %install-vector-accessor-pairs (specs)
  (dolist (spec specs)
    (destructuring-bind (reader writer index) spec
      (%install-vector-accessor-pair reader writer index)))
  nil)

(defun %make-cartridge-instance ()
  (make-array 18 :initial-element nil))

(%install-vector-accessor-pairs
 '((cartridge-prg-rom set-cartridge-prg-rom! 0)
   (cartridge-chr-rom set-cartridge-chr-rom! 1)
   (cartridge-prg-ram set-cartridge-prg-ram! 2)
   (cartridge-mapper set-cartridge-mapper! 3)
   (cartridge-mirroring set-cartridge-mirroring! 4)
   (cartridge-initial-mirroring set-cartridge-initial-mirroring! 5)
   (cartridge-battery-backed-p set-cartridge-battery-backed-p! 6)
   (cartridge-four-screen-p set-cartridge-four-screen-p! 7)
   (cartridge-chr-writable-p set-cartridge-chr-writable-p! 8)
   (cartridge-prg-bank set-cartridge-prg-bank! 9)
   (cartridge-chr-bank set-cartridge-chr-bank! 10)
   (cartridge-mapper5-state set-cartridge-mapper5-state! 11)
   (cartridge-mapper4-state set-cartridge-mapper4-state! 12)
   (cartridge-mapper-state set-cartridge-mapper-state! 13)
   (cartridge-submapper set-cartridge-submapper! 14)
   (cartridge-bus-conflict-p set-cartridge-bus-conflict-p! 15)
   (cartridge-cpu-clock-required-p set-cartridge-cpu-clock-required-p! 16)
   (cartridge-battery-dirty-p set-cartridge-battery-dirty-p! 17)))
