(in-package #:cl-nes)

(defconstant +ines-header-size+ 16)
(defconstant +ines-trainer-size+ 512)
(defconstant +prg-bank-size+ (* 16 1024))
(defconstant +prg-bank-8k-size+ (* 8 1024))
(defconstant +prg-ram-bank-size+ (* 8 1024))
(defconstant +chr-bank-1k-size+ 1024)
(defconstant +chr-bank-4k-size+ (* 4 1024))
(defconstant +chr-bank-size+ (* 8 1024))
(defconstant +mapper4-a12-low-filter-cycles+ 3)
(define-constant +mapper-definitions+
  '((4 :cpu-clock-required-p t)
    (69 :cpu-clock-required-p t)))

(define-hardware-state cartridge-mapper5-state
  ((prg-mode 3 nil)
   (chr-mode 3 nil)
   (prg-banks (make-array 8 :element-type '(unsigned-byte 8)
                          :initial-element 0) vector)
   (chr-banks (make-array 12 :element-type '(unsigned-byte 8)
                          :initial-element 0) vector)
   (prg-ram-protect-1 0 nil)
   (prg-ram-protect-2 0 nil)
   (exram-mode 0 nil)
   (nametable-mapping 0 nil)
   (fill-tile 0 nil)
   (fill-attribute 0 nil)
   (split-control 0 nil)
   (split-scroll 0 nil)
   (split-bank 0 nil)
   (irq-scanline 0 nil)
   (irq-enabled-p nil nil)
   (irq-pending-p nil nil)
   (in-frame-p nil nil)
   (multiplier-a 0 nil)
   (multiplier-b 0 nil)
   (exram (make-array #x400 :element-type '(unsigned-byte 8)
                      :initial-element 0) vector))
  :constructor %make-cartridge-mapper5-state-instance
  :reset %reset-cartridge-mapper5-state!)

(define-hardware-state mapper-state-core
  ((mapper-shift #x10 nil)
   (mapper-control #x0C nil)
   (mapper-chr-bank-0 0 nil)
   (mapper-chr-bank-1 0 nil)
   (mapper-prg-bank-1 0 nil)
   (mapper-registers (make-array 8 :element-type '(unsigned-byte 8)
                                 :initial-element 0) vector)
   (mapper-register-select 0 nil)
   (mapper-mode 0 nil)
   (mapper-outer-bank #xFF nil)
   (mapper69-command 0 nil)
   (mapper69-registers (make-array 16 :element-type '(unsigned-byte 8)
                                   :initial-element 0) vector)
   (mapper69-irq-counter 0 nil)
   (mapper69-irq-enabled-p nil nil)
   (mapper69-irq-pending-p nil nil)
   (mapper1-ppu-a12-high-p nil nil)
   (mapper1-last-write-cycle nil nil))
  :constructor %make-mapper-state-core-instance
  :reset %reset-mapper-state-core!)

(define-hardware-state cartridge-mapper4-state
  ((mapper4-bank-select 0 nil)
   (mapper4-registers (make-array 8 :element-type '(unsigned-byte 8)
                                  :initial-element 0) vector)
   (mapper4-variant :mmc3 nil)
   (mapper4-prg-ram-enabled-p t nil)
   (mapper4-prg-ram-write-protected-p nil nil)
   (mapper4-irq-latch 0 nil)
   (mapper4-irq-counter 0 nil)
   (mapper4-irq-reload-p nil nil)
   (mapper4-irq-enabled-p nil nil)
   (mapper4-irq-pending-p nil nil)
   (mapper4-ppu-a12-high-p nil nil)
   (mapper4-a12-low-m2-cycles 0 nil))
  :constructor %make-cartridge-mapper4-state-instance
  :reset %reset-cartridge-mapper4-state!)

(define-hardware-state cartridge
  ((prg-rom #() vector)
   (chr-rom #() vector)
   (prg-ram #() vector)
   (mapper 0 nil)
   (mirroring :horizontal nil)
   (initial-mirroring :horizontal nil)
   (battery-backed-p nil nil)
   (four-screen-p nil nil)
   (chr-writable-p nil nil)
   (prg-bank 0 nil)
   (chr-bank 0 nil)
   (mapper5-state nil nil)
   (mapper4-state nil nil)
   (mapper-state nil nil)
   (submapper 0 nil)
   (bus-conflict-p nil nil)
   (cpu-clock-required-p nil nil)
   (battery-dirty-p nil nil))
  :constructor %make-cartridge-instance)

(defmacro %define-cartridge-setter (name accessor)
  `(defun ,name (cartridge value)
     (setf (,accessor cartridge) value)))

(%define-cartridge-setter set-cartridge-prg-rom! cartridge-prg-rom)
(%define-cartridge-setter set-cartridge-chr-rom! cartridge-chr-rom)
(%define-cartridge-setter set-cartridge-prg-ram! cartridge-prg-ram)
(%define-cartridge-setter set-cartridge-mapper! cartridge-mapper)
(%define-cartridge-setter set-cartridge-mirroring! cartridge-mirroring)
(%define-cartridge-setter set-cartridge-initial-mirroring! cartridge-initial-mirroring)
(%define-cartridge-setter set-cartridge-battery-backed-p! cartridge-battery-backed-p)
(%define-cartridge-setter set-cartridge-four-screen-p! cartridge-four-screen-p)
(%define-cartridge-setter set-cartridge-chr-writable-p! cartridge-chr-writable-p)
(%define-cartridge-setter set-cartridge-prg-bank! cartridge-prg-bank)
(%define-cartridge-setter set-cartridge-chr-bank! cartridge-chr-bank)
(%define-cartridge-setter set-cartridge-mapper5-state! cartridge-mapper5-state)
(%define-cartridge-setter set-cartridge-mapper4-state! cartridge-mapper4-state)
(%define-cartridge-setter set-cartridge-mapper-state! cartridge-mapper-state)
(%define-cartridge-setter set-cartridge-submapper! cartridge-submapper)
(%define-cartridge-setter set-cartridge-bus-conflict-p! cartridge-bus-conflict-p)
(%define-cartridge-setter set-cartridge-cpu-clock-required-p! cartridge-cpu-clock-required-p)
(%define-cartridge-setter set-cartridge-battery-dirty-p! cartridge-battery-dirty-p)
