(in-package #:cl-nes)

(defmacro %with-mapper5-state ((state cartridge) &body body)
  `(let ((,state (cartridge-mapper5-state ,cartridge)))
     ,@body))

(defun %mapper5-write-control-register! (cartridge address value)
  (%with-mapper5-state (state cartridge)
    (cond
      ((= address #x5100)
       (setf (cartridge-mapper5-state-prg-mode state) (logand value 3)))
      ((= address #x5101)
       (setf (cartridge-mapper5-state-chr-mode state) (logand value 3)))
      ((= address #x5102)
       (setf (cartridge-mapper5-state-prg-ram-protect-1 state) value))
      ((= address #x5103)
       (setf (cartridge-mapper5-state-prg-ram-protect-2 state) value))
      ((= address #x5104)
       (setf (cartridge-mapper5-state-exram-mode state) (logand value 3)))
      ((= address #x5105)
       (setf (cartridge-mapper5-state-nametable-mapping state) value))
      ((= address #x5106)
       (setf (cartridge-mapper5-state-fill-tile state) value))
      ((= address #x5107)
       (setf (cartridge-mapper5-state-fill-attribute state) (logand value 3))))))

(defun %mapper5-write-prg-bank-register! (cartridge address value)
  (when (<= #x5113 address #x5117)
    (setf (aref (cartridge-mapper5-prg-banks cartridge)
                (- address #x5110))
          value)))

(defun %mapper5-write-chr-bank-register! (cartridge address value)
  (when (<= #x5120 address #x512B)
    (setf (aref (cartridge-mapper5-chr-banks cartridge)
                (- address #x5120))
          value)))

(defun %mapper5-write-irq-register! (cartridge address value)
  (%with-mapper5-state (state cartridge)
    (cond
      ((= address #x5200)
       (setf (cartridge-mapper5-state-split-control state) value))
      ((= address #x5201)
       (setf (cartridge-mapper5-state-split-scroll state) value))
      ((= address #x5202)
       (setf (cartridge-mapper5-state-split-bank state) value))
      ((= address #x5203)
       (setf (cartridge-mapper5-state-irq-scanline state) value))
      ((= address #x5204)
       (setf (cartridge-mapper5-state-irq-enabled-p state) (logbitp 7 value))
       (unless (logbitp 7 value)
         (setf (cartridge-mapper5-state-irq-pending-p state) nil)))
      ((= address #x5205)
       (setf (cartridge-mapper5-state-multiplier-a state) value))
      ((= address #x5206)
       (setf (cartridge-mapper5-state-multiplier-b state) value)))))

(defun %mapper5-write-exram! (cartridge address value)
  (%with-mapper5-state (state cartridge)
    (when (and (<= #x5C00 address #x5FFF)
               (/= (cartridge-mapper5-state-exram-mode state) 3))
      (setf (aref (cartridge-mapper5-state-exram state)
                  (mod (- address #x5C00) #x400))
            value))))

(defun %mapper5-multiplier-product (cartridge)
  (%with-mapper5-state (state cartridge)
    (* (cartridge-mapper5-state-multiplier-a state)
       (cartridge-mapper5-state-multiplier-b state))))

(defun %mapper5-read-status-register (cartridge)
  (%with-mapper5-state (state cartridge)
    (prog1 (logior (if (cartridge-mapper5-state-irq-pending-p state)
                       #x80
                       0)
                   (if (cartridge-mapper5-state-in-frame-p state)
                       #x40
                       0))
      (setf (cartridge-mapper5-state-irq-pending-p state) nil))))

(defun %mapper5-read-multiplier-low (cartridge)
  (ldb (byte 8 0) (%mapper5-multiplier-product cartridge)))

(defun %mapper5-read-multiplier-high (cartridge)
  (ldb (byte 8 8) (%mapper5-multiplier-product cartridge)))

(defun %mapper5-read-exram (cartridge address)
  (%with-mapper5-state (state cartridge)
    (when (and (<= #x5C00 address #x5FFF)
               (/= (cartridge-mapper5-state-exram-mode state) 3))
      (aref (cartridge-mapper5-state-exram state)
            (mod (- address #x5C00) #x400)))))

(defun %mapper5-write-expansion! (cartridge address value)
  (%mapper5-write-control-register! cartridge address value)
  (%mapper5-write-prg-bank-register! cartridge address value)
  (%mapper5-write-chr-bank-register! cartridge address value)
  (%mapper5-write-irq-register! cartridge address value)
  (%mapper5-write-exram! cartridge address value)
  value)

(defun cartridge-read-expansion (cartridge address)
  (when (= (cartridge-mapper cartridge) 5)
    (cond
      ((= address #x5204) (%mapper5-read-status-register cartridge))
      ((= address #x5205) (%mapper5-read-multiplier-low cartridge))
      ((= address #x5206) (%mapper5-read-multiplier-high cartridge))
      (t (%mapper5-read-exram cartridge address)))))

(defun cartridge-mmc5-read-chr-bank (cartridge bank address)
  "Read ADDRESS from a 4 KiB MMC5 CHR BANK."
  (when (and (= (cartridge-mapper cartridge) 5)
             (<= 0 address #x1FFF))
    (cartridge-clock-ppu-latch! cartridge address)
    (let* ((offset (+ (* bank +chr-bank-4k-size+)
                      (mod address +chr-bank-4k-size+)))
           (rom (cartridge-chr-rom cartridge)))
      (aref rom (mod offset (length rom))))))

(defun cartridge-mmc5-read-split-chr (cartridge address)
  "Read the 4 KiB CHR window selected by MMC5 $5202."
  (cartridge-mmc5-read-chr-bank
   cartridge (cartridge-mapper5-split-bank cartridge) address))

(defun cartridge-write-expansion! (cartridge address value)
  (when (= (cartridge-mapper cartridge) 5)
    (%mapper5-write-expansion! cartridge address value))
  value)

(defun cartridge-mmc5-nametable-location (cartridge address)
  (when (= (cartridge-mapper cartridge) 5)
    (let* ((offset (mod (- address #x2000) #x1000))
           (table (floor offset #x400))
           (within (mod offset #x400))
           (source (ldb (byte 2 (* table 2))
                        (cartridge-mapper5-nametable-mapping cartridge))))
      (values (case source
                (0 :ciram-0)
                (1 :ciram-1)
                (2 :exram)
                (otherwise :fill))
              within))))

(defun cartridge-mmc5-fill-value (cartridge within)
  (if (< within #x3C0)
      (cartridge-mapper5-fill-tile cartridge)
      (let ((attribute (cartridge-mapper5-fill-attribute cartridge)))
        (logior attribute
                (ash attribute 2)
                (ash attribute 4)
                (ash attribute 6)))))

(defun cartridge-clock-scanline! (cartridge scanline)
  (when (and cartridge (= (cartridge-mapper cartridge) 5))
    (%with-mapper5-state (state cartridge)
      (setf (cartridge-mapper5-state-in-frame-p state) (< scanline 240))
      (when (and (cartridge-mapper5-state-in-frame-p state)
                 (cartridge-mapper5-state-irq-enabled-p state)
                 (= scanline (cartridge-mapper5-state-irq-scanline state)))
        (setf (cartridge-mapper5-state-irq-pending-p state) t))))
  cartridge)
