(in-package #:cl-nes)

(defun %mapper4-prg-offset (cartridge address)
  (let* ((offset (- address #x8000))
         (slot (floor offset +prg-bank-8k-size+))
         (registers (cartridge-mapper4-registers cartridge))
         (bank-count (floor (length (cartridge-prg-rom cartridge))
                            +prg-bank-8k-size+))
         (last-bank (1- bank-count))
         (second-last-bank (max 0 (- last-bank 1)))
         (bank
           (if (zerop (logand (cartridge-mapper4-bank-select cartridge) #x40))
               (case slot
                 (0 (aref registers 6))
                 (1 (aref registers 7))
                 (2 second-last-bank)
                 (otherwise last-bank))
               (case slot
                 (0 second-last-bank)
                 (1 (aref registers 7))
                 (2 (aref registers 6))
                 (otherwise last-bank)))))
    (+ (* (mod bank bank-count) +prg-bank-8k-size+)
       (mod offset +prg-bank-8k-size+))))

(defun %mapper4-chr-offset (cartridge address)
  (let* ((slot (floor address +chr-bank-1k-size+))
         (registers (cartridge-mapper4-registers cartridge))
         (bank
           (if (zerop (logand (cartridge-mapper4-bank-select cartridge) #x80))
               (case slot
                 ((0 1) (+ (logand (aref registers 0) #xFE) slot))
                 ((2 3) (+ (logand (aref registers 1) #xFE)
                           (- slot 2)))
                 (4 (aref registers 2))
                 (5 (aref registers 3))
                 (6 (aref registers 4))
                 (otherwise (aref registers 5)))
               (case slot
                 (0 (aref registers 2))
                 (1 (aref registers 3))
                 (2 (aref registers 4))
                 (3 (aref registers 5))
                 ((4 5) (+ (logand (aref registers 0) #xFE)
                           (- slot 4)))
                 (otherwise (+ (logand (aref registers 1) #xFE)
                               (- slot 6)))))))
    (+ (* bank +chr-bank-1k-size+)
       (mod address +chr-bank-1k-size+))))
