(in-package #:cl-nes)

(defun %mapper9-prg-offset (cartridge address)
  (let* ((rom (cartridge-prg-rom cartridge))
         (bank-count (floor (length rom) +prg-bank-8k-size+))
         (offset (- address #x8000))
         (slot (floor offset +prg-bank-8k-size+))
         (bank (if (zerop slot)
                   (mod (cartridge-prg-bank cartridge) bank-count)
                   (+ (- bank-count 4) slot))))
    (+ (* bank +prg-bank-8k-size+)
       (mod offset +prg-bank-8k-size+))))

(defun %mapper10-prg-offset (cartridge address)
  (let* ((rom (cartridge-prg-rom cartridge))
         (bank-count (floor (length rom) +prg-bank-size+))
         (offset (- address #x8000))
         (bank (if (< offset +prg-bank-size+)
                   (mod (cartridge-prg-bank cartridge) bank-count)
                   (1- bank-count))))
    (+ (* bank +prg-bank-size+)
       (mod offset +prg-bank-size+))))

(defun %mapper9-10-chr-offset (cartridge address)
  (let* ((mode (cartridge-mapper-mode cartridge))
         (bank (if (< address #x1000)
                   (if (zerop (logand mode 1))
                       (cartridge-mapper-chr-bank-0 cartridge)
                       (cartridge-mapper-prg-bank-1 cartridge))
                   (if (zerop (logand mode 2))
                       (cartridge-mapper-chr-bank-1 cartridge)
                       (cartridge-mapper-register-select cartridge))))
         (bank-count (floor (length (cartridge-chr-rom cartridge))
                            +chr-bank-4k-size+)))
    (+ (* (mod bank bank-count) +chr-bank-4k-size+)
       (mod address +chr-bank-4k-size+))))

(defun cartridge-clock-ppu-latch! (cartridge address)
  (when (member (cartridge-mapper cartridge) '(9 10))
    (let ((address (logand address #x1FFF))
          (mode (cartridge-mapper-mode cartridge)))
      (cond
        ((<= #x0FD8 address #x0FDF)
         (setf (cartridge-mapper-mode cartridge) (logand mode #xFE)))
        ((<= #x0FE8 address #x0FEF)
         (setf (cartridge-mapper-mode cartridge) (logior mode 1)))
        ((<= #x1FD8 address #x1FDF)
         (setf (cartridge-mapper-mode cartridge) (logand mode #xFD)))
        ((<= #x1FE8 address #x1FEF)
         (setf (cartridge-mapper-mode cartridge) (logior mode 2)))))
  cartridge))

(defun %mapper9-10-write! (cartridge address value)
  (let ((value (logand value #xFF)))
    (cond
      ((<= #xA000 address #xAFFF)
       (set-cartridge-prg-bank! cartridge (logand value #x0F)))
      ((<= #xB000 address #xBFFF)
       (setf (cartridge-mapper-chr-bank-0 cartridge) (logand value #x1F)))
      ((<= #xC000 address #xCFFF)
       (setf (cartridge-mapper-prg-bank-1 cartridge) (logand value #x1F)))
      ((<= #xD000 address #xDFFF)
       (setf (cartridge-mapper-chr-bank-1 cartridge) (logand value #x1F)))
      ((<= #xE000 address #xEFFF)
       (setf (cartridge-mapper-register-select cartridge) (logand value #x1F)))
      ((<= #xF000 address #xFFFF)
       (set-cartridge-mirroring!
        cartridge
        (if (zerop (logand value 1)) :vertical :horizontal))))
  value))
