(in-package #:cl-nes/test)

(describe "CPU arithmetic flag transitions"
  (it "propagates arithmetic and rotate flag transitions"
    (labels ((run (program a status)
               (with-fixture-cpu-state (cpu bus
                                        :program program
                                        :a a
                                        :p status)
                 (expect (cpu-step! cpu bus) :to-be 2)
                 cpu)))
      (let ((cpu (run '(#x69 #x01) #x7F 0)))
        (expect (cpu-a cpu) :to-be #x80)
        (expect (logand (cpu-p cpu) cl-nes::+flag-overflow+)
                :to-be cl-nes::+flag-overflow+)
        (expect (logand (cpu-p cpu) cl-nes::+flag-negative+)
                :to-be cl-nes::+flag-negative+)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0))
      (let ((cpu (run '(#x69 #x01) #xFF cl-nes::+flag-carry+)))
        (expect (cpu-a cpu) :to-be 1)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
                :to-be cl-nes::+flag-carry+))
      (let ((cpu (run '(#x2A) #x80 cl-nes::+flag-carry+)))
        (expect (cpu-a cpu) :to-be 1)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
                :to-be cl-nes::+flag-carry+))
      (let ((cpu (run '(#x2A) 0 0)))
        (expect (cpu-a cpu) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
                :to-be cl-nes::+flag-zero+))
      (let ((cpu (run '(#x6A) 1 cl-nes::+flag-carry+)))
        (expect (cpu-a cpu) :to-be #x80)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
                :to-be cl-nes::+flag-carry+))
      (let ((cpu (run '(#x6A) 0 0)))
        (expect (cpu-a cpu) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
                :to-be cl-nes::+flag-zero+)))))
