(in-package #:cl-nes/test)

(describe "CPU opcode dispatch reachability (00-1F)"
  (define-opcode-dispatch-reachability-spec
      "reaches opcode #x~2,'0X through the unified dispatch"
    ((#x00)
     (#x01)
     (#x03)
     (#x04)
     (#x05)
     (#x06)
     (#x07)
     (#x08)
     (#x09)
     (#x0A)
     (#x0B)
     (#x0C)
     (#x0D)
     (#x0E)
     (#x0F)
     (#x10)
     (#x11)
     (#x13)
     (#x14)
     (#x15)
     (#x16)
     (#x17)
     (#x18)
     (#x19)
     (#x1A)
     (#x1B)
     (#x1C)
     (#x1D)
     (#x1E)
     (#x1F))))
