(in-package #:cl-nes/test)

(describe "CPU opcode dispatch (A0-BF)"
  (define-opcode-dispatch-spec
      "dispatches opcode #x~2,'0X in ~D cycles"
    ((#xA0 2)
     (#xA1 6)
     (#xA2 2)
     (#xA3 6)
     (#xA4 3)
     (#xA5 3)
     (#xA6 3)
     (#xA7 3)
     (#xA8 2)
     (#xA9 2)
     (#xAA 2)
     (#xAB 2)
     (#xAC 4)
     (#xAD 4)
     (#xAE 4)
     (#xAF 4)
     (#xB0 2)
     (#xB1 5)
     (#xB3 5)
     (#xB4 4)
     (#xB5 4)
     (#xB6 4)
     (#xB7 4)
     (#xB8 2)
     (#xB9 4)
     (#xBA 2)
     (#xBC 4)
     (#xBD 4)
     (#xBE 4)
     (#xBF 4))))
