(in-package #:cl-nes/test)

(describe "CPU opcode dispatch (E0-FF)"
  (define-opcode-dispatch-spec
      "dispatches opcode #x~2,'0X in ~D cycles"
    ((#xE0 2)
     (#xE1 6)
     (#xE2 2)
     (#xE3 8)
     (#xE4 3)
     (#xE5 3)
     (#xE6 5)
     (#xE7 5)
     (#xE8 2)
     (#xE9 2)
     (#xEA 2)
     (#xEB 2)
     (#xEC 4)
     (#xED 4)
     (#xEE 6)
     (#xEF 6)
     (#xF0 2)
     (#xF1 5)
     (#xF3 8)
     (#xF4 4)
     (#xF5 4)
     (#xF6 6)
     (#xF7 6)
     (#xF8 2)
     (#xF9 4)
     (#xFA 2)
     (#xFB 7)
     (#xFC 4)
     (#xFD 4)
     (#xFE 7)
     (#xFF 7))))
