(in-package #:cl-nes/test)

(describe "Bus state transitions"
  (it "routes CPU windows to PPU, APU, controllers, and cartridge memory"
    (let* ((cartridge (make-fixture-cartridge :program '(#xEA)))
           (ppu (make-ppu cartridge))
           (apu (make-apu))
           (controller-1 (make-controller))
           (controller-2 (make-controller))
           (bus (make-bus :cartridge cartridge
                          :ppu ppu
                          :apu apu
                          :controller-1 controller-1
                          :controller-2 controller-2)))
      (setf (ppu-status ppu) #xE0)
      (expect (bus-read bus #x2002) :to-be #xE0)
      (bus-write! bus #x2001 #x18)
      (expect (ppu-mask ppu) :to-be #x18)
      (setf (cl-nes::apu-frame-irq-pending-p apu) t)
      (expect (bus-read bus #x4015) :to-be #x40)
      (controller-set-buttons! controller-1 cl-nes::+button-a+)
      (controller-set-buttons! controller-2 cl-nes::+button-a+)
      (bus-write! bus #x4016 1)
      (expect (bus-read bus #x4016) :to-be 1)
      (expect (bus-read bus #x4017) :to-be 1)
      (expect (bus-write! bus #x4000 #xFF) :to-be #xFF)
      (expect (bus-write! bus #x4015 0) :to-be 0)
      (expect (bus-write! bus #x5000 #x33) :to-be #x33)
      (expect (bus-read bus #x5000) :to-be #x33)
      (bus-write! bus #x6000 #xB6)
      (expect (bus-read bus #x6000) :to-be #xB6)
      (expect (bus-read bus #x8000) :to-be #xEA)))

  (it "routes mapper expansion and NROM-368 windows"
    (with-mmc5-cartridge (mapper5)
      (let ((expansion-bus (make-bus :cartridge mapper5)))
        (bus-write! expansion-bus #x5C00 #xA7)
        (expect (bus-read expansion-bus #x5C00) :to-be #xA7)))
    (let* ((prg (make-array (* 48 1024)
                            :element-type '(unsigned-byte 8)
                            :initial-element 0))
           (cartridge (make-cartridge :prg-rom prg))
           (bus (make-bus :cartridge cartridge)))
      (setf (aref (cartridge-prg-rom cartridge) #x0800) #xC3)
      (expect (bus-read bus #x4800) :to-be #xC3)
      (bus-write! bus #x6000 #xD4)
      (expect (aref (cartridge-prg-ram cartridge) 0) :to-be 0)))

  (it "mirrors internal RAM and retains the open-bus value"
    (let ((bus (make-bus :cartridge (make-fixture-cartridge))))
      (bus-write! bus #x0000 #xA5)
      (expect (bus-read bus #x0800) :to-be #xA5)
      (bus-write! bus #x4018 #x5A)
      (expect (bus-read bus #x4018) :to-be #x5A)))
  (it "transfers a page through OAM DMA and consumes its stall once"
    (let ((bus (make-bus :cartridge (make-fixture-cartridge))))
      (dotimes (offset 256)
        (bus-write! bus offset offset))
      (bus-write! bus #x2003 0)
      (bus-write! bus #x4014 0)
      (expect (aref (ppu-oam (cl-nes::bus-ppu bus)) 0) :to-be 0)
      (expect (aref (ppu-oam (cl-nes::bus-ppu bus)) #xFF) :to-be #xFF)
      (expect (ppu-oam-address (cl-nes::bus-ppu bus)) :to-be 0)
      (expect (cl-nes::bus-take-dma-stall-cycles! bus) :to-be 513)
      (expect (cl-nes::bus-take-dma-stall-cycles! bus) :to-be 0))))
