(in-package #:cl-nes/test)

(describe "MMC3 control contracts"
  (it "controls mirroring, PRG-RAM, and A12 IRQ filtering"
    (with-mmc3-cartridge (cartridge)
      (cartridge-write-prg! cartridge #xA000 0)
      (expect (cartridge-mirroring cartridge) :to-be :vertical)
      (cartridge-write-prg! cartridge #xA000 1)
      (expect (cartridge-mirroring cartridge) :to-be :horizontal)
      (cartridge-write-prg-ram! cartridge #x6000 #xA5)
      (expect (cartridge-read-prg-ram cartridge #x6000) :to-be #xA5)
      (cartridge-write-prg! cartridge #xA001 0)
      (cartridge-write-prg-ram! cartridge #x6000 #x5A)
      (expect (cartridge-read-prg-ram cartridge #x6000) :to-be nil)
      (cartridge-write-prg! cartridge #xA001 #x80)
      (cartridge-write-prg-ram! cartridge #x6000 #x5A)
      (expect (cartridge-read-prg-ram cartridge #x6000) :to-be #x5A)
      (cartridge-write-prg! cartridge #xA001 #xC0)
      (cartridge-write-prg-ram! cartridge #x6000 #xA5)
      (expect (cartridge-read-prg-ram cartridge #x6000) :to-be #x5A)
      (let ((four-screen (make-patterned-cartridge :mapper 4 :prg-banks 8 :chr-banks 8 :four-screen-p t)))
        (cartridge-write-prg! four-screen #xA000 0)
        (expect (cartridge-mirroring four-screen) :to-be :horizontal))
      (cartridge-write-prg! cartridge #xC000 1)
      (cartridge-write-prg! cartridge #xE001 0)
      (cl-nes::cartridge-clock-ppu-a12! cartridge nil 23)
      (cl-nes::cartridge-clock-ppu-a12! cartridge t)
      (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
      (cl-nes::cartridge-clock-ppu-a12! cartridge nil 1)
      (cl-nes::cartridge-clock-ppu-a12! cartridge t)
      (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
      (cl-nes::cartridge-clock-ppu-a12! cartridge nil 24)
      (cl-nes::cartridge-clock-ppu-a12! cartridge t)
      (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
      (cartridge-write-prg! cartridge #xE000 0)
      (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
      (cartridge-write-prg! cartridge #xE001 0)
      (cartridge-write-prg! cartridge #xC001 0)
      (cl-nes::cartridge-clock-ppu-a12! cartridge nil 24)
      (cl-nes::cartridge-clock-ppu-a12! cartridge t)
      (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
      (cl-nes::cartridge-clock-ppu-a12! cartridge nil 24)
      (cl-nes::cartridge-clock-ppu-a12! cartridge t)
      (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be t)))
  (it "distinguishes MMC6 zero-counter reload behavior"
    (with-mmc3-cartridge (cartridge :mapper4-variant :mmc6)
      (cartridge-write-prg! cartridge #xC000 0)
      (cartridge-write-prg! cartridge #xE001 0)
      (cl-nes::cartridge-clock-ppu-a12! cartridge nil 24)
      (cl-nes::cartridge-clock-ppu-a12! cartridge t)
      (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
      (cartridge-write-prg! cartridge #xC001 0)
      (cl-nes::cartridge-clock-ppu-a12! cartridge nil 24)
      (cl-nes::cartridge-clock-ppu-a12! cartridge t)
      (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be t))))
