(in-package #:cl-nes/test)

(describe "Coverage: cartridge memory and mapper contracts"
  (it "covers MMC1 PRG modes and CHR banking"
    (with-patterned-cartridge (cartridge :mapper 1 :prg-banks 8 :chr-banks 32)
      (serial-write-mmc1-register cartridge #x8000 0)
      (serial-write-mmc1-register cartridge #xE000 3)
      (expect (cartridge-read-prg cartridge #x8000) :to-be 4)
      (expect (cartridge-read-prg cartridge #xC000) :to-be 6)
      (serial-write-mmc1-register cartridge #x8000 8)
      (expect (cartridge-read-prg cartridge #x8000) :to-be 0)
      (expect (cartridge-read-prg cartridge #xC000) :to-be 6)
      (serial-write-mmc1-register cartridge #x8000 12)
      (serial-write-mmc1-register cartridge #xE000 1)
      (expect (cartridge-read-prg cartridge #x8000) :to-be 2)
      (expect (cartridge-read-prg cartridge #xC000) :to-be 6)
      (serial-write-mmc1-register cartridge #xA000 2)
      (serial-write-mmc1-register cartridge #xC000 3)
      (expect (cartridge-read-chr cartridge 0) :to-be 16)
      (expect (cartridge-read-chr cartridge #x1000) :to-be 20)
      (serial-write-mmc1-register cartridge #x8000 0)
      (serial-write-mmc1-register cartridge #xA000 2)
      (expect (cartridge-read-chr cartridge 0) :to-be 16)
      (cartridge-write-prg! cartridge #x8000 #x80)
      (expect (cl-nes::cartridge-mapper-shift cartridge) :to-be #x10)
      (serial-write-mmc1-register cartridge #x8000 1)
      (expect (cartridge-mirroring cartridge) :to-be :single-screen-upper)
      (serial-write-mmc1-register cartridge #x8000 #x10)
      (serial-write-mmc1-register cartridge #xA000 1)
      (serial-write-mmc1-register cartridge #xC000 2)
      (expect (cartridge-read-chr cartridge 0) :to-be 4)
      (expect (cartridge-read-chr cartridge #x1000) :to-be 8))))
