(in-package #:cl-nes/test)

(describe "Coverage: CPU flag contracts"
  (it "covers BIT and shift flag transitions"
    (let ((cpu (make-cpu)))
      (setf (cpu-a cpu) #xFF)
      (cl-nes::%bit! cpu #xC0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-overflow+)
              :to-be cl-nes::+flag-overflow+)
      (expect (logand (cpu-p cpu) cl-nes::+flag-negative+)
              :to-be cl-nes::+flag-negative+)
      (setf (cpu-a cpu) 0)
      (cl-nes::%bit! cpu 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
              :to-be cl-nes::+flag-zero+)
      (expect (logand (cpu-p cpu) cl-nes::+flag-overflow+) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-negative+) :to-be 0)
      (expect (cl-nes::%asl-value! cpu #x80) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
              :to-be cl-nes::+flag-carry+)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
              :to-be cl-nes::+flag-zero+)
      (expect (cl-nes::%asl-value! cpu 1) :to-be 2)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+) :to-be 0)
      (expect (cl-nes::%lsr-value! cpu 1) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
              :to-be cl-nes::+flag-carry+)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
              :to-be cl-nes::+flag-zero+)
      (expect (cl-nes::%lsr-value! cpu 2) :to-be 1)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
      (setf (cpu-p cpu) cl-nes::+flag-carry+)
      (expect (cl-nes::%rol-value! cpu #x80) :to-be 1)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
              :to-be cl-nes::+flag-carry+)
      (setf (cpu-p cpu) 0)
      (expect (cl-nes::%rol-value! cpu 0) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
              :to-be cl-nes::+flag-zero+)
      (setf (cpu-p cpu) cl-nes::+flag-carry+)
      (expect (cl-nes::%ror-value! cpu 1) :to-be #x80)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
              :to-be cl-nes::+flag-carry+)
      (setf (cpu-p cpu) 0)
      (expect (cl-nes::%ror-value! cpu 2) :to-be 1)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0))))
