(in-package #:cl-nes/test)

(describe "Coverage: CPU and PPU contracts"
  (it "delays IRQ after enabling interrupts"
      (let* ((bus (make-bus :cartridge
                            (make-fixture-cartridge :program '(#x78))))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (expect (cpu-interrupt! cpu bus :reset) :to-be nil)
      (setf (cpu-p cpu) 0
            (cl-nes::cpu-irq-delay cpu) 0)
      (expect (cpu-step! cpu bus) :to-be 2)
      (expect (logand (cpu-p cpu) cl-nes::+flag-interrupt-disable+)
              :to-be cl-nes::+flag-interrupt-disable+)
      (expect (cl-nes::cpu-irq-delay cpu) :to-be 1)))

  (it "switches nametable storage and distinguishes buffered palette reads"
    (let* ((ppu (make-ppu))
           (four (make-patterned-cartridge
                  :mapper 0 :prg-banks 2 :chr-banks 8 :four-screen-p t))
           (normal (make-patterned-cartridge
                    :mapper 0 :prg-banks 2 :chr-banks 8)))
      (ppu-load-cartridge! ppu four)
      (expect (length (cl-nes::ppu-nametable ppu)) :to-be #x1000)
      (ppu-load-cartridge! ppu four)
      (expect (length (cl-nes::ppu-nametable ppu)) :to-be #x1000)
      (ppu-load-cartridge! ppu normal)
      (expect (length (cl-nes::ppu-nametable ppu)) :to-be #x800)
      (ppu-load-cartridge! ppu normal)
      (expect (length (cl-nes::ppu-nametable ppu)) :to-be #x800)
      (ppu-write-vram! ppu #x2000 #xA5)
      (expect (ppu-read-vram ppu #x3000) :to-be #xA5)
      (ppu-write-vram! ppu #x3F00 #x3C)
      (ppu-write-register! ppu 6 #x3F)
      (ppu-write-register! ppu 6 0)
      (expect (ppu-read-register ppu 7) :to-be #x3C)
      (setf (ppu-status ppu) #x80
            (ppu-control ppu) 0
            (ppu-nmi-pending-p ppu) nil
            (cl-nes::ppu-nmi-delay-p ppu) nil)
      (ppu-write-register! ppu 0 #x80)
      (expect (ppu-nmi-pending-p ppu) :to-be t)
      (expect (ppu-take-nmi! ppu) :to-be nil)
      (expect (ppu-take-nmi! ppu) :to-be t)
      (setf (ppu-nmi-pending-p ppu) t
            (cl-nes::ppu-nmi-delay-p ppu) t)
      (cl-nes::%request-nmi! ppu)
      (setf (ppu-oam-address ppu) #x12
            (aref (ppu-oam ppu) #x12) #xA6)
      (expect (ppu-read-register ppu 4) :to-be #xA6)
      (expect (ppu-read-register ppu 1) :to-be 0)
      (ppu-read-register ppu 2)
      (expect (ppu-nmi-pending-p ppu) :to-be nil)
      (expect (cl-nes::ppu-nmi-delay-p ppu) :to-be nil)))

  (it "covers rendering gates and pattern fetch phases"
    (let ((ppu (make-ppu (make-fixture-cartridge))))
      (setf (ppu-mask ppu) 0
            (cl-nes::ppu-scanline ppu) 0)
      (expect (cl-nes::%ppu-rendering-scanline-p ppu) :to-be nil)
      (setf (ppu-mask ppu) #x08)
      (expect (cl-nes::%ppu-rendering-scanline-p ppu) :to-be t)
      (setf (cl-nes::ppu-scanline ppu) 240)
      (expect (cl-nes::%ppu-rendering-scanline-p ppu) :to-be nil)
      (setf (cl-nes::ppu-scanline ppu) 261)
      (expect (cl-nes::%ppu-rendering-scanline-p ppu) :to-be t)
      (setf (ppu-control ppu) 0
            (cl-nes::ppu-dot ppu) 10)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be nil)
      (setf (ppu-control ppu) #x10)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be t)
      (setf (cl-nes::ppu-dot ppu) 14)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be nil)
      (setf (cl-nes::ppu-dot ppu) 330)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be t)
      (setf (cl-nes::ppu-dot ppu) 334)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be nil)
      (setf (ppu-control ppu) #x08
            (cl-nes::ppu-dot ppu) 266)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be t)
      (setf (cl-nes::ppu-dot ppu) 270)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be nil)
      (cl-nes::%ppu-clock-render-a12! (make-ppu) t)
      (let ((background-ppu (make-ppu (make-fixture-cartridge))))
        (ppu-write-register! background-ppu 1 0)
        (multiple-value-bind (color present)
            (cl-nes::%background-pixel background-ppu 0 0)
          (expect color :to-be 0)
          (expect present :to-be nil))
        (ppu-write-register! background-ppu 1 #x02)
        (multiple-value-bind (color present)
            (cl-nes::%background-pixel background-ppu 0 0)
          (expect color :to-be 0)
          (expect present :to-be nil))
        (ppu-write-register! background-ppu 1 #x06)
        (multiple-value-bind (color present)
            (cl-nes::%background-pixel background-ppu 0 0)
          (expect color :to-be 0)
          (expect present :to-be nil)))
      (let ((sprite-ppu (make-ppu (make-fixture-cartridge))))
        (ppu-write-register! sprite-ppu 1 #x10)
        (ppu-write-vram! sprite-ppu #x0000 #x80)
        (ppu-write-vram! sprite-ppu #x3F11 #x21)
        (setf (aref (ppu-oam sprite-ppu) 0) 0
              (aref (ppu-oam sprite-ppu) 1) 0
              (aref (ppu-oam sprite-ppu) 2) 0
              (aref (ppu-oam sprite-ppu) 3) 8
              (ppu-control sprite-ppu) 0)
        (multiple-value-bind (color present behind)
            (cl-nes::%sprite-pixel sprite-ppu 0 8 1)
          (expect color :to-be #x21)
          (expect present :to-be t)
          (expect behind :to-be nil))
        (multiple-value-bind (color present behind)
            (cl-nes::%sprite-pixel sprite-ppu 0 0 1)
          (expect color :to-be nil)
          (expect present :to-be nil)
          (expect behind :to-be nil))
        (multiple-value-bind (color present behind)
            (cl-nes::%sprite-pixel sprite-ppu 0 8 0)
          (expect color :to-be nil)
          (expect present :to-be nil)
          (expect behind :to-be nil))
        (multiple-value-bind (color present behind)
            (cl-nes::%sprite-pixel sprite-ppu 0 16 1)
          (expect color :to-be nil)
          (expect present :to-be nil)
          (expect behind :to-be nil))
        (setf (aref (ppu-oam sprite-ppu) 3) 0)
        (multiple-value-bind (color present behind)
            (cl-nes::%sprite-pixel sprite-ppu 0 0 1)
          (expect color :to-be #x21)
          (expect present :to-be t)
          (expect behind :to-be nil))
        (setf (ppu-mask sprite-ppu) 0)
        (multiple-value-bind (color present behind)
            (cl-nes::%sprite-pixel sprite-ppu 0 0 1)
          (expect color :to-be nil)
          (expect present :to-be nil)
          (expect behind :to-be nil))
        (setf (aref (ppu-oam sprite-ppu) 3) 8
              (ppu-mask sprite-ppu) #x10)
        (let ((background-opaque
                (make-array (* cl-nes::+ppu-width+ cl-nes::+ppu-height+)
                            :element-type 'bit
                            :initial-element 0))
              (occupied
                (make-array (* cl-nes::+ppu-width+ cl-nes::+ppu-height+)
                            :element-type 'bit
                            :initial-element 0)))
          (cl-nes::%draw-sprite-pixel!
           sprite-ppu 1 0 1 background-opaque occupied)
          (expect (aref occupied cl-nes::+ppu-width+) :to-be 1))
        (ppu-write-vram! sprite-ppu #x1000 #x80)
        (setf (ppu-control sprite-ppu) #x08)
        (multiple-value-bind (color present behind)
            (cl-nes::%sprite-pixel sprite-ppu 0 8 1)
          (expect color :to-be #x21)
          (expect present :to-be t)
          (expect behind :to-be nil)))))

  (it "covers the even-frame wrap"
    (let ((ppu (make-ppu)))
      (setf (cl-nes::ppu-scanline ppu) 261
            (cl-nes::ppu-dot ppu) 340
            (cl-nes::ppu-odd-frame-p ppu) nil)
      (ppu-tick! ppu)
      (expect (cl-nes::ppu-scanline ppu) :to-be 0)
      (expect (cl-nes::ppu-dot ppu) :to-be 0)
      (expect (cl-nes::ppu-odd-frame-p ppu) :to-be t))))
