(in-package #:cl-nes/test)

(describe "Coverage: PPU rendering phases"
  (it "covers rendering gates and pattern fetch phases"
    (with-fixture-ppu (ppu)
      (setf (ppu-mask ppu) 0
            (cl-nes::ppu-scanline ppu) 0)
      (expect (cl-nes::%ppu-rendering-scanline-p ppu) :to-be nil)
      (setf (ppu-mask ppu) #x08)
      (expect (cl-nes::%ppu-rendering-scanline-p ppu) :to-be t)
      (setf (cl-nes::ppu-scanline ppu) 240)
      (expect (cl-nes::%ppu-rendering-scanline-p ppu) :to-be nil)
      (setf (cl-nes::ppu-scanline ppu) 261)
      (expect (cl-nes::%ppu-rendering-scanline-p ppu) :to-be t)
      (setf (ppu-control ppu) 0
            (cl-nes::ppu-dot ppu) 10)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be nil)
      (setf (ppu-control ppu) #x10)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be t)
      (setf (cl-nes::ppu-dot ppu) 14)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be nil)
      (setf (cl-nes::ppu-dot ppu) 330)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be t)
      (setf (cl-nes::ppu-dot ppu) 334)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be nil)
      (setf (ppu-control ppu) #x08
            (cl-nes::ppu-dot ppu) 266)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be t)
      (setf (cl-nes::ppu-dot ppu) 270)
      (expect (cl-nes::%ppu-a12-high-p ppu) :to-be nil)
      (cl-nes::%ppu-clock-render-a12! (make-ppu) t)
      (with-fixture-ppu (background-ppu)
        (ppu-write-register! background-ppu 1 0)
        (expect-background-pixel (background-ppu 0 0) 0 nil)
        (ppu-write-register! background-ppu 1 #x02)
        (expect-background-pixel (background-ppu 0 0) 0 nil)
        (ppu-write-register! background-ppu 1 #x06)
        (expect-background-pixel (background-ppu 0 0) 0 nil))
      (with-fixture-ppu (sprite-ppu)
        (ppu-write-register! sprite-ppu 1 #x10)
        (write-vram-values sprite-ppu
          (#x0000 #x80)
          (#x3F11 #x21))
        (write-oam-values sprite-ppu
          (0 0)
          (1 0)
          (2 0)
          (3 8))
        (setf (ppu-control sprite-ppu) 0)
        (expect-sprite-pixel (sprite-ppu 0 8 1) #x21 t nil)
        (expect-sprite-pixel (sprite-ppu 0 0 1) nil nil nil)
        (expect-sprite-pixel (sprite-ppu 0 8 0) nil nil nil)
        (expect-sprite-pixel (sprite-ppu 0 16 1) nil nil nil)
        (write-oam-values sprite-ppu
          (3 0))
        (expect-sprite-pixel (sprite-ppu 0 0 1) #x21 t nil)
        (setf (ppu-mask sprite-ppu) 0)
        (expect-sprite-pixel (sprite-ppu 0 0 1) nil nil nil)
        (write-oam-values sprite-ppu
          (3 8))
        (setf (ppu-mask sprite-ppu) #x10)
        (with-screen-bits (background-opaque occupied)
          (cl-nes::%draw-sprite-pixel!
           sprite-ppu 1 0 1 background-opaque occupied)
          (expect (aref occupied cl-nes::+ppu-width+) :to-be 1))
        (ppu-write-vram! sprite-ppu #x1000 #x80)
        (setf (ppu-control sprite-ppu) #x08)
        (expect-sprite-pixel (sprite-ppu 0 8 1) #x21 t nil)))))
