(in-package #:cl-nes/test)

(describe "Coverage: mapper contracts"
  (it "resets MMC1 shift state and forces safe mirroring"
    (let ((cartridge (make-contract-cartridge 1)))
      (cartridge-write-prg! cartridge #x8000 #x80)
      (expect (cl-nes::cartridge-mapper-shift cartridge) :to-be #x10)
      (expect (cl-nes::cartridge-mapper-control cartridge) :to-be #x0C)
      (expect (cartridge-mirroring cartridge) :to-be :single-screen-lower)))

  (it "selects MMC1 mirroring and 8 KiB CHR mode"
    (let ((cartridge (make-patterned-cartridge
                      :mapper 1 :prg-banks 4 :chr-banks 32)))
      (labels ((serial-write (address value)
                 (dotimes (bit 5)
                   (cartridge-write-prg!
                    cartridge address (ldb (byte 1 bit) value)))))
        (serial-write #x8000 2)
        (expect (cartridge-mirroring cartridge) :to-be :vertical)
        (serial-write #x8000 3)
        (expect (cartridge-mirroring cartridge) :to-be :horizontal)
        (serial-write #x8000 0)
        (serial-write #xA000 2)
        (expect (cartridge-read-chr cartridge 0) :to-be 16)
        (serial-write #xC000 1)
        (expect (cl-nes::cartridge-mapper-chr-bank-1 cartridge) :to-be 1))))

  (it "updates mapper 28 mirroring and bank registers"
    (let ((cartridge (make-patterned-cartridge
                      :mapper 28 :prg-banks 4 :chr-banks 16)))
      (labels ((write-register (register value)
                 (cartridge-write-prg! cartridge #x5000 register)
                 (cartridge-write-prg! cartridge #x8000 value)))
        (write-register #x80 2)
        (expect (cartridge-mirroring cartridge) :to-be :vertical)
        (write-register #x80 3)
        (expect (cartridge-mirroring cartridge) :to-be :horizontal)
        (write-register #x80 0)
        (write-register #x00 #x10)
        (expect (cartridge-mirroring cartridge) :to-be :single-screen-upper)
        (write-register #x01 0)
        (expect (cartridge-mirroring cartridge) :to-be :single-screen-lower)
        (write-register #x80 3)
        (write-register #x00 #x10)
        (expect (cartridge-mirroring cartridge) :to-be :horizontal)
        (write-register #x81 #x2A)
        (expect (cl-nes::cartridge-mapper-outer-bank cartridge) :to-be #x2A))))

  (it "does not retrigger MMC3 on a high-to-high A12 sample"
    (let ((cartridge (make-patterned-cartridge
                      :mapper 4 :prg-banks 8 :chr-banks 8)))
      (cartridge-write-prg! cartridge #xC000 0)
      (cartridge-write-prg! cartridge #xE001 0)
      (cl-nes::cartridge-clock-ppu-a12! cartridge nil 24)
      (cl-nes::cartridge-clock-ppu-a12! cartridge t)
      (setf (cl-nes::cartridge-mapper4-irq-pending-p cartridge) nil)
      (cl-nes::cartridge-clock-ppu-a12! cartridge t)
      (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)))

  (it "delays IRQ after status changes and rotates ARR with carry"
    (let ((cpu (make-cpu)))
      (setf (cpu-p cpu) cl-nes::+flag-interrupt-disable+
            (cl-nes::cpu-irq-delay cpu) 0)
      (cl-nes::%restore-status! cpu 0)
      (expect (cl-nes::cpu-irq-delay cpu) :to-be 1)
      (setf (cl-nes::cpu-irq-delay cpu) 0
            (cpu-p cpu) cl-nes::+flag-interrupt-disable+)
      (cl-nes::%restore-status! cpu cl-nes::+flag-interrupt-disable+)
      (expect (cl-nes::cpu-irq-delay cpu) :to-be 0)
      (setf (cpu-a cpu) #xFF
            (cpu-p cpu) 0)
      (expect (cl-nes::%arr! cpu #xFF) :to-be #x7F)
      (setf (cpu-a cpu) #xFF
            (cpu-p cpu) cl-nes::+flag-carry+)
      (expect (cl-nes::%arr! cpu #xFF) :to-be #xFF)
      (setf (cpu-a cpu) #xFF
            (cpu-p cpu) 0)
      (expect (cl-nes::%arr! cpu #x80) :to-be #x40)
      (expect (logand (cpu-p cpu) cl-nes::+flag-overflow+)
              :to-be cl-nes::+flag-overflow+)
      (setf (cpu-a cpu) #xFF
            (cpu-p cpu) 0)
      (expect (cl-nes::%aac! cpu #x80) :to-be #x80)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
              :to-be cl-nes::+flag-carry+)
      (setf (cpu-a cpu) #xFF
            (cpu-p cpu) 0)
      (expect (cl-nes::%aac! cpu 0) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)))

  (it "covers BIT and shift flag transitions"
    (let ((cpu (make-cpu)))
      (setf (cpu-a cpu) #xFF)
      (cl-nes::%bit! cpu #xC0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-overflow+)
              :to-be cl-nes::+flag-overflow+)
      (expect (logand (cpu-p cpu) cl-nes::+flag-negative+)
              :to-be cl-nes::+flag-negative+)
      (setf (cpu-a cpu) 0)
      (cl-nes::%bit! cpu 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
              :to-be cl-nes::+flag-zero+)
      (expect (logand (cpu-p cpu) cl-nes::+flag-overflow+) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-negative+) :to-be 0)
      (expect (cl-nes::%asl-value! cpu #x80) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
              :to-be cl-nes::+flag-carry+)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
              :to-be cl-nes::+flag-zero+)
      (expect (cl-nes::%asl-value! cpu 1) :to-be 2)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+) :to-be 0)
      (expect (cl-nes::%lsr-value! cpu 1) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
              :to-be cl-nes::+flag-carry+)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
              :to-be cl-nes::+flag-zero+)
      (expect (cl-nes::%lsr-value! cpu 2) :to-be 1)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
      (setf (cpu-p cpu) cl-nes::+flag-carry+)
      (expect (cl-nes::%rol-value! cpu #x80) :to-be 1)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
              :to-be cl-nes::+flag-carry+)
      (setf (cpu-p cpu) 0)
      (expect (cl-nes::%rol-value! cpu 0) :to-be 0)
      (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
              :to-be cl-nes::+flag-zero+)
      (setf (cpu-p cpu) cl-nes::+flag-carry+)
      (expect (cl-nes::%ror-value! cpu 1) :to-be #x80)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
              :to-be cl-nes::+flag-carry+)
      (setf (cpu-p cpu) 0)
      (expect (cl-nes::%ror-value! cpu 2) :to-be 1)
      (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0))))
