(in-package #:cl-nes/test)

(defun set-fixture-vector! (cartridge address target)
  (let ((rom (cartridge-prg-rom cartridge)))
    (setf (aref rom (- address #x8000))
          (ldb (byte 8 0) target)
          (aref rom (1+ (- address #x8000)))
          (ldb (byte 8 8) target)))
  cartridge)

(describe "CPU state transitions"
  (it "does not advance a stopped CPU"
    (let* ((bus (make-bus :cartridge (make-fixture-cartridge)))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (setf (cpu-stopped-p cpu) t)
      (let ((before-pc (cpu-pc cpu))
            (before-cycles (cpu-cycles cpu)))
        (expect (cpu-step! cpu bus) :to-be 0)
        (expect (cpu-pc cpu) :to-be before-pc)
        (expect (cpu-cycles cpu) :to-be before-cycles))))
  (it-each ((#x10 #x24 #x8000 #x10 #x8012 3)
            (#x30 #xA4 #x8000 #x30 #x8032 3)
            (#x50 #x24 #x8000 #x50 #x8052 3)
            (#x70 #x64 #x8000 #x70 #x8072 3)
            (#x90 #x24 #x8000 #x10 #x8012 3)
            (#xB0 #x25 #x8000 #x30 #x8032 3)
            (#xD0 #x24 #x8000 #x50 #x8052 3)
            (#xF0 #x26 #x8000 #x70 #x8072 3)
            (#x10 #xA4 #x8000 #x10 #x8002 2)
            (#x30 #x24 #x8000 #x30 #x8002 2)
            (#x50 #x64 #x8000 #x50 #x8002 2)
            (#x70 #x24 #x8000 #x70 #x8002 2)
            (#x90 #x25 #x8000 #x90 #x8002 2)
            (#xB0 #x24 #x8000 #xB0 #x8002 2)
            (#xD0 #x26 #x8000 #xD0 #x8002 2)
            (#xF0 #x24 #x8000 #xF0 #x8002 2)
            (#x10 #x24 #x80F0 #x10 #x8102 4)
            (#x10 #x24 #x8100 #xF0 #x80F2 4))
      "applies branch flags and page-crossing cycle penalties"
      (opcode status start offset expected-pc expected-cycles)
    (let* ((bus (make-bus
                 :cartridge
                 (make-fixture-cartridge
                  :program (list opcode offset 0)
                  :start start)))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (setf (cpu-p cpu) status)
      (let ((before-cycles (cpu-cycles cpu)))
        (expect (cpu-step! cpu bus) :to-be expected-cycles)
        (expect (cpu-pc cpu) :to-be expected-pc)
        (expect (- (cpu-cycles cpu) before-cycles)
                :to-be expected-cycles)))))

(describe "CPU interrupt and addressing transitions"
  (it "pushes the return state before entering an NMI vector"
    (let* ((cartridge (set-fixture-vector!
                       (make-fixture-cartridge)
                       #xFFFA
                       #x9000))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (setf (cpu-pc cpu) #x8123)
      (expect (cpu-interrupt! cpu bus :nmi) :to-be 7)
      (expect (cpu-pc cpu) :to-be #x9000)
      (expect (cpu-sp cpu) :to-be #xFA)
      (expect (cpu-cycles cpu) :to-be 14)
      (expect (bus-read bus #x01FD) :to-be #x81)
      (expect (bus-read bus #x01FC) :to-be #x23)
      (let ((stack-status (bus-read bus #x01FB)))
        (expect (logand stack-status #x20) :to-be #x20)
        (expect (logand stack-status #x10) :to-be 0))))

  (it "handles masked, enabled, and forced IRQ delivery"
    (let* ((cartridge (set-fixture-vector!
                       (make-fixture-cartridge)
                       #xFFFE
                       #xA000))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (setf (cpu-pc cpu) #x8123)
      (let ((before-pc (cpu-pc cpu))
            (before-sp (cpu-sp cpu))
            (before-cycles (cpu-cycles cpu)))
        (expect (cpu-interrupt! cpu bus :irq) :to-be nil)
        (expect (cpu-pc cpu) :to-be before-pc)
        (expect (cpu-sp cpu) :to-be before-sp)
        (expect (cpu-cycles cpu) :to-be before-cycles))
      (setf (cpu-p cpu) #x20)
      (expect (cpu-interrupt! cpu bus :irq) :to-be 7)
      (expect (cpu-pc cpu) :to-be #xA000)
      (cpu-reset! cpu bus)
      (setf (cpu-p cpu) #x24
            (cpu-pc cpu) #x8123)
      (expect (cpu-interrupt! cpu bus :irq t) :to-be 7)
      (expect (cpu-pc cpu) :to-be #xA000)))

  (it "propagates arithmetic and rotate flag transitions"
    (labels ((run (program a status)
               (let* ((bus (make-bus
                            :cartridge
                            (make-fixture-cartridge :program program)))
                      (cpu (make-cpu)))
                 (cpu-reset! cpu bus)
                 (setf (cpu-a cpu) a
                       (cpu-p cpu) status)
                 (expect (cpu-step! cpu bus) :to-be 2)
                 cpu)))
      (let ((cpu (run '(#x69 #x01) #x7F 0)))
        (expect (cpu-a cpu) :to-be #x80)
        (expect (logand (cpu-p cpu) cl-nes::+flag-overflow+)
                :to-be cl-nes::+flag-overflow+)
        (expect (logand (cpu-p cpu) cl-nes::+flag-negative+)
                :to-be cl-nes::+flag-negative+)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0))
      (let ((cpu (run '(#x69 #x01) #xFF cl-nes::+flag-carry+)))
        (expect (cpu-a cpu) :to-be 1)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
                :to-be cl-nes::+flag-carry+))
      (let ((cpu (run '(#x2A) #x80 cl-nes::+flag-carry+)))
        (expect (cpu-a cpu) :to-be 1)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
                :to-be cl-nes::+flag-carry+))
      (let ((cpu (run '(#x2A) 0 0)))
        (expect (cpu-a cpu) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
                :to-be cl-nes::+flag-zero+))
      (let ((cpu (run '(#x6A) 1 cl-nes::+flag-carry+)))
        (expect (cpu-a cpu) :to-be #x80)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
                :to-be cl-nes::+flag-carry+))
      (let ((cpu (run '(#x6A) 0 0)))
        (expect (cpu-a cpu) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
                :to-be cl-nes::+flag-zero+))))

  (it "applies page-crossing penalties to indexed reads"
    (let* ((cartridge (make-fixture-cartridge
                       :program '(#xB9 #xFF #x80)))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (setf (aref (cartridge-prg-rom cartridge) #x100) #xA5)
      (cpu-reset! cpu bus)
      (setf (cpu-y cpu) 1)
      (expect (cpu-step! cpu bus) :to-be 5)
      (expect (cpu-a cpu) :to-be #xA5)
      (expect (cpu-pc cpu) :to-be #x8003))
    (let* ((cartridge (make-fixture-cartridge
                       :program '(#xB1 #x20)))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (setf (aref (cartridge-prg-rom cartridge) #x100) #x5A)
      (cpu-reset! cpu bus)
      (bus-write! bus #x20 #xFF)
      (bus-write! bus #x21 #x80)
      (setf (cpu-y cpu) 1)
      (expect (cpu-step! cpu bus) :to-be 6)
      (expect (cpu-a cpu) :to-be #x5A)
      (expect (cpu-pc cpu) :to-be #x8002)))

  (it "wraps the high byte of an indirect jump within its page"
    (let* ((cartridge (make-fixture-cartridge
                       :program '(#x6C #xFF #x00)))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (bus-write! bus 0 #x12)
      (bus-write! bus #x00FF #x34)
      (expect (cpu-step! cpu bus) :to-be 5)
      (expect (cpu-pc cpu) :to-be #x1234))))
