(in-package #:cl-nes/test)

(describe "CPU opcode dispatch (C0-DF)"
  (define-opcode-dispatch-spec
      "dispatches opcode #x~2,'0X in ~D cycles"
    ((#xC0 2)
     (#xC1 6)
     (#xC2 2)
     (#xC3 8)
     (#xC4 3)
     (#xC5 3)
     (#xC6 5)
     (#xC7 5)
     (#xC8 2)
     (#xC9 2)
     (#xCA 2)
     (#xCB 2)
     (#xCC 4)
     (#xCD 4)
     (#xCE 6)
     (#xCF 6)
     (#xD0 3)
     (#xD1 5)
     (#xD3 8)
     (#xD4 4)
     (#xD5 4)
     (#xD6 6)
     (#xD7 6)
     (#xD8 2)
     (#xD9 4)
     (#xDA 2)
     (#xDB 7)
     (#xDC 4)
     (#xDD 4)
     (#xDE 7)
     (#xDF 7))))
