(in-package #:cl-nes/test)

(describe "MMC3 mapper"
  (describe "PRG and CHR banking"
    (it-each ((0 2 3 6 7)
              (#x40 6 3 2 7))
        "maps PRG slots with bank-select bit ~X"
        (bank-select slot-0 slot-1 slot-2 slot-3)
      (with-mmc3-cartridge (cartridge)
        (configure-mmc3-prg-banks cartridge)
        (cartridge-write-prg! cartridge #x8000 bank-select)
        (expect-prg-slot-banks cartridge
                               (list slot-0 slot-1 slot-2 slot-3))))
    (it-each ((0 2 3 4 5 5 6 7 1)
              (#x80 5 6 7 1 2 3 4 5))
        "maps CHR slots with bank-select bit ~X"
        (bank-select slot-0 slot-1 slot-2 slot-3
                     slot-4 slot-5 slot-6 slot-7)
      (with-mmc3-cartridge (cartridge)
        (configure-mmc3-chr-banks cartridge)
        (cartridge-write-prg! cartridge #x8000 bank-select)
        (expect-chr-slot-banks cartridge
                               (list slot-0 slot-1 slot-2 slot-3
                                     slot-4 slot-5 slot-6 slot-7)))))
  (describe "mirroring and IRQ behavior"
    (it "controls mirroring, PRG-RAM, and A12 IRQ filtering"
      (with-mmc3-cartridge (cartridge)
        (cartridge-write-prg! cartridge #xA000 0)
        (expect (cartridge-mirroring cartridge) :to-be :vertical)
        (cartridge-write-prg! cartridge #xA000 1)
        (expect (cartridge-mirroring cartridge) :to-be :horizontal)
        (cartridge-write-prg-ram! cartridge #x6000 #xA5)
        (expect (cartridge-read-prg-ram cartridge #x6000) :to-be #xA5)
        (cartridge-write-prg! cartridge #xA001 0)
        (cartridge-write-prg-ram! cartridge #x6000 #x5A)
        (expect (cartridge-read-prg-ram cartridge #x6000) :to-be nil)
        (cartridge-write-prg! cartridge #xA001 #x80)
        (cartridge-write-prg-ram! cartridge #x6000 #x5A)
        (expect (cartridge-read-prg-ram cartridge #x6000) :to-be #x5A)
        (cartridge-write-prg! cartridge #xA001 #xC0)
        (cartridge-write-prg-ram! cartridge #x6000 #xA5)
        (expect (cartridge-read-prg-ram cartridge #x6000) :to-be #x5A)
        (with-mmc3-cartridge (four-screen :four-screen-p t)
          (cartridge-write-prg! four-screen #xA000 0)
          (expect (cartridge-mirroring four-screen) :to-be :horizontal))
        (cartridge-write-prg! cartridge #xC000 1)
        (cartridge-write-prg! cartridge #xE001 0)
        (pulse-ppu-a12! cartridge 23)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
        (pulse-ppu-a12! cartridge 1)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
        (pulse-ppu-a12! cartridge)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
        (cartridge-write-prg! cartridge #xE000 0)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
        (cartridge-write-prg! cartridge #xE001 0)
        (cartridge-write-prg! cartridge #xC001 0)
        (pulse-ppu-a12! cartridge)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
        (pulse-ppu-a12! cartridge)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be t)))
    (it "distinguishes MMC6 zero-counter reload behavior"
      (with-mmc3-cartridge (cartridge :mapper4-variant :mmc6)
        (cartridge-write-prg! cartridge #xC000 0)
        (cartridge-write-prg! cartridge #xE001 0)
        (pulse-ppu-a12! cartridge)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
        (cartridge-write-prg! cartridge #xC001 0)
        (pulse-ppu-a12! cartridge)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be t)))))
