(in-package #:cl-nes/test)

(describe "MMC5 mapper"
  (describe "EXRAM and IRQ behavior"
    (it "handles MMC5 EXRAM access modes and direct EXRAM helpers"
      (with-mmc5-cartridge (cartridge)
        (write-expansion-registers cartridge
          (#x5104 0))
        (expect (cl-nes::cartridge-write-expansion! cartridge #x5BFF #x55)
                :to-be #x55)
        (expect (cl-nes::cartridge-read-expansion cartridge #x5BFF)
                :to-be nil)
        (cl-nes::cartridge-write-expansion! cartridge #x5C00 #x33)
        (expect (cl-nes::cartridge-read-expansion cartridge #x5C00)
                :to-be #x33)
        (write-expansion-registers cartridge
          (#x5104 3))
        (cl-nes::cartridge-write-expansion! cartridge #x5C00 #x44)
        (expect (cl-nes::cartridge-read-expansion cartridge #x5C00)
                :to-be nil)
        (expect (cl-nes::cartridge-mmc5-write-exram! cartridge #x400 #x5A)
                :to-be #x5A)
        (expect (cl-nes::cartridge-mmc5-read-exram cartridge 0)
                :to-be #x5A)))
    (it "handles MMC5 split registers, multiplier, and scanline IRQ"
      (with-mmc5-cartridge (cartridge)
        (write-expansion-registers cartridge
          (#x5200 #x80)
          (#x5201 #x10)
          (#x5202 #x02))
        (expect (cl-nes::cartridge-mapper5-split-control cartridge)
                :to-be #x80)
        (expect (cl-nes::cartridge-mapper5-split-scroll cartridge)
                :to-be #x10)
        (expect (cl-nes::cartridge-mapper5-split-bank cartridge)
                :to-be #x02)
        (write-expansion-registers cartridge
          (#x5205 3)
          (#x5206 7))
        (expect (cl-nes::cartridge-read-expansion cartridge #x5205)
                :to-be 21)
        (expect (cl-nes::cartridge-read-expansion cartridge #x5206)
                :to-be 0)
        (write-expansion-registers cartridge
          (#x5203 42)
          (#x5204 #x80))
        (cl-nes::cartridge-clock-scanline! cartridge 42)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be t)
        (expect (cl-nes::cartridge-read-expansion cartridge #x5204)
                :to-be #xC0)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
        (cl-nes::cartridge-clock-scanline! cartridge 1)
        (expect (cl-nes::cartridge-read-expansion cartridge #x5204)
                :to-be #x40)
        (write-expansion-registers cartridge
          (#x5204 0))
        (cl-nes::cartridge-clock-scanline! cartridge 42)
        (expect (cl-nes::cartridge-irq-pending-p cartridge) :to-be nil)
        (cl-nes::cartridge-clock-scanline! cartridge 240)
        (expect (cl-nes::cartridge-read-expansion cartridge #x5204)
                :to-be 0)))))
