(in-package #:cl-nes/test)

(defun make-state-transition-cartridge
    (&key (mirroring :horizontal) four-screen-p)
  (make-cartridge
   :prg-rom (make-array #x8000
                        :element-type '(unsigned-byte 8)
                        :initial-element 0)
   :mirroring mirroring
   :four-screen-p four-screen-p
   :chr-writable-p t))

(defun set-fixture-vector! (cartridge address target)
  (let ((rom (cartridge-prg-rom cartridge)))
    (setf (aref rom (- address #x8000))
          (ldb (byte 8 0) target)
          (aref rom (1+ (- address #x8000)))
          (ldb (byte 8 8) target)))
  cartridge)

(describe "CPU state transitions"
  (it "does not advance a stopped CPU"
    (let* ((bus (make-bus :cartridge (make-fixture-cartridge)))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (setf (cpu-stopped-p cpu) t)
      (let ((before-pc (cpu-pc cpu))
            (before-cycles (cpu-cycles cpu)))
        (expect (cpu-step! cpu bus) :to-be 0)
        (expect (cpu-pc cpu) :to-be before-pc)
        (expect (cpu-cycles cpu) :to-be before-cycles))))
  (it-each ((#x10 #x24 #x8000 #x10 #x8012 3)
            (#x30 #xA4 #x8000 #x30 #x8032 3)
            (#x50 #x24 #x8000 #x50 #x8052 3)
            (#x70 #x64 #x8000 #x70 #x8072 3)
            (#x90 #x24 #x8000 #x10 #x8012 3)
            (#xB0 #x25 #x8000 #x30 #x8032 3)
            (#xD0 #x24 #x8000 #x50 #x8052 3)
            (#xF0 #x26 #x8000 #x70 #x8072 3)
            (#x10 #xA4 #x8000 #x10 #x8002 2)
            (#x30 #x24 #x8000 #x30 #x8002 2)
            (#x50 #x64 #x8000 #x50 #x8002 2)
            (#x70 #x24 #x8000 #x70 #x8002 2)
            (#x90 #x25 #x8000 #x90 #x8002 2)
            (#xB0 #x24 #x8000 #xB0 #x8002 2)
            (#xD0 #x26 #x8000 #xD0 #x8002 2)
            (#xF0 #x24 #x8000 #xF0 #x8002 2)
            (#x10 #x24 #x80F0 #x10 #x8102 4)
            (#x10 #x24 #x8100 #xF0 #x80F2 4))
      "applies branch flags and page-crossing cycle penalties"
      (opcode status start offset expected-pc expected-cycles)
    (let* ((bus (make-bus
                 :cartridge
                 (make-fixture-cartridge
                  :program (list opcode offset 0)
                  :start start)))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (setf (cpu-p cpu) status)
      (let ((before-cycles (cpu-cycles cpu)))
        (expect (cpu-step! cpu bus) :to-be expected-cycles)
        (expect (cpu-pc cpu) :to-be expected-pc)
        (expect (- (cpu-cycles cpu) before-cycles)
                :to-be expected-cycles)))))
  (it "wraps the high byte of an indirect jump within its page"
    (let* ((cartridge (make-fixture-cartridge
                       :program '(#x6C #xFF #x00)))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (bus-write! bus 0 #x12)
      (bus-write! bus #x00FF #x34)
      (expect (cpu-step! cpu bus) :to-be 5)
      (expect (cpu-pc cpu) :to-be #x1234)))
  (it "applies page-crossing penalties to indexed reads"
    (let* ((cartridge (make-fixture-cartridge
                       :program '(#xB9 #xFF #x80)))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (setf (aref (cartridge-prg-rom cartridge) #x100) #xA5)
      (cpu-reset! cpu bus)
      (setf (cpu-y cpu) 1)
      (expect (cpu-step! cpu bus) :to-be 5)
      (expect (cpu-a cpu) :to-be #xA5)
      (expect (cpu-pc cpu) :to-be #x8003))
    (let* ((cartridge (make-fixture-cartridge
                       :program '(#xB1 #x20)))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (setf (aref (cartridge-prg-rom cartridge) #x100) #x5A)
      (cpu-reset! cpu bus)
      (bus-write! bus #x20 #xFF)
      (bus-write! bus #x21 #x80)
      (setf (cpu-y cpu) 1)
      (expect (cpu-step! cpu bus) :to-be 6)
      (expect (cpu-a cpu) :to-be #x5A)
      (expect (cpu-pc cpu) :to-be #x8002)))
  (it "propagates arithmetic and rotate flag transitions"
    (labels ((run (program a status)
               (let* ((bus (make-bus
                            :cartridge
                            (make-fixture-cartridge :program program)))
                      (cpu (make-cpu)))
                 (cpu-reset! cpu bus)
                 (setf (cpu-a cpu) a
                       (cpu-p cpu) status)
                 (expect (cpu-step! cpu bus) :to-be 2)
                 cpu)))
      (let ((cpu (run '(#x69 #x01) #x7F 0)))
        (expect (cpu-a cpu) :to-be #x80)
        (expect (logand (cpu-p cpu) cl-nes::+flag-overflow+)
                :to-be cl-nes::+flag-overflow+)
        (expect (logand (cpu-p cpu) cl-nes::+flag-negative+)
                :to-be cl-nes::+flag-negative+)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0))
      (let ((cpu (run '(#x69 #x01) #xFF cl-nes::+flag-carry+)))
        (expect (cpu-a cpu) :to-be 1)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
                :to-be cl-nes::+flag-carry+))
      (let ((cpu (run '(#x2A) #x80 cl-nes::+flag-carry+)))
        (expect (cpu-a cpu) :to-be 1)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
                :to-be cl-nes::+flag-carry+))
      (let ((cpu (run '(#x2A) 0 0)))
        (expect (cpu-a cpu) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
                :to-be cl-nes::+flag-zero+))
      (let ((cpu (run '(#x6A) 1 cl-nes::+flag-carry+)))
        (expect (cpu-a cpu) :to-be #x80)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+)
                :to-be cl-nes::+flag-carry+))
      (let ((cpu (run '(#x6A) 0 0)))
        (expect (cpu-a cpu) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-carry+) :to-be 0)
        (expect (logand (cpu-p cpu) cl-nes::+flag-zero+)
                :to-be cl-nes::+flag-zero+))))
  (it "handles masked, enabled, and forced IRQ delivery"
    (let* ((cartridge (set-fixture-vector!
                       (make-fixture-cartridge)
                       #xFFFE
                       #xA000))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (setf (cpu-pc cpu) #x8123)
      (let ((before-pc (cpu-pc cpu))
            (before-sp (cpu-sp cpu))
            (before-cycles (cpu-cycles cpu)))
        (expect (cpu-interrupt! cpu bus :irq) :to-be nil)
        (expect (cpu-pc cpu) :to-be before-pc)
        (expect (cpu-sp cpu) :to-be before-sp)
        (expect (cpu-cycles cpu) :to-be before-cycles))
      (setf (cpu-p cpu) #x20)
      (expect (cpu-interrupt! cpu bus :irq) :to-be 7)
      (expect (cpu-pc cpu) :to-be #xA000)
      (cpu-reset! cpu bus)
      (setf (cpu-p cpu) #x24
            (cpu-pc cpu) #x8123)
      (expect (cpu-interrupt! cpu bus :irq t) :to-be 7)
      (expect (cpu-pc cpu) :to-be #xA000)))
  (it "pushes the return state before entering an NMI vector"
    (let* ((cartridge (set-fixture-vector!
                       (make-fixture-cartridge)
                       #xFFFA
                       #x9000))
           (bus (make-bus :cartridge cartridge))
           (cpu (make-cpu)))
      (cpu-reset! cpu bus)
      (setf (cpu-pc cpu) #x8123)
      (expect (cpu-interrupt! cpu bus :nmi) :to-be 7)
      (expect (cpu-pc cpu) :to-be #x9000)
      (expect (cpu-sp cpu) :to-be #xFA)
      (expect (cpu-cycles cpu) :to-be 14)
      (expect (bus-read bus #x01FD) :to-be #x81)
      (expect (bus-read bus #x01FC) :to-be #x23)
      (let ((stack-status (bus-read bus #x01FB)))
        (expect (logand stack-status #x20) :to-be #x20)
        (expect (logand stack-status #x10) :to-be 0))))

(describe "NES interrupt transitions"
  (it "delays a pending APU IRQ for one instruction"
    (let* ((nes (make-nes
                 :cartridge
                 (make-fixture-cartridge :program '(#xEA #xEA))))
           (cpu (nes-cpu nes))
           (apu (nes-apu nes)))
      (setf (cl-nes::apu-frame-irq-pending-p apu) t
            (cl-nes::cpu-irq-delay cpu) 1)
      (expect (nes-step/k nes #'identity) :to-be 2)
      (expect (cpu-pc cpu) :to-be #x8001)
      (expect (cl-nes::cpu-irq-delay cpu) :to-be 0)
      (setf (cpu-p cpu)
            (logand (cpu-p cpu)
                    (lognot cl-nes::+flag-interrupt-disable+)))
      (expect (nes-step/k nes #'identity) :to-be 9)
      (expect (cpu-pc cpu) :to-be #x8000)
      (expect (cpu-sp cpu) :to-be #xFA)))
  (it "delivers an MMC5 IRQ after the current instruction"
    (let* ((cartridge (make-patterned-cartridge
                       :mapper 5
                       :prg-banks 16
                       :chr-banks 16))
           (rom (cartridge-prg-rom cartridge)))
      (setf (aref rom 0) #xEA
            (aref rom 1) #xEA
            (aref rom (+ (* 15 cl-nes::+prg-bank-8k-size+) #x1FFC)) 0
            (aref rom (+ (* 15 cl-nes::+prg-bank-8k-size+) #x1FFD)) #x80
            (aref rom (+ (* 15 cl-nes::+prg-bank-8k-size+) #x1FFE)) 0
            (aref rom (+ (* 15 cl-nes::+prg-bank-8k-size+) #x1FFF)) #x80)
      (let* ((nes (make-nes :cartridge cartridge))
             (cpu (nes-cpu nes)))
        (setf (cpu-p cpu)
              (logand (cpu-p cpu)
                      (lognot cl-nes::+flag-interrupt-disable+)))
        (cl-nes::cartridge-write-expansion! cartridge #x5203 1)
        (cl-nes::cartridge-write-expansion! cartridge #x5204 #x80)
        (cl-nes::cartridge-clock-scanline! cartridge 1)
        (expect (nes-step/k nes #'identity) :to-be 9)
        (expect (cpu-pc cpu) :to-be #x8000)
        (expect (cpu-sp cpu) :to-be #xFA)))))

(describe "PPU register and timing transitions"
  (it "resets the scroll latch when status is read"
    (let ((ppu (make-ppu)))
      (ppu-write-register! ppu 5 #x12)
      (setf (ppu-status ppu) #xE0)
      (expect (ppu-read-register ppu 2) :to-be #xE0)
      (expect (ppu-status ppu) :to-be #x60)
      (ppu-write-register! ppu 5 #x34)
      (ppu-write-register! ppu 5 #xA8)
      (expect (cl-nes::ppu-scroll-x ppu) :to-be #x34)
      (expect (cl-nes::ppu-scroll-y ppu) :to-be #xA8)
      (expect (cl-nes::ppu-fine-x ppu) :to-be 4)))
  (it "keeps pattern-table memory open when no cartridge is loaded"
    (let ((ppu (make-ppu)))
      (expect (ppu-read-vram ppu #x1000) :to-be 0)
      (expect (ppu-write-vram! ppu #x1000 #xA5) :to-be #xA5)
      (expect (ppu-read-vram ppu #x1000) :to-be 0)))
  (it "buffers nametable reads and increments VRAM by 32 when selected"
    (let ((ppu (make-ppu)))
      (ppu-write-vram! ppu #x2000 #x55)
      (ppu-write-register! ppu 0 #x04)
      (ppu-write-register! ppu 6 #x20)
      (ppu-write-register! ppu 6 #x00)
      (ppu-write-register! ppu 7 #x11)
      (ppu-write-register! ppu 7 #x22)
      (expect (ppu-read-vram ppu #x2000) :to-be #x11)
      (expect (ppu-read-vram ppu #x2020) :to-be #x22)
      (ppu-write-register! ppu 6 #x20)
      (ppu-write-register! ppu 6 #x00)
      (expect (ppu-read-register ppu 7) :to-be 0)
      (expect (ppu-read-register ppu 7) :to-be #x11)))
  (it "applies horizontal, vertical, and four-screen nametable mapping"
    (let ((horizontal (make-ppu (make-state-transition-cartridge)))
          (vertical (make-ppu
                     (make-state-transition-cartridge
                      :mirroring :vertical)))
          (four-screen (make-ppu
                        (make-state-transition-cartridge
                         :four-screen-p t))))
      (ppu-write-vram! horizontal #x2000 #x11)
      (expect (ppu-read-vram horizontal #x2400) :to-be #x11)
      (ppu-write-vram! vertical #x2000 #x22)
      (ppu-write-vram! vertical #x2400 #x33)
      (expect (ppu-read-vram vertical #x2000) :to-be #x22)
      (expect (ppu-read-vram vertical #x2400) :to-be #x33)
      (ppu-write-vram! four-screen #x2000 #x44)
      (ppu-write-vram! four-screen #x2800 #x55)
      (expect (ppu-read-vram four-screen #x2000) :to-be #x44)
      (expect (ppu-read-vram four-screen #x2800) :to-be #x55)
      (ppu-write-vram! four-screen #x3F10 #x66)
      (expect (ppu-read-vram four-screen #x3F00) :to-be #x66)))
  (it "routes MMC5 nametables through CIRAM, EXRAM, and fill"
    (let* ((cartridge (make-patterned-cartridge
                       :mapper 5
                       :prg-banks 16
                       :chr-banks 16))
           (ppu (make-ppu cartridge)))
      (cl-nes::cartridge-write-expansion! cartridge #x5105 #xE4)
      (cl-nes::cartridge-write-expansion! cartridge #x5106 #xAA)
      (cl-nes::cartridge-write-expansion! cartridge #x5107 2)
      (ppu-write-vram! ppu #x2000 #x11)
      (ppu-write-vram! ppu #x2400 #x22)
      (ppu-write-vram! ppu #x2800 #x33)
      (expect (ppu-read-vram ppu #x2000) :to-be #x11)
      (expect (ppu-read-vram ppu #x2400) :to-be #x22)
      (expect (ppu-read-vram ppu #x2800) :to-be #x33)
      (expect (ppu-read-vram ppu #x2C00) :to-be #xAA)
      (ppu-write-vram! ppu #x2C00 #x55)
      (expect (ppu-read-vram ppu #x2C00) :to-be #xAA)))
  (it "applies horizontal and vertical sprite flips"
    (let* ((ppu (make-ppu (make-fixture-cartridge)))
           (oam (ppu-oam ppu)))
      (ppu-write-vram! ppu #x0000 #x80)
      (ppu-write-vram! ppu #x3F11 #x21)
      (setf (aref oam 0) 0
            (aref oam 1) 0
            (aref oam 3) 8)
      (flet ((expect-pixel (attributes x y)
               (setf (aref oam 2) attributes)
               (multiple-value-bind (color present behind-background)
                   (cl-nes::%sprite-pixel ppu 0 x y)
                 (declare (ignore behind-background))
                 (expect present :to-be t)
                 (expect color :to-be #x21))))
        (expect-pixel 0 8 1)
        (expect-pixel #x40 15 1)
        (expect-pixel #x80 8 8)
        (expect-pixel #xC0 15 8))))
  (it "selects background quadrants and 8x16 sprite pattern tables"
    (let* ((cartridge (make-fixture-cartridge))
           (ppu (make-ppu cartridge)))
      (ppu-write-register! ppu #x00 #x10)
      (ppu-write-register! ppu #x01 #x06)
      (ppu-write-vram! ppu #x2001 #x01)
      (ppu-write-vram! ppu #x1010 #x80)
      (ppu-write-vram! ppu #x3F01 #x22)
      (multiple-value-bind (color present)
          (cl-nes::%background-pixel ppu 8 0)
        (expect color :to-be #x22)
        (expect present :to-be t))
      (multiple-value-bind (color present)
          (cl-nes::%background-pixel ppu 0 0)
        (expect color :to-be 0)
        (expect present :to-be nil))
      (ppu-write-vram! ppu #x2042 #x01)
      (ppu-write-vram! ppu #x23C0 #xC0)
      (ppu-write-vram! ppu #x3F0D #x33)
      (multiple-value-bind (color present)
          (cl-nes::%background-pixel ppu 16 16)
        (expect color :to-be #x33)
        (expect present :to-be t))
      (let ((sprite-ppu (make-ppu (make-fixture-cartridge))))
        (ppu-write-register! sprite-ppu #x00 #x20)
        (ppu-write-vram! sprite-ppu #x1000 #x80)
        (ppu-write-vram! sprite-ppu #x3F11 #x21)
        (setf (aref (ppu-oam sprite-ppu) 0) 0
              (aref (ppu-oam sprite-ppu) 1) 1
              (aref (ppu-oam sprite-ppu) 2) 0
              (aref (ppu-oam sprite-ppu) 3) 8)
        (multiple-value-bind (color present behind)
            (cl-nes::%sprite-pixel sprite-ppu 0 8 1)
          (expect color :to-be #x21)
          (expect present :to-be t)
          (expect behind :to-be nil))
        (let* ((width 256)
               (height 240)
               (occupied (make-array (* width height)
                                     :element-type 'bit
                                     :initial-element 0))
               (opaque (make-array (* width height)
                                   :element-type 'bit
                                   :initial-element 0))
               (index (+ 8 (* 1 width))))
          (setf (aref opaque index) 1)
          (cl-nes::%draw-sprite-pixel! sprite-ppu 0 8 1 opaque occupied)
          (expect (aref occupied index) :to-be 1)
          (expect (logand (ppu-status sprite-ppu) #x40) :to-be #x40)
          (cl-nes::%draw-sprite-pixel! sprite-ppu 0 8 1 opaque occupied)
          (expect (aref occupied index) :to-be 1)))))
  (it "enters vblank, delays NMI delivery, and starts a new frame"
    (let ((ppu (make-ppu (make-fixture-cartridge))))
      (ppu-write-register! ppu 0 #x80)
      (ppu-tick! ppu (* 241 341))
      (expect (cl-nes::ppu-scanline ppu) :to-be 241)
      (expect (cl-nes::ppu-dot ppu) :to-be 0)
      (ppu-tick! ppu)
      (expect (ppu-frame-ready-p ppu) :to-be t)
      (expect (logand (ppu-status ppu) #x80) :to-be #x80)
      (expect (ppu-nmi-pending-p ppu) :to-be t)
      (expect (ppu-take-nmi! ppu) :to-be nil)
      (expect (ppu-take-nmi! ppu) :to-be t)
      (ppu-tick! ppu (* 20 341))
      (expect (cl-nes::ppu-scanline ppu) :to-be 261)
      (expect (cl-nes::ppu-dot ppu) :to-be 1)
      (expect (ppu-frame-ready-p ppu) :to-be nil)
      (expect (ppu-status ppu) :to-be 0)))
  (it "skips the odd-frame pre-render dot when rendering is enabled"
    (let ((ppu (make-ppu (make-fixture-cartridge))))
      (setf (cl-nes::ppu-scanline ppu) 261
            (cl-nes::ppu-dot ppu) 338
            (cl-nes::ppu-odd-frame-p ppu) t
            (ppu-mask ppu) #x08)
      (ppu-tick! ppu)
      (expect (cl-nes::ppu-dot ppu) :to-be 340)
      (ppu-tick! ppu)
      (expect (cl-nes::ppu-scanline ppu) :to-be 0)
      (expect (cl-nes::ppu-dot ppu) :to-be 0)
      (expect (cl-nes::ppu-odd-frame-p ppu) :to-be nil)))
  (it "does not skip the odd-frame pre-render dot when rendering is disabled"
    (let ((ppu (make-ppu (make-fixture-cartridge))))
      (setf (cl-nes::ppu-scanline ppu) 261
            (cl-nes::ppu-dot ppu) 338
            (cl-nes::ppu-odd-frame-p ppu) t
            (ppu-mask ppu) 0)
      (ppu-tick! ppu)
      (expect (cl-nes::ppu-dot ppu) :to-be 339)
      (ppu-tick! ppu 2)
      (expect (cl-nes::ppu-scanline ppu) :to-be 0)
      (expect (cl-nes::ppu-dot ppu) :to-be 0)
      (expect (cl-nes::ppu-odd-frame-p ppu) :to-be nil))))

(describe "Bus state transitions"
  (it "routes CPU windows to PPU, APU, controllers, and cartridge memory"
    (let* ((cartridge (make-fixture-cartridge :program '(#xEA)))
           (ppu (make-ppu cartridge))
           (apu (make-apu))
           (controller-1 (make-controller))
           (controller-2 (make-controller))
           (bus (make-bus :cartridge cartridge
                          :ppu ppu
                          :apu apu
                          :controller-1 controller-1
                          :controller-2 controller-2)))
      (setf (ppu-status ppu) #xE0)
      (expect (bus-read bus #x2002) :to-be #xE0)
      (bus-write! bus #x2001 #x18)
      (expect (ppu-mask ppu) :to-be #x18)
      (setf (cl-nes::apu-frame-irq-pending-p apu) t)
      (expect (bus-read bus #x4015) :to-be #x40)
      (controller-set-buttons! controller-1 cl-nes::+button-a+)
      (controller-set-buttons! controller-2 cl-nes::+button-a+)
      (bus-write! bus #x4016 1)
      (expect (bus-read bus #x4016) :to-be 1)
      (expect (bus-read bus #x4017) :to-be 1)
      (expect (bus-write! bus #x4000 #xFF) :to-be #xFF)
      (expect (bus-write! bus #x4015 0) :to-be 0)
      (expect (bus-write! bus #x5000 #x33) :to-be #x33)
      (expect (bus-read bus #x5000) :to-be #x33)
      (bus-write! bus #x6000 #xB6)
      (expect (bus-read bus #x6000) :to-be #xB6)
      (expect (bus-read bus #x8000) :to-be #xEA)))

  (it "routes mapper expansion and NROM-368 windows"
    (let* ((mapper5 (make-patterned-cartridge
                     :mapper 5
                     :prg-banks 16
                     :chr-banks 16))
           (expansion-bus (make-bus :cartridge mapper5)))
      (bus-write! expansion-bus #x5C00 #xA7)
      (expect (bus-read expansion-bus #x5C00) :to-be #xA7))
    (let* ((prg (make-array (* 48 1024)
                            :element-type '(unsigned-byte 8)
                            :initial-element 0))
           (cartridge (make-cartridge :prg-rom prg))
           (bus (make-bus :cartridge cartridge)))
      (setf (aref (cartridge-prg-rom cartridge) #x0800) #xC3)
      (expect (bus-read bus #x4800) :to-be #xC3)
      (bus-write! bus #x6000 #xD4)
      (expect (aref (cartridge-prg-ram cartridge) 0) :to-be 0)))

  (it "mirrors internal RAM and retains the open-bus value"
    (let ((bus (make-bus :cartridge (make-fixture-cartridge))))
      (bus-write! bus #x0000 #xA5)
      (expect (bus-read bus #x0800) :to-be #xA5)
      (bus-write! bus #x4018 #x5A)
      (expect (bus-read bus #x4018) :to-be #x5A)))
  (it "transfers a page through OAM DMA and consumes its stall once"
    (let ((bus (make-bus :cartridge (make-fixture-cartridge))))
      (dotimes (offset 256)
        (bus-write! bus offset offset))
      (bus-write! bus #x2003 0)
      (bus-write! bus #x4014 0)
      (expect (aref (ppu-oam (cl-nes::bus-ppu bus)) 0) :to-be 0)
      (expect (aref (ppu-oam (cl-nes::bus-ppu bus)) #xFF) :to-be #xFF)
      (expect (ppu-oam-address (cl-nes::bus-ppu bus)) :to-be 0)
      (expect (cl-nes::bus-take-dma-stall-cycles! bus) :to-be 513)
      (expect (cl-nes::bus-take-dma-stall-cycles! bus) :to-be 0))))
