(in-package #:cl-nes)

(defconstant +ppu-width+ 256)
(defconstant +ppu-height+ 240)
(defconstant +ppu-vram-size+ #x4000)

(define-hardware-state ppu
  ((cartridge nil nil)
   (control 0 (unsigned-byte 8))
   (mask 0 (unsigned-byte 8))
  ;; PPUMASK writes reach the rendering pipeline after a short propagation
  ;; delay.  MASK remains the CPU-visible register; these fields hold the
  ;; effective value used by timing-sensitive behavior.
   (rendering-mask 0 (unsigned-byte 8))
   (rendering-mask-pending 0 (unsigned-byte 8))
   (rendering-mask-delay 0 fixnum)
   (rendering-mask-valid-p nil nil)
   (status 0 (unsigned-byte 8))
   (oam-address 0 (unsigned-byte 8))
   (oam (make-array 256 :element-type '(unsigned-byte 8) :initial-element 0) vector)
   (nametable (make-array 2048 :element-type '(unsigned-byte 8) :initial-element 0) vector)
   (palette (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0) vector)
   (vram-address 0 fixnum)
   (temporary-address 0 fixnum)
   (fine-x 0 fixnum)
   (write-toggle nil nil)
   (scroll-x 0 fixnum)
   (scroll-y 0 fixnum)
   (read-buffer 0 (unsigned-byte 8))
   (scanline 0 fixnum)
   (dot 0 fixnum)
   (frame-ready-p nil nil)
   (odd-frame-p nil nil)
   (vblank-suppression-p nil nil)
   (nmi-pending-p nil nil)
   (nmi-delay-p nil nil)
   (decay-value 0 (unsigned-byte 8))
   (decay-clock 0 fixnum)
   (decay-deadlines (make-array 8 :initial-element 0) vector)
   (decay-next-expiry most-positive-fixnum fixnum)
   (framebuffer (make-array (* +ppu-width+ +ppu-height+)
                            :element-type '(unsigned-byte 16)
                            :initial-element 0) vector)
   (background-shift-low 0 (unsigned-byte 16))
   (background-shift-high 0 (unsigned-byte 16))
   (attribute-shift-low 0 (unsigned-byte 16))
   (attribute-shift-high 0 (unsigned-byte 16))
   (next-tile 0 (unsigned-byte 8))
   (next-attribute 0 (unsigned-byte 8))
   (next-pattern-low 0 (unsigned-byte 8))
   (next-pattern-high 0 (unsigned-byte 8))
   (secondary-oam (make-array 32 :element-type '(unsigned-byte 8) :initial-element #xFF) vector)
   (secondary-oam-count 0 fixnum)
   (sprite-evaluation-index 0 fixnum)
   (sprite-shift-low (make-array 8 :element-type '(unsigned-byte 8) :initial-element 0) vector)
   (sprite-shift-high (make-array 8 :element-type '(unsigned-byte 8) :initial-element 0) vector)
   (sprite-x-counter (make-array 8 :element-type '(unsigned-byte 8) :initial-element 0) vector)
   (sprite-attributes (make-array 8 :element-type '(unsigned-byte 8) :initial-element 0) vector)
   (sprite-indexes (make-array 8 :element-type '(unsigned-byte 8) :initial-element 0) vector))
  :constructor %make-ppu
  :exclude (cartridge))

(defconstant +ppu-decay-period+ 1000000)

(defun %ppu-recompute-decay-expiry! (ppu)
  (let ((next-expiry most-positive-fixnum))
    (dotimes (bit 8)
      (let ((deadline (aref (ppu-decay-deadlines ppu) bit)))
        (when (< deadline next-expiry)
          (setf next-expiry deadline))))
    (setf (ppu-decay-next-expiry ppu) next-expiry)))

(defun %ppu-expire-decay! (ppu)
  (let ((now (ppu-decay-clock ppu)))
    (when (<= (ppu-decay-next-expiry ppu) now)
      (dotimes (bit 8)
        (let ((deadline (aref (ppu-decay-deadlines ppu) bit)))
          (when (<= deadline now)
            (setf (ppu-decay-value ppu)
                  (logand (ppu-decay-value ppu)
                          (lognot (ash 1 bit))
                          #xFF)
                  (aref (ppu-decay-deadlines ppu) bit)
                  most-positive-fixnum))))
      (%ppu-recompute-decay-expiry! ppu)))
  ppu)

(defun %ppu-current-decay (ppu)
  (%ppu-expire-decay! ppu)
  (ppu-decay-value ppu))

(defun %ppu-drive-decay! (ppu value &optional (mask #xFF))
  (%ppu-expire-decay! ppu)
  (let ((value (logand value #xFF))
        (mask (logand mask #xFF))
        (deadline (+ (ppu-decay-clock ppu) +ppu-decay-period+)))
    (dotimes (bit 8)
      (let ((bit-mask (ash 1 bit)))
        (when (logbitp bit mask)
          (if (logbitp bit value)
              (setf (ppu-decay-value ppu)
                    (logior (ppu-decay-value ppu) bit-mask))
              (setf (ppu-decay-value ppu)
                    (logand (ppu-decay-value ppu)
                            (lognot bit-mask)
                            #xFF)))
          (setf (aref (ppu-decay-deadlines ppu) bit) deadline))))
    (%ppu-recompute-decay-expiry! ppu))
  value)

(defun %ppu-clock-decay! (ppu ticks)
  (incf (ppu-decay-clock ppu) ticks)
  (%ppu-expire-decay! ppu)
  ppu)
