(in-package #:cl-nes)

(defun %background-pixel (ppu x y)
  (let* ((base-table (logand (ppu-control ppu) 3))
         (base-x (mod base-table 2))
         (base-y (floor base-table 2))
         (world-x (+ x (ppu-scroll-x ppu)))
         (world-y (mod (+ y (ppu-scroll-y ppu)) (* +ppu-height+ 2)))
         (page-x (floor world-x 256))
         (page-y (floor world-y +ppu-height+))
         (logical-x (mod (+ base-x page-x) 2))
         (logical-y (mod (+ base-y page-y) 2))
         (table (+ (* logical-y 2) logical-x))
         (local-x (mod world-x 256))
         (local-y (mod world-y +ppu-height+))
         (tile-x (floor local-x 8))
         (tile-y (floor local-y 8))
         (nametable-base (+ #x2000 (* table #x400)))
         (tile-address (+ nametable-base (* tile-y 32) tile-x))
         (tile (ppu-read-vram ppu tile-address))
         (pattern-base (if (logbitp 4 (ppu-control ppu)) #x1000 0))
         (row (mod local-y 8))
         (low (ppu-read-vram ppu (+ pattern-base (* tile 16) row)))
         (high (ppu-read-vram ppu (+ pattern-base (* tile 16) row 8)))
         (bit (- 7 (mod local-x 8)))
         (color (logior (ldb (byte 1 bit) low)
                        (ash (ldb (byte 1 bit) high) 1)))
         (backdrop (logand (ppu-read-vram ppu #x3F00) #x3F)))
    (if (or (not (logbitp 1 (ppu-mask ppu)))
            (and (< x 8) (not (logbitp 2 (ppu-mask ppu)))))
        (values backdrop nil)
        (if (zerop color)
            (values backdrop nil)
            (let* ((attribute-address
                     (+ nametable-base #x3C0
                        (* (floor tile-y 4) 8)
                        (floor tile-x 4)))
                   (attribute (ppu-read-vram ppu attribute-address))
                   (quadrant (+ (if (>= (mod tile-x 4) 2) 1 0)
                                (if (>= (mod tile-y 4) 2) 2 0)))
                   (palette-number (ldb (byte 2 (* quadrant 2)) attribute)))
              (values
               (logand
                (ppu-read-vram ppu (+ #x3F00 (* palette-number 4) color))
                #x3F)
               t))))))

(defun %sprite-pattern-address (ppu tile attributes pixel-y)
  (let* ((height (if (logbitp 5 (ppu-control ppu)) 16 8))
         (row (if (logbitp 7 attributes)
                  (- (1- height) pixel-y)
                  pixel-y)))
    (if (= height 16)
        (+ (if (logbitp 0 tile) #x1000 0)
           (* (+ (logand tile #xFE) (floor row 8)) 16)
           (mod row 8))
        (+ (if (logbitp 3 (ppu-control ppu)) #x1000 0)
           (* tile 16)
           row))))

(defun %reverse-byte (value)
  (let ((result 0))
    (dotimes (bit 8 result)
      (setf result
            (logior (ash result 1)
                    (ldb (byte 1 bit) value))))))

(defun %sprite-pixel (ppu sprite-index x y)
  (let* ((oam (ppu-oam ppu))
         (base (* sprite-index 4))
         (sprite-y (1+ (aref oam base)))
         (tile (aref oam (+ base 1)))
         (attributes (aref oam (+ base 2)))
         (sprite-x (aref oam (+ base 3)))
         (height (if (logbitp 5 (ppu-control ppu)) 16 8))
         (local-x (- x sprite-x))
         (local-y (- y sprite-y)))
    (when (and (<= 0 local-x) (< local-x 8)
               (<= 0 local-y) (< local-y height)
               (or (>= x 8) (logbitp 4 (ppu-mask ppu))))
      (let* ((pixel-x (if (logbitp 6 attributes) (- 7 local-x) local-x))
             (pattern-address (%sprite-pattern-address ppu tile attributes local-y)))
        (let* ((bit (- 7 pixel-x))
               (low (ppu-read-vram ppu pattern-address t))
               (high (ppu-read-vram ppu (+ pattern-address 8) t))
               (color (logior (ldb (byte 1 bit) low)
                              (ash (ldb (byte 1 bit) high) 1))))
          (unless (zerop color)
            (values
             (logand
              (ppu-read-vram ppu (+ #x3F10
                                     (* (logand attributes 3) 4)
                                     color))
              #x3F)
             t
             (logbitp 5 attributes))))))))

(defun %ppu-rendering-enabled-p (ppu)
  (let ((mask (%ppu-effective-mask ppu)))
    (or (logbitp 3 mask) (logbitp 4 mask))))

(defun %ppu-background-pixel-at-dot (ppu)
  "Read the pixel selected by the dot renderer's current VRAM address.

The address and fine-X state are advanced by the timing code.  Keeping this
lookup separate from the fetch schedule makes the schedule observable while
retaining the existing cartridge nametable and CHR interfaces."
  (let* ((v (ppu-vram-address ppu))
         (coarse-x (logand v #x1F))
         (coarse-y (logand (ash v -5) #x1F))
         (table (logand (ash v -10) 3))
         (fine-y (logand (ash v -12) 7))
         (x (mod (+ (ppu-fine-x ppu) (1- (ppu-dot ppu))) 8))
         (tile-address (+ #x2000 (ash table 10) (ash coarse-y 5) coarse-x))
         (tile (ppu-read-vram ppu tile-address))
         (pattern-base (if (logbitp 4 (ppu-control ppu)) #x1000 0))
         (pattern-address (+ pattern-base (* tile 16) fine-y))
         (low (ppu-read-vram ppu pattern-address))
         (high (ppu-read-vram ppu (+ pattern-address 8)))
         (bit (- 7 x))
         (color (logior (ldb (byte 1 bit) low)
                        (ash (ldb (byte 1 bit) high) 1))))
    (if (or (not (logbitp 1 (%ppu-effective-mask ppu)))
            (and (< (ppu-dot ppu) 9)
                 (not (logbitp 2 (%ppu-effective-mask ppu)))))
        (values (logand (ppu-read-vram ppu #x3F00) #x3F) nil)
        (if (zerop color)
            (values (logand (ppu-read-vram ppu #x3F00) #x3F) nil)
            (let* ((attribute-address
                     (+ #x2000 (ash table 10) #x3C0
                        (* (floor coarse-y 4) 8) (floor coarse-x 4)))
                   (attribute (ppu-read-vram ppu attribute-address))
                   (quadrant (+ (if (>= (mod coarse-x 4) 2) 1 0)
                                (if (>= (mod coarse-y 4) 2) 2 0)))
                   (palette-number (ldb (byte 2 (* quadrant 2)) attribute)))
              (values
               (logand
                (ppu-read-vram ppu (+ #x3F00 (* palette-number 4) color))
                #x3F)
               t))))))

(defun %ppu-palette-pixel (ppu color)
  (let ((color (logand color #x3F))
        (mask (%ppu-effective-mask ppu)))
    (when (logbitp 0 mask)
      (setf color (logand color #x30)))
    (logior color (ash (ldb (byte 3 5) mask) 6))))

(defun %ppu-evaluate-sprites! (ppu scanline)
  (let ((count 0)
        (sprite 0))
    (fill (ppu-secondary-oam ppu) #xFF)
    (loop while (and (< sprite 64) (< count 8))
          for base = (* sprite 4)
          for top = (1+ (aref (ppu-oam ppu) base))
          do (when (and (<= top scanline)
                        (< scanline (+ top (if (logbitp 5 (ppu-control ppu)) 16 8))))
               (replace (ppu-secondary-oam ppu) (ppu-oam ppu)
                        :start1 (* count 4) :start2 base :end2 (+ base 4))
               (setf (aref (ppu-sprite-indexes ppu) count) sprite)
               (incf count))
             (incf sprite))
    (when (= count 8)
      (let ((n sprite)
            (m 0))
        (loop while (< n 64)
              do (let ((top (1+ (aref (ppu-oam ppu) (+ (* n 4) m)))))
                   (if (and (<= top scanline)
                            (< scanline (+ top (if (logbitp 5 (ppu-control ppu)) 16 8))))
                       (progn
                         (setf (ppu-status ppu)
                               (logior (ppu-status ppu) #x20))
                         (return))
                       (progn
                         (incf n)
                         (setf m (mod (1+ m) 4))))))))
    (setf (ppu-secondary-oam-count ppu) count)
    count))

(defun %ppu-sprite-pixel-at-dot (ppu x y background-solid)
  (when (logbitp 3 (%ppu-effective-mask ppu))
    (loop for slot below (ppu-secondary-oam-count ppu)
          for sprite = (aref (ppu-sprite-indexes ppu) slot)
          do (multiple-value-bind (color present behind)
                 (%sprite-pixel ppu sprite x y)
               (when present
                 (when (and (= sprite 0) background-solid (< x 255)
                            (not (logbitp 6 (ppu-status ppu))))
                   (setf (ppu-status ppu) (logior (ppu-status ppu) #x40)))
                 (return (if (and behind background-solid)
                             nil
                             color)))))))

(defun %ppu-render-dot! (ppu)
  (when (and (< (ppu-scanline ppu) +ppu-height+)
             (<= 1 (ppu-dot ppu) 256))
    (let ((x (1- (ppu-dot ppu)))
          (y (ppu-scanline ppu)))
      (multiple-value-bind (background solid)
          (%ppu-background-pixel-at-dot ppu)
        (let ((sprite (%ppu-sprite-pixel-at-dot ppu x y solid)))
          (setf (aref (ppu-framebuffer ppu) (+ x (* y +ppu-width+)))
                (%ppu-palette-pixel ppu (or sprite background))))))))
