(in-package #:cl-nes)

(defun %ppu-mmc5-split-state (ppu dot)
  "Return active, split-X, and split-Y for a background fetch."
  (when (and (< (ppu-scanline ppu) +ppu-height+)
             (ppu-cartridge ppu)
             (= (cartridge-mapper (ppu-cartridge ppu)) 5))
    (let* ((cartridge (ppu-cartridge ppu))
           (control (cartridge-mapper5-split-control cartridge))
           (mode (cartridge-mapper5-exram-mode cartridge))
           (tile-index (floor (1- dot) 8))
           (threshold (logand control #x1F))
           (left-p (zerop (logand control #x40)))
           (active-p (and (logbitp 7 control)
                          (<= mode 1)
                          (if left-p
                              (< tile-index threshold)
                              (>= tile-index threshold)))))
      (when active-p
        (return-from %ppu-mmc5-split-state
          (values t
                  (if left-p tile-index (- tile-index threshold))
                  (mod (+ (ppu-scanline ppu)
                          (cartridge-mapper5-split-scroll cartridge))
                       +ppu-height+))))))
  (values nil 0 0))

(defun %ppu-mmc5-exram-byte (ppu tile-x tile-y)
  (cartridge-read-expansion
   (ppu-cartridge ppu)
   (+ #x5C00 (mod (+ (* (mod tile-y 30) 32) (mod tile-x 32)) #x400))))

(defun %ppu-mmc5-background-chr (ppu address split-p exram-byte)
  (let ((cartridge (ppu-cartridge ppu)))
    (cond
      (split-p (cartridge-mmc5-read-split-chr cartridge address))
      (exram-byte
       (cartridge-mmc5-read-chr-bank cartridge (logand exram-byte #x3F) address))
      (t (ppu-read-vram ppu address)))))

(defun %ppu-background-sample
    (ppu x y tile-x tile-y nametable-base split-p split-x split-y)
  (let* ((cartridge (ppu-cartridge ppu))
         (mode (and cartridge (= (cartridge-mapper cartridge) 5)
                    (cartridge-mapper5-exram-mode cartridge)))
         (exram-tile (and mode (= mode 1) (not split-p)
                          (%ppu-mmc5-exram-byte ppu tile-x tile-y)))
         (effective-tile-x (if split-p split-x tile-x))
         (effective-tile-y (if split-p (floor split-y 8) tile-y))
         (tile (if split-p
                   (%ppu-mmc5-exram-byte ppu effective-tile-x effective-tile-y)
                   (ppu-read-vram ppu (+ nametable-base (* tile-y 32) tile-x))))
         (row (if split-p (mod split-y 8) (mod y 8)))
         (pattern-base (if (logbitp 4 (ppu-control ppu)) #x1000 0))
         (address (+ pattern-base (* tile 16) row))
         (low (%ppu-mmc5-background-chr ppu address split-p exram-tile))
         (high (%ppu-mmc5-background-chr ppu (+ address 8) split-p exram-tile))
         (bit (- 7 (mod x 8)))
         (color (logior (ldb (byte 1 bit) low)
                        (ash (ldb (byte 1 bit) high) 1)))
         (attribute
           (if exram-tile
               (ldb (byte 2 6) exram-tile)
               (let* ((attribute-address
                        (if split-p
                            (+ #x2000 #x3C0
                               (* (floor effective-tile-y 4) 8)
                               (floor effective-tile-x 4))
                            (+ nametable-base #x3C0
                               (* (floor tile-y 4) 8)
                               (floor tile-x 4))))
                      (value (ppu-read-vram ppu attribute-address))
                      (quadrant (+ (if (>= (mod effective-tile-x 4) 2) 1 0)
                                   (if (>= (mod effective-tile-y 4) 2) 2 0))))
                 (ldb (byte 2 (* quadrant 2)) value)))))
    (values color attribute)))

(defun %background-pixel (ppu x y)
  (multiple-value-bind (split-p split-x split-y)
      (%ppu-mmc5-split-state ppu (1+ x))
    (let* ((base-table (logand (ppu-control ppu) 3))
         (base-x (mod base-table 2))
         (base-y (floor base-table 2))
         (world-x (+ x (ppu-scroll-x ppu)))
         (world-y (mod (+ y (ppu-scroll-y ppu)) (* +ppu-height+ 2)))
         (page-x (floor world-x 256))
         (page-y (floor world-y +ppu-height+))
         (logical-x (mod (+ base-x page-x) 2))
         (logical-y (mod (+ base-y page-y) 2))
         (table (+ (* logical-y 2) logical-x))
         (local-x (mod world-x 256))
         (local-y (mod world-y +ppu-height+))
         (tile-x (floor local-x 8))
         (tile-y (floor local-y 8))
         (nametable-base (+ #x2000 (* table #x400)))
         (backdrop (logand (ppu-read-vram ppu #x3F00) #x3F)))
    (multiple-value-bind (color palette-number)
        (%ppu-background-sample ppu local-x local-y tile-x tile-y nametable-base
                                 split-p split-x split-y)
      (if (or (not (logbitp 1 (ppu-mask ppu)))
            (and (< x 8) (not (logbitp 2 (ppu-mask ppu)))))
            (values backdrop nil)
          (if (zerop color)
              (values backdrop nil)
              (values
               (logand
                (ppu-read-vram ppu (+ #x3F00 (* palette-number 4) color))
                #x3F)
               t)))))))

(defun %sprite-pattern-address (ppu tile attributes pixel-y)
  (let* ((height (if (logbitp 5 (ppu-control ppu)) 16 8))
         (row (if (logbitp 7 attributes)
                  (- (1- height) pixel-y)
                  pixel-y)))
    (if (= height 16)
        (+ (if (logbitp 0 tile) #x1000 0)
           (* (+ (logand tile #xFE) (floor row 8)) 16)
           (mod row 8))
        (+ (if (logbitp 3 (ppu-control ppu)) #x1000 0)
           (* tile 16)
           row))))

(defun %reverse-byte (value)
  (let ((result 0))
    (dotimes (bit 8 result)
      (setf result
            (logior (ash result 1)
                    (ldb (byte 1 bit) value))))))

(defun %sprite-pixel (ppu sprite-index x y)
  (let* ((oam (ppu-oam ppu))
         (base (* sprite-index 4))
         (sprite-y (1+ (aref oam base)))
         (tile (aref oam (+ base 1)))
         (attributes (aref oam (+ base 2)))
         (sprite-x (aref oam (+ base 3)))
         (height (if (logbitp 5 (ppu-control ppu)) 16 8))
         (local-x (- x sprite-x))
         (local-y (- y sprite-y)))
    (when (and (<= 0 local-x) (< local-x 8)
               (<= 0 local-y) (< local-y height)
               (or (>= x 8) (logbitp 4 (ppu-mask ppu))))
      (let* ((pixel-x (if (logbitp 6 attributes) (- 7 local-x) local-x))
             (pattern-address (%sprite-pattern-address ppu tile attributes local-y)))
        (let* ((bit (- 7 pixel-x))
               (low (ppu-read-vram ppu pattern-address t))
               (high (ppu-read-vram ppu (+ pattern-address 8) t))
               (color (logior (ldb (byte 1 bit) low)
                              (ash (ldb (byte 1 bit) high) 1))))
          (unless (zerop color)
            (values
             (logand
              (ppu-read-vram ppu (+ #x3F10
                                     (* (logand attributes 3) 4)
                                     color))
              #x3F)
             t
             (logbitp 5 attributes))))))))

(defun %ppu-rendering-enabled-p (ppu)
  (let ((mask (%ppu-effective-mask ppu)))
    (or (logbitp 3 mask) (logbitp 4 mask))))

(defun %ppu-background-pixel-at-dot (ppu)
  "Read the pixel selected by the dot renderer's current VRAM address.

The address and fine-X state are advanced by the timing code.  Keeping this
lookup separate from the fetch schedule makes the schedule observable while
retaining the existing cartridge nametable and CHR interfaces."
  (multiple-value-bind (split-p split-x split-y)
      (%ppu-mmc5-split-state ppu (ppu-dot ppu))
    (let* ((v (ppu-vram-address ppu))
         (coarse-x (logand v #x1F))
         (coarse-y (logand (ash v -5) #x1F))
         (table (logand (ash v -10) 3))
         (fine-y (logand (ash v -12) 7))
         (x (mod (+ (ppu-fine-x ppu) (1- (ppu-dot ppu))) 8))
         (nametable-base (+ #x2000 (ash table 10)))
         (color nil)
         (palette-number nil))
    (multiple-value-setq (color palette-number)
      (%ppu-background-sample ppu x (+ (* coarse-y 8) fine-y)
                              coarse-x coarse-y nametable-base
                              split-p split-x split-y))
    (if (or (not (logbitp 1 (%ppu-effective-mask ppu)))
            (and (< (ppu-dot ppu) 9)
                 (not (logbitp 2 (%ppu-effective-mask ppu)))))
        (values (logand (ppu-read-vram ppu #x3F00) #x3F) nil)
        (if (zerop color)
            (values (logand (ppu-read-vram ppu #x3F00) #x3F) nil)
            (values
             (logand
              (ppu-read-vram ppu (+ #x3F00 (* palette-number 4) color))
              #x3F)
             t))))))

(defun %ppu-palette-pixel (ppu color)
  (let ((color (logand color #x3F))
        (mask (%ppu-effective-mask ppu)))
    (when (logbitp 0 mask)
      (setf color (logand color #x30)))
    (logior color (ash (ldb (byte 3 5) mask) 6))))

(defun %ppu-evaluate-sprites! (ppu scanline)
  (let ((count 0)
        (sprite 0))
    (fill (ppu-secondary-oam ppu) #xFF)
    (loop while (and (< sprite 64) (< count 8))
          for base = (* sprite 4)
          for top = (1+ (aref (ppu-oam ppu) base))
          do (when (and (<= top scanline)
                        (< scanline (+ top (if (logbitp 5 (ppu-control ppu)) 16 8))))
               (replace (ppu-secondary-oam ppu) (ppu-oam ppu)
                        :start1 (* count 4) :start2 base :end2 (+ base 4))
               (setf (aref (ppu-sprite-indexes ppu) count) sprite)
               (incf count))
             (incf sprite))
    (when (= count 8)
      (let ((n sprite)
            (m 0))
        (loop while (< n 64)
              do (let ((top (1+ (aref (ppu-oam ppu) (+ (* n 4) m)))))
                   (if (and (<= top scanline)
                            (< scanline (+ top (if (logbitp 5 (ppu-control ppu)) 16 8))))
                       (progn
                         (setf (ppu-status ppu)
                               (logior (ppu-status ppu) #x20))
                         (return))
                       (progn
                         (incf n)
                         (setf m (mod (1+ m) 4))))))))
    (setf (ppu-secondary-oam-count ppu) count)
    count))

(defun %ppu-sprite-pixel-at-dot (ppu x y background-solid)
  (when (logbitp 3 (%ppu-effective-mask ppu))
    (loop for slot below (ppu-secondary-oam-count ppu)
          for sprite = (aref (ppu-sprite-indexes ppu) slot)
          do (multiple-value-bind (color present behind)
                 (%sprite-pixel ppu sprite x y)
               (when present
                 (when (and (= sprite 0) background-solid (< x 255)
                            (not (logbitp 6 (ppu-status ppu))))
                   (setf (ppu-status ppu) (logior (ppu-status ppu) #x40)))
                 (return (if (and behind background-solid)
                             nil
                             color)))))))

(defun %ppu-render-dot! (ppu)
  (when (and (< (ppu-scanline ppu) +ppu-height+)
             (<= 1 (ppu-dot ppu) 256))
    (let ((x (1- (ppu-dot ppu)))
          (y (ppu-scanline ppu)))
      (multiple-value-bind (background solid)
          (%ppu-background-pixel-at-dot ppu)
        (let ((sprite (%ppu-sprite-pixel-at-dot ppu x y solid)))
          (setf (aref (ppu-framebuffer ppu) (+ x (* y +ppu-width+)))
                (%ppu-palette-pixel ppu (or sprite background))))))))
