(in-package #:cl-nes)

(defun %start-vblank! (ppu)
  (if (ppu-vblank-suppression-p ppu)
      (setf (ppu-vblank-suppression-p ppu) nil)
      (progn
        (setf (ppu-status ppu) (logior (ppu-status ppu) #x80)
              (ppu-frame-ready-p ppu) t)
        (when (logbitp 7 (ppu-control ppu))
          (%request-nmi! ppu)))))

(defun %start-frame! (ppu)
  (setf (ppu-status ppu) (logand (ppu-status ppu) #x1F)
        (ppu-frame-ready-p ppu) nil
        (ppu-nmi-pending-p ppu) nil
        (ppu-nmi-delay-p ppu) nil))

(defun %ppu-effective-mask (ppu)
  (if (ppu-rendering-mask-valid-p ppu)
      (ppu-rendering-mask ppu)
      (ppu-mask ppu)))

(defun %ppu-advance-rendering-mask! (ppu)
  (when (ppu-rendering-mask-valid-p ppu)
    (when (plusp (ppu-rendering-mask-delay ppu))
      (decf (ppu-rendering-mask-delay ppu)))
    (when (zerop (ppu-rendering-mask-delay ppu))
      (setf (ppu-rendering-mask ppu)
            (ppu-rendering-mask-pending ppu)))))

(defun %ppu-rendering-scanline-p (ppu)
  (and (or (< (ppu-scanline ppu) 240)
           (= (ppu-scanline ppu) 261))
       (%ppu-rendering-enabled-p ppu)))

(defun %ppu-clock-render-a12! (ppu high-p &optional (low-cycles 1))
  (when (and (ppu-cartridge ppu)
             (%ppu-rendering-scanline-p ppu))
    (cartridge-clock-ppu-a12! (ppu-cartridge ppu) high-p low-cycles)))

(defun %ppu-a12-high-p (ppu)
  "Return the coarse PPU address phase used by MMC3's A12 edge detector.

  The renderer does not model every nametable fetch, but it preserves the
  pattern-fetch phases that matter to MMC3's low-time filter.  A pattern-table
  access occupies four PPU dots in each eight-dot fetch group.  Background
  fetches also occur at dots 321-336 for the next scanline, while sprite
  fetches occupy dots 257-320."
  (let ((dot (ppu-dot ppu)))
    (or (and (logbitp 4 (ppu-control ppu))
             (or (and (<= 10 dot 256)
                      (< (mod (- dot 10) 8) 4))
                 (and (<= 330 dot 336)
                      (< (mod (- dot 330) 8) 4))))
        (and (logbitp 3 (ppu-control ppu))
             (<= 266 dot 320)
             (< (mod (- dot 266) 8) 4)))))

(defun %ppu-horizontal-increment! (ppu)
  (if (= (logand (ppu-vram-address ppu) #x1F) #x1F)
      (setf (ppu-vram-address ppu)
            (logxor (ppu-vram-address ppu) #x041F))
      (incf (ppu-vram-address ppu)))
  (setf (ppu-vram-address ppu) (logand (ppu-vram-address ppu) #x7FFF)))

(defun %ppu-vertical-increment! (ppu)
  (if (< (logand (ppu-vram-address ppu) #x7000) #x7000)
      (incf (ppu-vram-address ppu) #x1000)
      (let ((coarse-y (logand (ash (ppu-vram-address ppu) -5) #x1F)))
        (setf (ppu-vram-address ppu)
              (logand (ppu-vram-address ppu) #x0FFF))
        (cond
          ((= coarse-y 29)
           (setf (ppu-vram-address ppu)
                 (logxor (logand (ppu-vram-address ppu)
                                 (lognot #x03E0))
                         #x0800)))
          ((= coarse-y 31)
           (setf (ppu-vram-address ppu)
                 (logand (ppu-vram-address ppu) (lognot #x03E0))))
          (t
           (incf (ppu-vram-address ppu) #x0020)))))
  (setf (ppu-vram-address ppu) (logand (ppu-vram-address ppu) #x7FFF)))

(defun %ppu-copy-horizontal! (ppu)
  (setf (ppu-vram-address ppu)
        (logior (logand (ppu-vram-address ppu) #x7BE0)
                (logand (ppu-temporary-address ppu) #x041F))))

(defun %ppu-copy-vertical! (ppu)
  (setf (ppu-vram-address ppu)
        (logior (logand (ppu-vram-address ppu) #x041F)
                (logand (ppu-temporary-address ppu) #x7BE0))))

(defun %ppu-fetch! (ppu address)
  (declare (ignore ppu address)))

(defun %ppu-background-fetch! (ppu dot)
  (let ((phase (logand dot 7)))
    (case phase
      ((1)
       (multiple-value-bind (split-p split-x split-y)
           (%ppu-mmc5-split-state ppu dot)
         (setf (ppu-next-tile ppu)
               (if split-p
                   (%ppu-mmc5-exram-byte ppu split-x (floor split-y 8))
                   (ppu-read-vram ppu
                                  (+ #x2000 (logand (ppu-vram-address ppu)
                                                    #x0FFF)))))))
      ((3) (let* ((v (ppu-vram-address ppu))
                  (tile-x (logand v #x1F))
                  (tile-y (logand (ash v -5) #x1F)))
             (multiple-value-bind (split-p split-x split-y)
                 (%ppu-mmc5-split-state ppu dot)
               (let* ((effective-x (if split-p split-x tile-x))
                      (effective-y (if split-p (floor split-y 8) tile-y))
                      (exram (and (not split-p)
                                  (%ppu-mmc5-exram-tile ppu tile-x tile-y)))
                      (value (or exram
                                  (ppu-read-vram
                                   ppu
                                   (if split-p
                                       (+ #x2000 #x3C0
                                          (* (floor effective-y 4) 8)
                                          (floor effective-x 4))
                                       (+ #x23C0 (logand v #x0C00)
                                          (ash (logand v #x0380) -4)
                                          (ash (logand v #x001F) -2))))))
                      (quadrant (%ppu-attribute-quadrant effective-x effective-y)))
                 (setf (ppu-next-attribute ppu)
                       (if exram
                           (ldb (byte 2 6) exram)
                           (ldb (byte 2 (* quadrant 2)) value)))))))
      ((5)
       (multiple-value-bind (split-p split-x split-y)
           (%ppu-mmc5-split-state ppu dot)
         (declare (ignore split-x))
         (let* ((address (+ (if (and (not split-p)
                                     (logbitp 4 (ppu-control ppu)))
                                #x1000
                                0)
                            (* (ppu-next-tile ppu) 16)
                            (if split-p
                                (logand split-y 7)
                                (logand (ash (ppu-vram-address ppu) -12) 7))))
                (exram (and (not split-p)
                            (%ppu-mmc5-exram-tile
                             ppu (logand (ppu-vram-address ppu) #x1F)
                             (logand (ash (ppu-vram-address ppu) -5) #x1F)))))
           (setf (ppu-next-pattern-low ppu)
                 (%ppu-mmc5-background-chr ppu address split-p exram))
           (%ppu-fetch! ppu address))))
      ((7)
       (multiple-value-bind (split-p split-x split-y)
           (%ppu-mmc5-split-state ppu dot)
         (declare (ignore split-x))
         (let* ((address (+ (if (and (not split-p)
                                     (logbitp 4 (ppu-control ppu)))
                                #x1000
                                0)
                            (* (ppu-next-tile ppu) 16)
                            (if split-p
                                (logand split-y 7)
                                (logand (ash (ppu-vram-address ppu) -12) 7))
                            8))
                (exram (and (not split-p)
                            (%ppu-mmc5-exram-tile
                             ppu (logand (ppu-vram-address ppu) #x1F)
                             (logand (ash (ppu-vram-address ppu) -5) #x1F)))))
           (setf (ppu-next-pattern-high ppu)
                 (%ppu-mmc5-background-chr ppu address split-p exram))
           (%ppu-fetch! ppu address))))
      ((0) (setf (ppu-background-shift-low ppu)
                 (logand #xFFFF
                         (logior (ash (ppu-next-pattern-low ppu) 8)
                                 (ldb (byte 8 0)
                                      (ppu-background-shift-low ppu))))
                 (ppu-background-shift-high ppu)
                 (logand #xFFFF
                         (logior (ash (ppu-next-pattern-high ppu) 8)
                                 (ldb (byte 8 0)
                                      (ppu-background-shift-high ppu))))
                 (ppu-attribute-shift-low ppu)
                 (logand #xFFFF
                         (logior (ash (if (logbitp 0 (ppu-next-attribute ppu))
                                           #xFF
                                           0)
                                       8)
                                 (ldb (byte 8 0)
                                      (ppu-attribute-shift-low ppu))))
                 (ppu-attribute-shift-high ppu)
                 (logand #xFFFF
                         (logior (ash (if (logbitp 1 (ppu-next-attribute ppu))
                                           #xFF
                                           0)
                                       8)
                                 (ldb (byte 8 0)
                                      (ppu-attribute-shift-high ppu)))))
            (%ppu-horizontal-increment! ppu)))))

(defun %ppu-clock-pipeline! (ppu)
  (let ((scanline (ppu-scanline ppu))
        (dot (ppu-dot ppu)))
    (when (or (< scanline 240) (= scanline 261))
      (when (<= 1 dot 256)
        (%ppu-background-fetch! ppu dot))
      (when (<= 321 dot 336)
        (%ppu-background-fetch! ppu dot))
      (when (= dot 256)
        (%ppu-vertical-increment! ppu))
      (when (= dot 257)
        (%ppu-copy-horizontal! ppu))
      (when (and (= scanline 261) (<= 280 dot 304))
        (%ppu-copy-vertical! ppu))
      (when (and (= dot 65)
                 (%ppu-rendering-scanline-p ppu))
        (%ppu-evaluate-sprites! ppu (if (< scanline 240) scanline 0)))
      (when (and (<= 257 dot 320) (zerop (mod (- dot 257) 8)))
        (let* ((sprite (floor (- dot 257) 8))
               (address
                 (if (< sprite (ppu-secondary-oam-count ppu))
                     (let* ((base (* sprite 4))
                            (tile (aref (ppu-secondary-oam ppu) (+ base 1)))
                            (attributes (aref (ppu-secondary-oam ppu) (+ base 2)))
                            (row (- scanline
                                    (1+ (aref (ppu-secondary-oam ppu) base)))))
                       (%sprite-pattern-address ppu tile attributes row))
                     (if (logbitp 3 (ppu-control ppu)) #x1000 0))))
          (when (< sprite (ppu-secondary-oam-count ppu))
            (let* ((base (* sprite 4))
                   (attributes (aref (ppu-secondary-oam ppu) (+ base 2))))
              (setf (aref (ppu-sprite-shift-low ppu) sprite)
                    (ppu-read-vram ppu address t)
                    (aref (ppu-sprite-shift-high ppu) sprite)
                    (ppu-read-vram ppu (+ address 8) t))
              (when (logbitp 6 attributes)
                (setf (aref (ppu-sprite-shift-low ppu) sprite)
                      (%reverse-byte (aref (ppu-sprite-shift-low ppu) sprite))
                      (aref (ppu-sprite-shift-high ppu) sprite)
                      (%reverse-byte (aref (ppu-sprite-shift-high ppu) sprite)))))
          (%ppu-fetch! ppu address)
          (%ppu-fetch! ppu (+ address 8))))))))

(defun ppu-tick! (ppu &optional (ticks 1))
  (loop repeat ticks do
    (when (and (numberp (ppu-nmi-delay-p ppu))
               (plusp (ppu-nmi-delay-p ppu)))
      (decf (ppu-nmi-delay-p ppu)))
    (%ppu-clock-decay! ppu 1)
    (%ppu-advance-rendering-mask! ppu)
    (incf (ppu-dot ppu))
    (%ppu-render-dot! ppu)
    (when (%ppu-rendering-scanline-p ppu)
      (%ppu-shift-background-registers! ppu))
    (when (and (= (ppu-scanline ppu) 240)
               (= (ppu-dot ppu) 65)
               (%ppu-rendering-enabled-p ppu))
      (%ppu-evaluate-sprites! ppu 240))
    (%ppu-clock-pipeline! ppu)
    (%ppu-clock-render-a12! ppu (%ppu-a12-high-p ppu))
    (when (and (= (ppu-scanline ppu) 241) (= (ppu-dot ppu) 1))
      (%start-vblank! ppu))
    (when (and (= (ppu-scanline ppu) 261) (= (ppu-dot ppu) 1))
      (%start-frame! ppu))
    (when (and (= (ppu-scanline ppu) 261)
               (= (ppu-dot ppu) 339)
               (ppu-odd-frame-p ppu)
               (%ppu-rendering-scanline-p ppu))
      (setf (ppu-dot ppu) 340))
    (when (>= (ppu-dot ppu) 341)
      (setf (ppu-dot ppu) 0)
      (incf (ppu-scanline ppu))
      (when (>= (ppu-scanline ppu) 262)
        (setf (ppu-scanline ppu) 0
              (ppu-odd-frame-p ppu) (not (ppu-odd-frame-p ppu))))
      (cartridge-clock-scanline! (ppu-cartridge ppu)
                                 (ppu-scanline ppu))))
  ppu)

(defun ppu-take-nmi! (ppu)
  (when (ppu-nmi-pending-p ppu)
    (if (%nmi-delay-active-p ppu)
        nil
        (progn
          (setf (ppu-nmi-pending-p ppu) nil)
          t))))
