(in-package #:cl-nes)

(defun %background-pixel (ppu x y)
  (let* ((base-table (logand (ppu-control ppu) 3))
         (base-x (mod base-table 2))
         (base-y (floor base-table 2))
         (world-x (+ x (ppu-scroll-x ppu)))
         (world-y (mod (+ y (ppu-scroll-y ppu)) (* +ppu-height+ 2)))
         (page-x (floor world-x 256))
         (page-y (floor world-y +ppu-height+))
         (logical-x (mod (+ base-x page-x) 2))
         (logical-y (mod (+ base-y page-y) 2))
         (table (+ (* logical-y 2) logical-x))
         (local-x (mod world-x 256))
         (local-y (mod world-y +ppu-height+))
         (tile-x (floor local-x 8))
         (tile-y (floor local-y 8))
         (nametable-base (+ #x2000 (* table #x400)))
         (tile-address (+ nametable-base (* tile-y 32) tile-x))
         (tile (ppu-read-vram ppu tile-address))
         (pattern-base (if (logbitp 4 (ppu-control ppu)) #x1000 0))
         (row (mod local-y 8))
         (low (ppu-read-vram ppu (+ pattern-base (* tile 16) row)))
         (high (ppu-read-vram ppu (+ pattern-base (* tile 16) row 8)))
         (bit (- 7 (mod local-x 8)))
         (color (logior (ldb (byte 1 bit) low)
                        (ash (ldb (byte 1 bit) high) 1)))
         (backdrop (logand (ppu-read-vram ppu #x3F00) #x3F)))
    (if (or (not (logbitp 1 (ppu-mask ppu)))
            (and (< x 8) (not (logbitp 2 (ppu-mask ppu)))))
        (values backdrop nil)
        (if (zerop color)
            (values backdrop nil)
            (let* ((attribute-address
                     (+ nametable-base #x3C0
                        (* (floor tile-y 4) 8)
                        (floor tile-x 4)))
                   (attribute (ppu-read-vram ppu attribute-address))
                   (quadrant (+ (if (>= (mod tile-x 4) 2) 1 0)
                                (if (>= (mod tile-y 4) 2) 2 0)))
                   (palette-number (ldb (byte 2 (* quadrant 2)) attribute)))
              (values
               (logand
                (ppu-read-vram ppu (+ #x3F00 (* palette-number 4) color))
                #x3F)
               t))))))

(defun %render-background! (ppu)
  (let ((framebuffer (ppu-framebuffer ppu))
        (opaque (make-array (* +ppu-width+ +ppu-height+)
                            :element-type 'bit
                            :initial-element 0)))
    (if (logbitp 1 (ppu-mask ppu))
        (loop for y below +ppu-height+ do
          (loop for x below +ppu-width+ do
            (let ((index (+ x (* y +ppu-width+))))
              (multiple-value-bind (color solid)
                  (%background-pixel ppu x y)
                (setf (aref framebuffer index) color)
                (when solid
                  (setf (aref opaque index) 1))))))
        (fill framebuffer (logand (ppu-read-vram ppu #x3F00) #x3F)))
    opaque))

(defun %sprite-pixel (ppu sprite-index x y)
  (let* ((oam (ppu-oam ppu))
         (base (* sprite-index 4))
         (sprite-y (1+ (aref oam base)))
         (tile (aref oam (+ base 1)))
         (attributes (aref oam (+ base 2)))
         (sprite-x (aref oam (+ base 3)))
         (height (if (logbitp 5 (ppu-control ppu)) 16 8))
         (local-x (- x sprite-x))
         (local-y (- y sprite-y)))
    (when (and (<= 0 local-x) (< local-x 8)
               (<= 0 local-y) (< local-y height)
               (or (>= x 8) (logbitp 4 (ppu-mask ppu))))
      (let* ((pixel-x (if (logbitp 6 attributes) (- 7 local-x) local-x))
             (pixel-y (if (logbitp 7 attributes)
                          (- (1- height) local-y)
                          local-y))
             (pattern-base 0)
             (tile-number tile)
             (row pixel-y))
        (if (= height 16)
            (setf pattern-base (if (logbitp 0 tile) #x1000 0)
                  tile-number (logand tile #xFE)
                  row (mod pixel-y 8))
            (setf pattern-base (if (logbitp 3 (ppu-control ppu)) #x1000 0)))
        (when (= height 16)
          (incf tile-number (* (floor pixel-y 8) 1)))
        (let* ((bit (- 7 pixel-x))
               (low (ppu-read-vram ppu (+ pattern-base (* tile-number 16) row)
                                   t))
               (high (ppu-read-vram ppu (+ pattern-base (* tile-number 16)
                                          row 8)
                                      t))
               (color (logior (ldb (byte 1 bit) low)
                              (ash (ldb (byte 1 bit) high) 1))))
          (unless (zerop color)
            (values
             (logand
              (ppu-read-vram ppu (+ #x3F10
                                     (* (logand attributes 3) 4)
                                     color))
              #x3F)
             t
             (logbitp 5 attributes))))))))

(defun %sprite-count-on-scanline (ppu y)
  (let ((height (if (logbitp 5 (ppu-control ppu)) 16 8)))
    (loop for sprite below 64
          count (let ((top (1+ (aref (ppu-oam ppu) (* sprite 4)))))
                  (and (<= top y) (< y (+ top height)))))))

(defun %draw-sprite-pixel! (ppu sprite x y background-opaque occupied)
  (multiple-value-bind (color present behind-background)
      (%sprite-pixel ppu sprite x y)
    (when present
      (let ((index (+ x (* y +ppu-width+))))
        (unless (plusp (aref occupied index))
          (when (and (zerop sprite)
                     (< x 255)
                     (plusp (aref background-opaque index)))
            (setf (ppu-status ppu)
                  (logior (ppu-status ppu) #x40)))
          (setf (aref occupied index) 1)
          (unless (and behind-background
                       (plusp (aref background-opaque index)))
            (setf (aref (ppu-framebuffer ppu) index) color)))))))

(defun %render-sprites! (ppu background-opaque)
  (when (logbitp 3 (ppu-mask ppu))
    (let ((occupied (make-array (* +ppu-width+ +ppu-height+)
                                :element-type 'bit
                                :initial-element 0))
          (height (if (logbitp 5 (ppu-control ppu)) 16 8)))
      (loop for y below +ppu-height+
            when (> (%sprite-count-on-scanline ppu y) 8)
              do (setf (ppu-status ppu) (logior (ppu-status ppu) #x20))
                 (return))
      (loop for sprite below 64 do
        (let* ((base (* sprite 4))
               (top (1+ (aref (ppu-oam ppu) base)))
               (left (aref (ppu-oam ppu) (+ base 3)))
               (start-y (max 0 top))
               (end-y (min +ppu-height+ (+ top height)))
               (start-x (max 0 left))
               (end-x (min +ppu-width+ (+ left 8))))
          (loop for y from start-y below end-y do
            (loop for x from start-x below end-x do
              (%draw-sprite-pixel! ppu sprite x y background-opaque occupied))))))))
