(in-package #:cl-nes)

(defconstant +ppu-width+ 256)
(defconstant +ppu-height+ 240)
(defconstant +ppu-vram-size+ #x4000)

(defstruct (ppu
            (:constructor %make-ppu
                (&key cartridge control mask status oam-address oam nametable
                      palette vram-address temporary-address fine-x write-toggle
                      scroll-x scroll-y read-buffer scanline dot frame-ready-p
                      odd-frame-p nmi-pending-p nmi-delay-p decay-value decay-clock
                      decay-deadlines decay-next-expiry rendering-mask
                      rendering-mask-pending rendering-mask-delay
                      rendering-mask-valid-p framebuffer
                      background-opaque occupied
                      background-shift-low background-shift-high
                      attribute-shift-low attribute-shift-high
                      next-tile next-attribute next-pattern-low next-pattern-high
                      secondary-oam secondary-oam-count sprite-evaluation-index
                      sprite-shift-low sprite-shift-high sprite-x-counter
                      sprite-attributes sprite-indexes)))
  (cartridge nil)
  (control 0 :type (unsigned-byte 8))
  (mask 0 :type (unsigned-byte 8))
  ;; PPUMASK writes reach the rendering pipeline after a short propagation
  ;; delay.  MASK remains the CPU-visible register; these fields hold the
  ;; effective value used by timing-sensitive behavior.
  (rendering-mask 0 :type (unsigned-byte 8))
  (rendering-mask-pending 0 :type (unsigned-byte 8))
  (rendering-mask-delay 0 :type fixnum)
  (rendering-mask-valid-p nil)
  (status 0 :type (unsigned-byte 8))
  (oam-address 0 :type (unsigned-byte 8))
  (oam (make-array 256 :element-type '(unsigned-byte 8) :initial-element 0)
       :type vector)
  (nametable (make-array 2048 :element-type '(unsigned-byte 8) :initial-element 0)
             :type vector)
  (palette (make-array 32 :element-type '(unsigned-byte 8) :initial-element 0)
           :type vector)
  (vram-address 0 :type fixnum)
  (temporary-address 0 :type fixnum)
  (fine-x 0 :type fixnum)
  (write-toggle nil)
  (scroll-x 0 :type fixnum)
  (scroll-y 0 :type fixnum)
  (read-buffer 0 :type (unsigned-byte 8))
  (scanline 0 :type fixnum)
  (dot 0 :type fixnum)
  (frame-ready-p nil)
  (odd-frame-p nil)
  (nmi-pending-p nil)
  (nmi-delay-p nil)
  (decay-value 0 :type (unsigned-byte 8))
  (decay-clock 0 :type fixnum)
  (decay-deadlines (make-array 8 :initial-element 0) :type vector)
  (decay-next-expiry most-positive-fixnum :type fixnum)
  (framebuffer (make-array (* +ppu-width+ +ppu-height+)
                           :element-type '(unsigned-byte 16)
                           :initial-element 0)
               :type vector)
  (background-opaque (make-array (* +ppu-width+ +ppu-height+)
                                 :element-type 'bit :initial-element 0)
                     :type vector)
  (occupied (make-array (* +ppu-width+ +ppu-height+)
                       :element-type 'bit :initial-element 0)
            :type vector)
  (background-shift-low 0 :type (unsigned-byte 16))
  (background-shift-high 0 :type (unsigned-byte 16))
  (attribute-shift-low 0 :type (unsigned-byte 16))
  (attribute-shift-high 0 :type (unsigned-byte 16))
  (next-tile 0 :type (unsigned-byte 8))
  (next-attribute 0 :type (unsigned-byte 8))
  (next-pattern-low 0 :type (unsigned-byte 8))
  (next-pattern-high 0 :type (unsigned-byte 8))
  (secondary-oam (make-array 32 :element-type '(unsigned-byte 8)
                             :initial-element #xFF)
                 :type vector)
  (secondary-oam-count 0 :type fixnum)
  (sprite-evaluation-index 0 :type fixnum)
  (sprite-shift-low (make-array 8 :element-type '(unsigned-byte 8)
                                :initial-element 0)
                    :type vector)
  (sprite-shift-high (make-array 8 :element-type '(unsigned-byte 8)
                                 :initial-element 0)
                     :type vector)
  (sprite-x-counter (make-array 8 :element-type '(unsigned-byte 8)
                                :initial-element 0)
                    :type vector)
  (sprite-attributes (make-array 8 :element-type '(unsigned-byte 8)
                                 :initial-element 0)
                     :type vector)
  (sprite-indexes (make-array 8 :element-type '(unsigned-byte 8)
                              :initial-element 0)
                  :type vector))

(defconstant +ppu-decay-period+ 1000000)

(defun %ppu-recompute-decay-expiry! (ppu)
  (let ((next-expiry most-positive-fixnum))
    (dotimes (bit 8)
      (let ((deadline (aref (ppu-decay-deadlines ppu) bit)))
        (when (< deadline next-expiry)
          (setf next-expiry deadline))))
    (setf (ppu-decay-next-expiry ppu) next-expiry)))

(defun %ppu-expire-decay! (ppu)
  (let ((now (ppu-decay-clock ppu)))
    (when (<= (ppu-decay-next-expiry ppu) now)
      (dotimes (bit 8)
        (let ((deadline (aref (ppu-decay-deadlines ppu) bit)))
          (when (<= deadline now)
            (setf (ppu-decay-value ppu)
                  (logand (ppu-decay-value ppu)
                          (lognot (ash 1 bit))
                          #xFF)
                  (aref (ppu-decay-deadlines ppu) bit)
                  most-positive-fixnum))))
      (%ppu-recompute-decay-expiry! ppu)))
  ppu)

(defun %ppu-current-decay (ppu)
  (%ppu-expire-decay! ppu)
  (ppu-decay-value ppu))

(defun %ppu-drive-decay! (ppu value &optional (mask #xFF))
  (%ppu-expire-decay! ppu)
  (let ((value (logand value #xFF))
        (mask (logand mask #xFF))
        (deadline (+ (ppu-decay-clock ppu) +ppu-decay-period+)))
    (dotimes (bit 8)
      (let ((bit-mask (ash 1 bit)))
        (when (logbitp bit mask)
          (if (logbitp bit value)
              (setf (ppu-decay-value ppu)
                    (logior (ppu-decay-value ppu) bit-mask))
              (setf (ppu-decay-value ppu)
                    (logand (ppu-decay-value ppu)
                            (lognot bit-mask)
                            #xFF)))
          (setf (aref (ppu-decay-deadlines ppu) bit) deadline))))
    (%ppu-recompute-decay-expiry! ppu))
  value)

(defun %ppu-clock-decay! (ppu ticks)
  (incf (ppu-decay-clock ppu) ticks)
  (%ppu-expire-decay! ppu)
  ppu)
