(in-package #:cl-nes)

(defstruct (apu-envelope
            (:constructor %make-apu-envelope))
  (loop-p nil)
  (constant-volume-p nil)
  (volume 0 :type fixnum)
  (start-p nil)
  (divider 0 :type fixnum)
  (decay 0 :type fixnum))

(defstruct (apu-pulse
            (:constructor %make-apu-pulse))
  (enabled-p nil)
  (duty 0 :type fixnum)
  (sequence 0 :type fixnum)
  (timer 0 :type fixnum)
  (timer-period 0 :type fixnum)
  (length-counter 0 :type fixnum)
  (envelope (%make-apu-envelope))
  (sweep-enabled-p nil)
  (sweep-period 0 :type fixnum)
  (sweep-negate-p nil)
  (sweep-shift 0 :type fixnum)
  (sweep-divider 0 :type fixnum)
  (sweep-reload-p nil)
  (sweep-mute-p nil))

(defstruct (apu-triangle
            (:constructor %make-apu-triangle))
  (enabled-p nil)
  (timer 0 :type fixnum)
  (timer-period 0 :type fixnum)
  (length-counter 0 :type fixnum)
  (linear-counter 0 :type fixnum)
  (linear-reload-value 0 :type fixnum)
  (linear-reload-p nil)
  (control-p nil)
  (sequence 0 :type fixnum))

(defstruct (apu-noise
            (:constructor %make-apu-noise))
  (enabled-p nil)
  (mode-p nil)
  (timer 0 :type fixnum)
  (timer-period 4 :type fixnum)
  (length-counter 0 :type fixnum)
  (shift-register #x1 :type fixnum)
  (envelope (%make-apu-envelope)))

(defstruct (apu-dmc
            (:constructor %make-apu-dmc))
  (enabled-p nil)
  (irq-enabled-p nil)
  (loop-p nil)
  (irq-pending-p nil)
  (rate-index 0 :type fixnum)
  (timer 0 :type fixnum)
  (timer-period 428 :type fixnum)
  (output 0 :type fixnum)
  (sample-address #xC000 :type fixnum)
  (current-address #xC000 :type fixnum)
  (sample-length 1 :type fixnum)
  (bytes-remaining 0 :type fixnum)
  (sample-buffer 0 :type fixnum)
  (sample-buffer-empty-p t)
  (shift-register 0 :type fixnum)
  (bits-remaining 0 :type fixnum)
  (silence-p t))

(defstruct (apu
            (:constructor %make-apu))
  (pulse-1 (%make-apu-pulse))
  (pulse-2 (%make-apu-pulse))
  (triangle (%make-apu-triangle))
  (noise (%make-apu-noise))
  (dmc (%make-apu-dmc))
  (frame-cycle 0 :type fixnum)
  (frame-step 0 :type fixnum)
  (five-step-p nil)
  ;; A console RESET repeats the last mode written to $4017, while power-up
  ;; starts in four-step mode.
  (frame-last-five-step-p nil)
  (frame-irq-inhibit-p nil)
  (frame-irq-pending-p nil)
  (frame-irq-repeat-count 0 :type fixnum)
  ;; Four-step mode has two clocks after its final sequencer slot.
  ;; 0 means the normal sequence is active, 1/2 are those tail clocks.
  (frame-tail-step 0 :type fixnum)
  (frame-reset-delay 0 :type fixnum)
  (frame-reset-five-step-p nil)
  (frame-reset-irq-inhibit-p nil)
  (cycle-parity 0 :type fixnum)
  (memory-reader nil))
