(in-package #:cl-nes)

(defun %apu-write-pulse-control! (pulse value)
  (setf (apu-pulse-duty pulse) (ldb (byte 2 6) value))
  (let ((envelope (apu-pulse-envelope pulse)))
    (setf (apu-envelope-loop-p envelope) (logbitp 5 value)
          (apu-envelope-constant-volume-p envelope) (logbitp 4 value)
          (apu-envelope-volume envelope) (logand value #x0F))))

(defun %apu-write-pulse-sweep! (pulse value)
  (setf (apu-pulse-sweep-enabled-p pulse) (logbitp 7 value)
        (apu-pulse-sweep-period pulse) (1+ (ldb (byte 3 4) value))
        (apu-pulse-sweep-negate-p pulse) (logbitp 3 value)
        (apu-pulse-sweep-shift pulse) (logand value 7)
        (apu-pulse-sweep-reload-p pulse) t))

(defun %apu-write-triangle-control! (triangle value)
  (setf (apu-triangle-control-p triangle) (logbitp 7 value)
        (apu-triangle-linear-reload-value triangle) (logand value #x7F)))

(defun %apu-write-noise-control! (noise value)
  (let ((envelope (apu-noise-envelope noise)))
    (setf (apu-envelope-loop-p envelope) (logbitp 5 value)
          (apu-envelope-constant-volume-p envelope) (logbitp 4 value)
          (apu-envelope-volume envelope) (logand value #x0F))))

(defun %apu-write-status! (apu value)
  (let ((pulse-1 (apu-pulse-1 apu))
        (pulse-2 (apu-pulse-2 apu))
        (triangle (apu-triangle apu))
        (noise (apu-noise apu))
        (dmc (apu-dmc apu)))
    (setf (apu-dmc-irq-pending-p dmc) nil)
    (setf (apu-pulse-enabled-p pulse-1) (logbitp 0 value)
          (apu-pulse-enabled-p pulse-2) (logbitp 1 value)
          (apu-triangle-enabled-p triangle) (logbitp 2 value)
          (apu-noise-enabled-p noise) (logbitp 3 value))
    (unless (apu-pulse-enabled-p pulse-1)
      (setf (apu-pulse-length-counter pulse-1) 0))
    (unless (apu-pulse-enabled-p pulse-2)
      (setf (apu-pulse-length-counter pulse-2) 0))
    (unless (apu-triangle-enabled-p triangle)
      (setf (apu-triangle-length-counter triangle) 0))
    (unless (apu-noise-enabled-p noise)
      (setf (apu-noise-length-counter noise) 0))
    (setf (apu-dmc-enabled-p dmc) (logbitp 4 value))
    (if (apu-dmc-enabled-p dmc)
        (when (zerop (apu-dmc-bytes-remaining dmc))
          (%apu-dmc-restart! dmc))
        (setf (apu-dmc-bytes-remaining dmc) 0
              (apu-dmc-sample-buffer dmc) 0
              (apu-dmc-sample-buffer-empty-p dmc) t
              (apu-dmc-bits-remaining dmc) 0
              (apu-dmc-silence-p dmc) t))))

(defun apu-write-register! (apu address value)
  (let ((value (logand value #xFF)))
    (case (logand address #xFFFF)
      (#x4000 (%apu-write-pulse-control! (apu-pulse-1 apu) value))
      (#x4001 (%apu-write-pulse-sweep! (apu-pulse-1 apu) value))
      (#x4002 (setf (apu-pulse-timer-period (apu-pulse-1 apu))
                    (logior (logand (apu-pulse-timer-period (apu-pulse-1 apu)) #x700)
                            value)))
      (#x4003 (let ((pulse (apu-pulse-1 apu)))
                (when (apu-pulse-enabled-p pulse)
                  (setf (apu-pulse-length-counter pulse) (%apu-length-value value)))
                (setf (apu-pulse-timer-period pulse)
                      (logior (ash (logand value 7) 8)
                              (logand (apu-pulse-timer-period pulse) #xFF))
                      (apu-pulse-sequence pulse) 0
                      (apu-envelope-start-p (apu-pulse-envelope pulse)) t)))
      (#x4004 (%apu-write-pulse-control! (apu-pulse-2 apu) value))
      (#x4005 (%apu-write-pulse-sweep! (apu-pulse-2 apu) value))
      (#x4006 (setf (apu-pulse-timer-period (apu-pulse-2 apu))
                    (logior (logand (apu-pulse-timer-period (apu-pulse-2 apu)) #x700)
                            value)))
      (#x4007 (let ((pulse (apu-pulse-2 apu)))
                (when (apu-pulse-enabled-p pulse)
                  (setf (apu-pulse-length-counter pulse) (%apu-length-value value)))
                (setf (apu-pulse-timer-period pulse)
                      (logior (ash (logand value 7) 8)
                              (logand (apu-pulse-timer-period pulse) #xFF))
                      (apu-pulse-sequence pulse) 0
                      (apu-envelope-start-p (apu-pulse-envelope pulse)) t)))
      (#x4008 (%apu-write-triangle-control! (apu-triangle apu) value))
      (#x400A (setf (apu-triangle-timer-period (apu-triangle apu))
                    (logior (logand (apu-triangle-timer-period (apu-triangle apu)) #x700)
                            value)))
      (#x400B (let ((triangle (apu-triangle apu)))
                (when (apu-triangle-enabled-p triangle)
                  (setf (apu-triangle-length-counter triangle)
                        (%apu-length-value value)))
                (setf (apu-triangle-timer-period triangle)
                      (logior (ash (logand value 7) 8)
                              (logand (apu-triangle-timer-period triangle) #xFF))
                      (apu-triangle-linear-reload-p triangle) t)))
      (#x400C (%apu-write-noise-control! (apu-noise apu) value))
      (#x400E (let ((noise (apu-noise apu)))
                (setf (apu-noise-mode-p noise) (logbitp 7 value)
                      (apu-noise-timer-period noise)
                      (aref +apu-noise-period-table+ (logand value #x0F)))))
      (#x400F (let ((noise (apu-noise apu)))
                (when (apu-noise-enabled-p noise)
                  (setf (apu-noise-length-counter noise) (%apu-length-value value)))
                (setf (apu-envelope-start-p (apu-noise-envelope noise)) t)))
      (#x4010 (let ((dmc (apu-dmc apu)))
                (setf (apu-dmc-irq-enabled-p dmc) (logbitp 7 value)
                      (apu-dmc-loop-p dmc) (logbitp 6 value)
                      (apu-dmc-rate-index dmc) (logand value #x0F)
                      (apu-dmc-timer-period dmc)
                      (aref +apu-dmc-rate-table+ (logand value #x0F)))
                (unless (apu-dmc-irq-enabled-p dmc)
                  (setf (apu-dmc-irq-pending-p dmc) nil))))
      (#x4011 (setf (apu-dmc-output (apu-dmc apu)) (logand value #x7F)))
      (#x4012 (setf (apu-dmc-sample-address (apu-dmc apu))
                    (+ #xC000 (ash value 6))))
      (#x4013 (setf (apu-dmc-sample-length (apu-dmc apu))
                    (1+ (ash value 4))))
      (#x4015 (%apu-write-status! apu value))
      (#x4017 (setf (apu-frame-last-five-step-p apu) (logbitp 7 value)
                    (apu-frame-reset-delay apu)
                    (if (zerop (apu-cycle-parity apu)) 3 4)
                    (apu-frame-reset-five-step-p apu) (logbitp 7 value)
                    (apu-frame-reset-irq-inhibit-p apu) (logbitp 6 value)
                    ;; The inhibit bit takes effect at the write.  The
                    ;; sequencer mode itself still changes after its
                    ;; hardware reset delay.
                    (apu-frame-irq-inhibit-p apu) (logbitp 6 value))
                (when (logbitp 6 value)
                  (setf (apu-frame-irq-pending-p apu) nil
                        (apu-frame-irq-repeat-count apu) 0))))
    value))

(defun apu-read-register (apu address)
  (case (logand address #xFFFF)
    (#x4015
     (let ((value (logior (if (plusp (apu-pulse-length-counter (apu-pulse-1 apu))) 1 0)
                          (if (plusp (apu-pulse-length-counter (apu-pulse-2 apu))) 2 0)
                          (if (plusp (apu-triangle-length-counter (apu-triangle apu))) 4 0)
                          (if (plusp (apu-noise-length-counter (apu-noise apu))) 8 0)
                          (if (or (plusp (apu-dmc-bytes-remaining (apu-dmc apu)))
                                  (and (plusp (apu-dmc-bits-remaining (apu-dmc apu)))
                                       (not (apu-dmc-silence-p (apu-dmc apu)))))
                              16
                              0)
                          (if (apu-frame-irq-pending-p apu) #x40 0)
                          (if (apu-dmc-irq-pending-p (apu-dmc apu)) #x80 0))))
       (setf (apu-frame-irq-pending-p apu) nil)
       value))
    (otherwise nil)))

(defun apu-irq-pending-p (apu)
  (or (apu-frame-irq-pending-p apu)
      (apu-dmc-irq-pending-p (apu-dmc apu))))

(defun %apu-pulse-output (pulse first-p)
  (let* ((envelope (apu-pulse-envelope pulse))
         (timer (apu-pulse-timer-period pulse))
         (target (%apu-pulse-sweep-target pulse first-p)))
    (if (or (not (apu-pulse-enabled-p pulse))
            (zerop (apu-pulse-length-counter pulse))
            (< timer 8)
            (> target #x7FF)
            (zerop (aref (aref +apu-pulse-duty-table+ (apu-pulse-duty pulse))
                         (apu-pulse-sequence pulse))))
        0
        (%apu-envelope-output envelope))))

(defun %apu-triangle-output (triangle)
  (if (or (not (apu-triangle-enabled-p triangle))
          (zerop (apu-triangle-length-counter triangle))
          (zerop (apu-triangle-linear-counter triangle)))
      0
      (aref +apu-triangle-table+ (apu-triangle-sequence triangle))))

(defun %apu-noise-output (noise)
  (if (or (not (apu-noise-enabled-p noise))
          (zerop (apu-noise-length-counter noise))
          (logbitp 0 (apu-noise-shift-register noise)))
      0
      (%apu-envelope-output (apu-noise-envelope noise))))

(defun apu-sample (apu)
  "Return the current headless mixer output as an unsigned 8-bit integer."
  (let* ((pulse (+ (%apu-pulse-output (apu-pulse-1 apu) t)
                   (%apu-pulse-output (apu-pulse-2 apu) nil)))
         (triangle (%apu-triangle-output (apu-triangle apu)))
         (noise (%apu-noise-output (apu-noise apu)))
         (dmc (apu-dmc-output (apu-dmc apu))))
    (min 255 (+ (* 4 pulse) (* 2 triangle) noise dmc))))
