(in-package #:cl-nes)

(defun %cartridge-chr-offset (cartridge address &optional (sprite-p t))
  (case (cartridge-mapper cartridge)
    (1 (%mapper1-chr-offset cartridge address))
    ((3 11 28)
     (+ (* (cartridge-chr-bank cartridge) +chr-bank-size+)
        (mod address +chr-bank-size+)))
    (22
     (let ((slot (floor address +chr-bank-1k-size+)))
       (+ (* (ash (aref (cartridge-mapper-registers cartridge) slot) -1)
             +chr-bank-1k-size+)
          (mod address +chr-bank-1k-size+))))
    (4 (%mapper4-chr-offset cartridge address))
    (5 (%mapper5-chr-offset cartridge address sprite-p))
    (otherwise address)))

(defun cartridge-read-prg (cartridge address)
  (let* ((mapper (cartridge-mapper cartridge))
         (rom (cartridge-prg-rom cartridge))
         (nrom368-p (and (= mapper 0)
                         (= (length rom) (* 48 1024)))))
    (when (or (and nrom368-p (<= #x4800 address #xFFFF))
              (<= #x8000 address #xFFFF))
      (if (= mapper 5)
          (%mapper5-read-prg cartridge address)
          (aref rom
                (mod
                 (case mapper
                   ((0 3)
                    (if nrom368-p
                        (- address #x4000)
                        (- address #x8000)))
                   (1
                    (%mapper1-prg-offset cartridge address))
                   (2
                    (let* ((offset (- address #x8000))
                           (bank-count (floor (length rom) +prg-bank-size+))
                           (fixed-bank (1- bank-count)))
                      (if (< offset +prg-bank-size+)
                          (+ (* (mod (cartridge-prg-bank cartridge) fixed-bank)
                                +prg-bank-size+)
                             offset)
                          (+ (* fixed-bank +prg-bank-size+)
                             (- offset +prg-bank-size+)))))
                   (4 (%mapper4-prg-offset cartridge address))
                   ((7 11 34) (%banked-32k-prg-offset cartridge address))
                   (22 (%mapper22-prg-offset cartridge address))
                   (28 (%mapper28-prg-offset cartridge address)))
                 (length rom)))))))

(defun cartridge-write-prg! (cartridge address value)
  (when (and (= (cartridge-mapper cartridge) 1)
             (<= #x8000 address #xFFFF))
    (%mapper1-write! cartridge address value))
  (when (and (= (cartridge-mapper cartridge) 2)
             (<= #x8000 address #xFFFF))
    (let ((switchable-bank-count
            (1- (floor (length (cartridge-prg-rom cartridge))
                       +prg-bank-size+))))
      (setf (cartridge-prg-bank cartridge)
            (mod value switchable-bank-count))))
  (when (and (= (cartridge-mapper cartridge) 3)
             (<= #x8000 address #xFFFF))
    (let ((chr-bank-count (floor (length (cartridge-chr-rom cartridge))
                                 +chr-bank-size+)))
      (setf (cartridge-chr-bank cartridge)
            (mod value chr-bank-count))))
  (when (and (= (cartridge-mapper cartridge) 4)
             (<= #x8000 address #xFFFF))
    (%mapper4-write! cartridge address value))
  (when (and (= (cartridge-mapper cartridge) 7)
             (<= #x8000 address #xFFFF))
    (setf (cartridge-prg-bank cartridge) (logand value #x07)
          (cartridge-mirroring cartridge)
          (if (logbitp 4 value) :single-screen-upper :single-screen-lower)))
  (when (and (= (cartridge-mapper cartridge) 11)
             (<= #x8000 address #xFFFF))
    (setf (cartridge-prg-bank cartridge) (logand value #x03)
          (cartridge-chr-bank cartridge) (ldb (byte 4 4) value)))
  (when (and (= (cartridge-mapper cartridge) 22)
             (<= #x8000 address #xFFFF))
    (%mapper22-write! cartridge address value))
  (when (and (= (cartridge-mapper cartridge) 28)
             (or (<= #x5000 address #x5FFF)
                 (<= #x8000 address #xFFFF)))
    (%mapper28-write! cartridge address value))
  (when (and (= (cartridge-mapper cartridge) 34)
             (<= #x8000 address #xFFFF))
    (setf (cartridge-prg-bank cartridge) value))
  (when (and (= (cartridge-mapper cartridge) 5)
             (<= #x8000 address #xFFFF))
    (%mapper5-write-mapped-prg! cartridge address value))
  value)

(defun cartridge-read-prg-ram (cartridge address)
  (when (and (<= #x6000 address #x7FFF)
             (plusp (length (cartridge-prg-ram cartridge))))
    (let ((offset
            (case (cartridge-mapper cartridge)
              (4 (and (cartridge-mapper4-prg-ram-enabled-p cartridge)
                      (- address #x6000)))
              (5 (%mapper5-prg-ram-offset cartridge address))
              (otherwise (- address #x6000)))))
      (when offset
        (aref (cartridge-prg-ram cartridge)
              (mod offset (length (cartridge-prg-ram cartridge))))))))

(defun cartridge-write-prg-ram! (cartridge address value)
  (when (and (<= #x6000 address #x7FFF)
             (plusp (length (cartridge-prg-ram cartridge))))
    (let ((writable-p
            (case (cartridge-mapper cartridge)
              (4 (and (cartridge-mapper4-prg-ram-enabled-p cartridge)
                      (not (cartridge-mapper4-prg-ram-write-protected-p
                            cartridge))))
              (5 (%mapper5-prg-ram-writable-p cartridge))
              (otherwise t))))
      (when writable-p
        (setf (aref (cartridge-prg-ram cartridge)
                    (mod (case (cartridge-mapper cartridge)
                           (5 (%mapper5-prg-ram-offset cartridge address))
                           (otherwise (- address #x6000)))
                         (length (cartridge-prg-ram cartridge))))
              (logand value #xFF)))))
  value)

(defun cartridge-read-chr (cartridge address &optional (sprite-p t))
  (when (<= 0 address #x1FFF)
    (let ((rom (cartridge-chr-rom cartridge)))
      (aref rom
            (mod (%cartridge-chr-offset cartridge address sprite-p)
                 (length rom))))))

(defun cartridge-write-chr! (cartridge address value)
  (when (and (cartridge-chr-writable-p cartridge)
             (<= 0 address #x1FFF))
    (let ((rom (cartridge-chr-rom cartridge)))
      (setf (aref rom
                  (mod (%cartridge-chr-offset cartridge address) (length rom)))
            (logand value #xFF))))
  value)

