(in-package #:cl-nes)

(defun %banked-32k-prg-offset (cartridge address)
  (+ (* (cartridge-prg-bank cartridge) (* 2 +prg-bank-size+))
     (- address #x8000)))

(defun %mapper22-prg-offset (cartridge address)
  (let* ((bank-count (floor (length (cartridge-prg-rom cartridge))
                            +prg-bank-8k-size+))
         (slot (floor (- address #x8000) +prg-bank-8k-size+))
         (bank (case slot
                 (0 (cartridge-prg-bank cartridge))
                 (1 (cartridge-mapper-prg-bank-1 cartridge))
                 (2 (- bank-count 2))
                 (otherwise (1- bank-count)))))
    (+ (* (mod bank bank-count) +prg-bank-8k-size+)
       (mod address +prg-bank-8k-size+))))

(defun %mapper28-prg-offset (cartridge address)
  (let* ((cpu-a14 (if (logbitp 14 address) 1 0))
         (bank-mode (ash (cartridge-mapper-mode cartridge) -2))
         (outer-bank (ash (cartridge-mapper-outer-bank cartridge) 1))
         (current-bank (cartridge-prg-bank cartridge)))
    (when (= (logand (logxor bank-mode cpu-a14) #x03) #x02)
      (setf bank-mode 0))
    (when (zerop (logand bank-mode #x02))
      (setf current-bank (logior (ash current-bank 1) cpu-a14)))
    (let ((bank-mask (1- (ash 2 (logand (ash bank-mode -2) #x03)))))
      (+ (* (logior (logand current-bank bank-mask)
                    (logand outer-bank (lognot bank-mask)))
            +prg-bank-size+)
         (mod address +prg-bank-size+)))))

(defun %mapper28-update-mirroring! (cartridge)
  (setf (cartridge-mirroring cartridge)
        (case (logand (cartridge-mapper-mode cartridge) #x03)
          (0 :single-screen-lower)
          (1 :single-screen-upper)
          (2 :vertical)
          (otherwise :horizontal))))

(defun %mapper28-write-user-mirroring! (cartridge value)
  (when (zerop (logand (cartridge-mapper-mode cartridge) #x02))
    (setf (cartridge-mapper-mode cartridge)
          (dpb (ldb (byte 1 4) value)
               (byte 1 0)
               (cartridge-mapper-mode cartridge))))
  (%mapper28-update-mirroring! cartridge))

(defun %mapper22-write! (cartridge address value)
  (let* ((physical-low (logand address #x03))
         (logical-low (logior (ash (logand physical-low #x01) 1)
                              (ash (logand physical-low #x02) -1)))
         (page (logand address #xF000)))
    (cond
      ((= page #x8000)
       (setf (cartridge-prg-bank cartridge) (logand value #x1F)))
      ((and (= page #x9000) (zerop logical-low))
       (setf (cartridge-mirroring cartridge)
             (if (logbitp 0 value) :horizontal :vertical)))
      ((= page #xA000)
       (setf (cartridge-mapper-prg-bank-1 cartridge) (logand value #x1F)))
      ((<= #xB000 page #xE000)
       (let* ((register (+ (* (floor (- page #xB000) #x1000) 2)
                           (floor logical-low 2)))
              (old (aref (cartridge-mapper-registers cartridge) register)))
         (setf (aref (cartridge-mapper-registers cartridge) register)
               (if (logbitp 0 logical-low)
                   (logior (logand old #x0F) (ash (logand value #x0F) 4))
                   (logior (logand old #xF0) (logand value #x0F))))))))
  value)

(defun %mapper28-write! (cartridge address value)
  (if (<= #x5000 address #x5FFF)
      (setf (cartridge-mapper-register-select cartridge) (logand value #x81))
       (case (cartridge-mapper-register-select cartridge)
         (#x00
          (setf (aref (cartridge-mapper-registers cartridge) 0) value
                (cartridge-chr-bank cartridge) (logand value #x03))
          (%mapper28-write-user-mirroring! cartridge value))
         (#x01
          (setf (aref (cartridge-mapper-registers cartridge) 1) value
                (cartridge-prg-bank cartridge) (logand value #x0F))
          (%mapper28-write-user-mirroring! cartridge value))
        (#x80
         (setf (cartridge-mapper-mode cartridge) (logand value #x3F))
         (%mapper28-update-mirroring! cartridge))
        (#x81
         (setf (cartridge-mapper-outer-bank cartridge) (logand value #x3F)))))
  value)


