(in-package #:cl-nes)

(defun %banked-32k-prg-offset (cartridge address)
  (+ (* (cartridge-prg-bank cartridge) (* 2 +prg-bank-size+))
     (- address #x8000)))

(defun %mapper22-prg-offset (cartridge address)
  (let* ((bank-count (floor (length (cartridge-prg-rom cartridge))
                            +prg-bank-8k-size+))
         (slot (floor (- address #x8000) +prg-bank-8k-size+))
         (bank (case slot
                 (0 (cartridge-prg-bank cartridge))
                 (1 (cartridge-mapper-prg-bank-1 cartridge))
                 (2 (- bank-count 2))
                 (otherwise (1- bank-count)))))
    (+ (* (mod bank bank-count) +prg-bank-8k-size+)
       (mod address +prg-bank-8k-size+))))

(defun %mapper28-prg-offset (cartridge address)
  (let* ((cpu-a14 (if (logbitp 14 address) 1 0))
         (bank-mode (ash (cartridge-mapper-mode cartridge) -2))
         (outer-bank (ash (cartridge-mapper-outer-bank cartridge) 1))
         (current-bank (cartridge-prg-bank cartridge)))
    (when (= (logand (logxor bank-mode cpu-a14) #x03) #x02)
      (setf bank-mode 0))
    (when (zerop (logand bank-mode #x02))
      (setf current-bank (logior (ash current-bank 1) cpu-a14)))
    (let ((bank-mask (1- (ash 2 (logand (ash bank-mode -2) #x03)))))
      (+ (* (logior (logand current-bank bank-mask)
                    (logand outer-bank (lognot bank-mask)))
            +prg-bank-size+)
         (mod address +prg-bank-size+)))))

(defun %mapper22-write! (cartridge address value)
  (let* ((logical-low (%mapper22-logical-low address))
         (page (logand address #xF000)))
    (cond
      ((= page #x8000) (%mapper22-write-prg-bank! cartridge value))
      ((and (= page #x9000) (zerop logical-low))
       (%mapper22-write-mirroring! cartridge value))
      ((= page #xA000) (%mapper22-write-prg-bank-1! cartridge value))
      ((<= #xB000 page #xE000)
       (%mapper22-write-chr-bank-nibble! cartridge address value logical-low))))
  value)

(defun %mapper28-write! (cartridge address value)
  (if (<= #x5000 address #x5FFF)
      (setf (cartridge-mapper-register-select cartridge) (logand value #x81))
      (%mapper28-handle-register-write! cartridge value))
  value)
