(in-package #:cl-nes)

(defun cartridge-cpu-read (cartridge address)
  (cond
    ((null cartridge) nil)
    ((and (%cartridge-nrom-368-p cartridge)
          (%cartridge-nrom-368-address-p address))
     (cartridge-read-prg cartridge address))
    ((%cartridge-cpu-expansion-address-p address)
     (cartridge-read-expansion cartridge address))
    ((%cartridge-cpu-prg-ram-address-p address)
     (cartridge-read-prg-ram cartridge address))
    ((%cartridge-cpu-prg-address-p address)
     (cartridge-read-prg cartridge address))
    (t nil)))

(defun cartridge-cpu-write! (cartridge address value)
  (cond
    ((null cartridge) value)
    ((and (%cartridge-cpu-expansion-address-p address)
          (%cartridge-mapper5-p cartridge))
     (cartridge-write-expansion! cartridge address value))
    ((%cartridge-cpu-expansion-address-p address)
     (cartridge-write-prg! cartridge address value))
    ((and (%cartridge-cpu-prg-ram-address-p address)
          (not (%cartridge-nrom-368-p cartridge)))
     (cartridge-write-prg-ram! cartridge address value))
    ((%cartridge-cpu-prg-address-p address)
     (cartridge-write-prg! cartridge address value))
    (t value))
  value)


(defun cartridge-read-prg (cartridge address)
  (let ((rom (cartridge-prg-rom cartridge)))
    (when (%cartridge-cpu-readable-prg-address-p cartridge address)
      (if (%cartridge-mapper5-p cartridge)
          (%mapper5-read-prg cartridge address)
          (aref rom (%cartridge-prg-read-offset cartridge address))))))

(defun cartridge-write-prg! (cartridge address value)
  (%cartridge-write-prg-register! cartridge address value)
  value)

(defun cartridge-read-prg-ram (cartridge address)
  (when (and (%cartridge-cpu-prg-ram-address-p address)
             (plusp (length (cartridge-prg-ram cartridge))))
    (let ((offset (%cartridge-prg-ram-offset cartridge address)))
      (when offset
        (aref (cartridge-prg-ram cartridge)
              (mod offset (length (cartridge-prg-ram cartridge))))))))

(defun cartridge-write-prg-ram! (cartridge address value)
  (when (and (%cartridge-cpu-prg-ram-address-p address)
             (plusp (length (cartridge-prg-ram cartridge))))
    (let ((writable-p (%cartridge-prg-ram-writable-p cartridge)))
      (when writable-p
        (setf (aref (cartridge-prg-ram cartridge)
                    (mod (%cartridge-prg-ram-offset cartridge address)
                         (length (cartridge-prg-ram cartridge))))
              (logand value #xFF)))))
  value)
