(in-package #:cl-nes)

(defun %fetch-byte (cpu bus)
  (let ((value (bus-read bus (cpu-pc cpu))))
    (setf (cpu-pc cpu) (logand (1+ (cpu-pc cpu)) #xFFFF))
    value))

(defun %fetch-word (cpu bus)
  (let ((low (%fetch-byte cpu bus))
        (high (%fetch-byte cpu bus)))
    (logior low (ash high 8))))

(defun %read-word-zero-page (bus address)
  (let ((low (bus-read bus (logand address #xFF)))
        (high (bus-read bus (logand (1+ address) #xFF))))
    (logior low (ash high 8))))

(defun %addressing-read-base-cycles (mode)
  (ecase mode
    (:zp 3)
    (:zpx 4)
    (:zpy 4)
    (:abs 4)
    (:absx 4)
    (:absy 4)
    (:indx 6)
    (:indy 5)))

(defun %addressing-write-cycles (mode)
  (ecase mode
    (:zp 3)
    (:zpx 4)
    (:zpy 4)
    (:abs 4)
    (:absx 5)
    (:absy 5)
    (:indx 6)
    (:indy 6)))

(defun %addressing-page-crossed-p (base address)
  (/= (logand base #xFF00) (logand address #xFF00)))

(defun %addressing-fixup-address (base address)
  (logior (logand base #xFF00)
          (logand address #x00FF)))

(defun %addressing-indexed-dummy-read-p (mode)
  (member mode '(:absx :absy :indy)))

(defun %address-for-mode (cpu bus mode)
  (define-address-for-mode-cases))

(defun %read-op! (cpu bus mode operation page-cycle-p)
  (if (eq mode :immediate)
      (progn
        (funcall operation cpu (%fetch-byte cpu bus))
        2)
      (multiple-value-bind (address crossed-p base)
          (%address-for-mode cpu bus mode)
        (when (and page-cycle-p crossed-p)
          (bus-read bus (%addressing-fixup-address base address)))
        (funcall operation cpu (bus-read bus address))
        (+ (%addressing-read-base-cycles mode)
           (if (and page-cycle-p crossed-p) 1 0)))))

(defun %nop-op! (cpu bus mode cycles)
  (if (eq mode :immediate)
      (progn
        (%fetch-byte cpu bus)
        cycles)
      (multiple-value-bind (address ignored-crossed-p)
          (%address-for-mode cpu bus mode)
        (declare (ignore ignored-crossed-p))
        (bus-read bus address)
        cycles)))

(defun %write-op! (cpu bus mode value)
  (multiple-value-bind (address ignored-crossed-p base)
      (%address-for-mode cpu bus mode)
    (declare (ignore ignored-crossed-p))
    (when (%addressing-indexed-dummy-read-p mode)
      (bus-read bus (%addressing-fixup-address base address)))
    (bus-write! bus address value)
    (%addressing-write-cycles mode)))

(defun %rmw-op! (cpu bus mode operation cycles)
  (multiple-value-bind (address ignored-crossed-p base)
      (%address-for-mode cpu bus mode)
    (declare (ignore ignored-crossed-p))
    (when (%addressing-indexed-dummy-read-p mode)
      (bus-read bus (%addressing-fixup-address base address)))
    (let* ((old-value (bus-read bus address))
           (new-value (funcall operation cpu old-value)))
      (bus-write! bus address old-value)
      (bus-write! bus address new-value))
    cycles))
