(in-package #:cl-nes)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defparameter +opcode-80-ff-literal-specs+
    '(((#x80 #x82 #x89 #xC2 #xE2) (%nop-op! cpu bus :immediate 2))
      (#xDA 2)
      (#xEA 2)
      (#xFA 2)))
  (defparameter +opcode-80-ff-write-specs+
    '((#x81 :indx (cpu-a cpu))
      (#x83 :indx (logand (cpu-a cpu) (cpu-x cpu)))
      (#x84 :zp (cpu-y cpu))
      (#x85 :zp (cpu-a cpu))
      (#x86 :zp (cpu-x cpu))
      (#x87 :zp (logand (cpu-a cpu) (cpu-x cpu)))
      (#x8C :abs (cpu-y cpu))
      (#x8D :abs (cpu-a cpu))
      (#x8E :abs (cpu-x cpu))
      (#x8F :abs (logand (cpu-a cpu) (cpu-x cpu)))
      (#x91 :indy (cpu-a cpu))
      (#x94 :zpx (cpu-y cpu))
      (#x95 :zpx (cpu-a cpu))
      (#x96 :zpy (cpu-x cpu))
      (#x97 :zpy (logand (cpu-a cpu) (cpu-x cpu)))
      (#x99 :absy (cpu-a cpu))
      (#x9D :absx (cpu-a cpu))))
  (defparameter +opcode-80-ff-adjust-register-specs+
    '((#x88 (cpu-y cpu) 1-)
      (#xC8 (cpu-y cpu) 1+)
      (#xCA (cpu-x cpu) 1-)
      (#xE8 (cpu-x cpu) 1+)))
  (defparameter +opcode-80-ff-transfer-specs+
    '((#x8A (cpu-a cpu) (cpu-x cpu))
      (#x98 (cpu-a cpu) (cpu-y cpu))
      (#xA8 (cpu-y cpu) (cpu-a cpu))
      (#xAA (cpu-x cpu) (cpu-a cpu))
      (#xBA (cpu-x cpu) (cpu-sp cpu))))
  (defparameter +opcode-80-ff-branch-specs+
    '((#x90 (not (%flag-set-p cpu +flag-carry+)))
      (#xB0 (%flag-set-p cpu +flag-carry+))
      (#xD0 (not (%flag-set-p cpu +flag-zero+)))
      (#xF0 (%flag-set-p cpu +flag-zero+))))
  (defparameter +opcode-80-ff-read-specs+
    '((#xA0 :immediate #'%load-y! nil)
      (#xA1 :indx #'%load-a! nil)
      (#xA2 :immediate #'%load-x! nil)
      (#xA3 :indx #'%lax! nil)
      (#xA4 :zp #'%load-y! nil)
      (#xA5 :zp #'%load-a! nil)
      (#xA6 :zp #'%load-x! nil)
      (#xA7 :zp #'%lax! nil)
      (#xA9 :immediate #'%load-a! nil)
      (#xAB :immediate #'%atx! nil)
      (#xAC :abs #'%load-y! nil)
      (#xAD :abs #'%load-a! nil)
      (#xAE :abs #'%load-x! nil)
      (#xAF :abs #'%lax! nil)
      (#xB1 :indy #'%load-a! t)
      (#xB3 :indy #'%lax! t)
      (#xB4 :zpx #'%load-y! nil)
      (#xB5 :zpx #'%load-a! nil)
      (#xB6 :zpy #'%load-x! nil)
      (#xB7 :zpy #'%lax! nil)
      (#xB9 :absy #'%load-a! t)
      (#xBC :absx #'%load-y! t)
      (#xBD :absx #'%load-a! t)
      (#xBE :absy #'%load-x! t)
      (#xBF :absy #'%lax! t)
      (#xC0 :immediate #'%cmp-y! nil)
      (#xC1 :indx #'%cmp-a! nil)
      (#xC4 :zp #'%cmp-y! nil)
      (#xC5 :zp #'%cmp-a! nil)
      (#xC9 :immediate #'%cmp-a! nil)
      (#xCB :immediate #'%axs! nil)
      (#xCC :abs #'%cmp-y! nil)
      (#xCD :abs #'%cmp-a! nil)
      (#xD1 :indy #'%cmp-a! t)
      (#xD5 :zpx #'%cmp-a! nil)
      (#xD9 :absy #'%cmp-a! t)
      (#xDD :absx #'%cmp-a! t)
      (#xE0 :immediate #'%cmp-x! nil)
      (#xE1 :indx #'%sbc! nil)
      (#xE4 :zp #'%cmp-x! nil)
      (#xE5 :zp #'%sbc! nil)
      (#xE9 :immediate #'%sbc! nil)
      (#xEB :immediate #'%sbc! nil)
      (#xEC :abs #'%cmp-x! nil)
      (#xED :abs #'%sbc! nil)
      (#xF1 :indy #'%sbc! t)
      (#xF5 :zpx #'%sbc! nil)
      (#xF9 :absy #'%sbc! t)
      (#xFD :absx #'%sbc! t)))
  (defparameter +opcode-80-ff-rmw-specs+
    '((#xC3 :indx #'%dcp-value! 8)
      (#xC6 :zp #'%dec-value! 5)
      (#xC7 :zp #'%dcp-value! 5)
      (#xCE :abs #'%dec-value! 6)
      (#xCF :abs #'%dcp-value! 6)
      (#xD3 :indy #'%dcp-value! 8)
      (#xD6 :zpx #'%dec-value! 6)
      (#xD7 :zpx #'%dcp-value! 6)
      (#xDB :absy #'%dcp-value! 7)
      (#xDE :absx #'%dec-value! 7)
      (#xDF :absx #'%dcp-value! 7)
      (#xE3 :indx #'%isc-value! 8)
      (#xE6 :zp #'%inc-value! 5)
      (#xE7 :zp #'%isc-value! 5)
      (#xEE :abs #'%inc-value! 6)
      (#xEF :abs #'%isc-value! 6)
      (#xF3 :indy #'%isc-value! 8)
      (#xF6 :zpx #'%inc-value! 6)
      (#xF7 :zpx #'%isc-value! 6)
      (#xFB :absy #'%isc-value! 7)
      (#xFE :absx #'%inc-value! 7)
      (#xFF :absx #'%isc-value! 7)))
  (defparameter +opcode-80-ff-flag-specs+
    '((#xB8 +flag-overflow+ nil)
      (#xD8 +flag-decimal+ nil)
      (#xF8 +flag-decimal+ t)))
  (defparameter +opcode-80-ff-zpx-nop-specs+
    '((#xD4 (%nop-op! cpu bus :zpx 4))
      (#xF4 (%nop-op! cpu bus :zpx 4))))
  (defparameter +opcode-80-ff-absx-nop-specs+
    '((#xDC (%nop-op! cpu bus :absx 4))
      (#xFC (%nop-op! cpu bus :absx 4)))))
