(in-package #:cl-nes)

(defun %dispatch-cpu-opcode-80-ff (cpu bus opcode)
  (case opcode
    ((#x80 #x82 #x89 #xC2 #xE2)
     (%nop-op! cpu bus :immediate 2))
    (#x81 (%write-op! cpu bus :indx (cpu-a cpu)))
    (#x83 (%write-op! cpu bus :indx (logand (cpu-a cpu) (cpu-x cpu))))
    (#x84 (%write-op! cpu bus :zp (cpu-y cpu)))
    (#x85 (%write-op! cpu bus :zp (cpu-a cpu)))
    (#x86 (%write-op! cpu bus :zp (cpu-x cpu)))
    (#x87 (%write-op! cpu bus :zp (logand (cpu-a cpu) (cpu-x cpu))))
    (#x88
     (setf (cpu-y cpu) (mod (1- (cpu-y cpu)) 256))
     (%update-zn! cpu (cpu-y cpu))
     2)
    (#x8A
     (setf (cpu-a cpu) (cpu-x cpu))
     (%update-zn! cpu (cpu-a cpu))
     2)
    (#x8C (%write-op! cpu bus :abs (cpu-y cpu)))
    (#x8D (%write-op! cpu bus :abs (cpu-a cpu)))
    (#x8E (%write-op! cpu bus :abs (cpu-x cpu)))
    (#x8F (%write-op! cpu bus :abs (logand (cpu-a cpu) (cpu-x cpu))))
    (#x90 (%branch! cpu bus (not (%flag-set-p cpu +flag-carry+))))
    (#x91 (%write-op! cpu bus :indy (cpu-a cpu)))
    (#x94 (%write-op! cpu bus :zpx (cpu-y cpu)))
    (#x95 (%write-op! cpu bus :zpx (cpu-a cpu)))
    (#x96 (%write-op! cpu bus :zpy (cpu-x cpu)))
    (#x97 (%write-op! cpu bus :zpy (logand (cpu-a cpu) (cpu-x cpu))))
    (#x98
     (setf (cpu-a cpu) (cpu-y cpu))
     (%update-zn! cpu (cpu-a cpu))
     2)
    (#x99 (%write-op! cpu bus :absy (cpu-a cpu)))
    (#x9A
     (setf (cpu-sp cpu) (cpu-x cpu))
     2)
    (#x9C (%unstable-store-op! cpu bus (cpu-x cpu) (cpu-y cpu)))
    (#x9D (%write-op! cpu bus :absx (cpu-a cpu)))
    (#x9E (%unstable-store-op! cpu bus (cpu-y cpu) (cpu-x cpu)))

    (#xA0 (%read-op! cpu bus :immediate
                     (lambda (cpu value)
                       (%update-zn! cpu (setf (cpu-y cpu) value)))
                     nil))
    (#xA1 (%read-op! cpu bus :indx #'%load-a! nil))
    (#xA2 (%read-op! cpu bus :immediate #'%load-x! nil))
    (#xA3 (%read-op! cpu bus :indx #'%lax! nil))
    (#xA4 (%read-op! cpu bus :zp #'%load-y! nil))
    (#xA5 (%read-op! cpu bus :zp #'%load-a! nil))
    (#xA6 (%read-op! cpu bus :zp #'%load-x! nil))
    (#xA7 (%read-op! cpu bus :zp #'%lax! nil))
    (#xA8
     (setf (cpu-y cpu) (cpu-a cpu))
     (%update-zn! cpu (cpu-y cpu))
     2)
    (#xA9 (%read-op! cpu bus :immediate #'%load-a! nil))
    (#xAA
     (setf (cpu-x cpu) (cpu-a cpu))
     (%update-zn! cpu (cpu-x cpu))
     2)
    (#xAB (%read-op! cpu bus :immediate #'%atx! nil))
    (#xAC (%read-op! cpu bus :abs #'%load-y! nil))
    (#xAD (%read-op! cpu bus :abs #'%load-a! nil))
    (#xAE (%read-op! cpu bus :abs #'%load-x! nil))
    (#xAF (%read-op! cpu bus :abs #'%lax! nil))
    (#xB0 (%branch! cpu bus (%flag-set-p cpu +flag-carry+)))
    (#xB1 (%read-op! cpu bus :indy #'%load-a! t))
    (#xB3 (%read-op! cpu bus :indy #'%lax! t))
    (#xB4 (%read-op! cpu bus :zpx #'%load-y! nil))
    (#xB5 (%read-op! cpu bus :zpx #'%load-a! nil))
    (#xB6 (%read-op! cpu bus :zpy #'%load-x! nil))
    (#xB7 (%read-op! cpu bus :zpy #'%lax! nil))
    (#xB8 (%set-flag! cpu +flag-overflow+ nil) 2)
    (#xB9 (%read-op! cpu bus :absy #'%load-a! t))
    (#xBA
     (setf (cpu-x cpu) (cpu-sp cpu))
     (%update-zn! cpu (cpu-x cpu))
     2)
    (#xBC (%read-op! cpu bus :absx #'%load-y! t))
    (#xBD (%read-op! cpu bus :absx #'%load-a! t))
    (#xBE (%read-op! cpu bus :absy #'%load-x! t))
    (#xBF (%read-op! cpu bus :absy #'%lax! t))

    (#xC0 (%read-op! cpu bus :immediate #'%cmp-y! nil))
    (#xC1 (%read-op! cpu bus :indx #'%cmp-a! nil))
    (#xC3 (%rmw-op! cpu bus :indx #'%dcp-value! 8))
    (#xC4 (%read-op! cpu bus :zp #'%cmp-y! nil))
    (#xC5 (%read-op! cpu bus :zp #'%cmp-a! nil))
    (#xC6 (%rmw-op! cpu bus :zp #'%dec-value! 5))
    (#xC7 (%rmw-op! cpu bus :zp #'%dcp-value! 5))
    (#xC8
     (setf (cpu-y cpu) (mod (1+ (cpu-y cpu)) 256))
     (%update-zn! cpu (cpu-y cpu))
     2)
    (#xC9 (%read-op! cpu bus :immediate #'%cmp-a! nil))
    (#xCA
     (setf (cpu-x cpu) (mod (1- (cpu-x cpu)) 256))
     (%update-zn! cpu (cpu-x cpu))
     2)
    (#xCB (%read-op! cpu bus :immediate #'%axs! nil))
    (#xCC (%read-op! cpu bus :abs #'%cmp-y! nil))
    (#xCD (%read-op! cpu bus :abs #'%cmp-a! nil))
    (#xCE (%rmw-op! cpu bus :abs #'%dec-value! 6))
    (#xCF (%rmw-op! cpu bus :abs #'%dcp-value! 6))
    (#xD0 (%branch! cpu bus (not (%flag-set-p cpu +flag-zero+))))
    (#xD1 (%read-op! cpu bus :indy #'%cmp-a! t))
    (#xD3 (%rmw-op! cpu bus :indy #'%dcp-value! 8))
    (#xD4 (%nop-op! cpu bus :zpx 4))
    (#xD5 (%read-op! cpu bus :zpx #'%cmp-a! nil))
    (#xD6 (%rmw-op! cpu bus :zpx #'%dec-value! 6))
    (#xD7 (%rmw-op! cpu bus :zpx #'%dcp-value! 6))
    (#xD8 (%set-flag! cpu +flag-decimal+ nil) 2)
    (#xD9 (%read-op! cpu bus :absy #'%cmp-a! t))
    (#xDA 2)
    (#xDB (%rmw-op! cpu bus :absy #'%dcp-value! 7))
    (#xDC (%nop-op! cpu bus :absx 4))
    (#xDD (%read-op! cpu bus :absx #'%cmp-a! t))
    (#xDE (%rmw-op! cpu bus :absx #'%dec-value! 7))
    (#xDF (%rmw-op! cpu bus :absx #'%dcp-value! 7))

    (#xE0 (%read-op! cpu bus :immediate #'%cmp-x! nil))
    (#xE1 (%read-op! cpu bus :indx #'%sbc! nil))
    (#xE3 (%rmw-op! cpu bus :indx #'%isc-value! 8))
    (#xE4 (%read-op! cpu bus :zp #'%cmp-x! nil))
    (#xE5 (%read-op! cpu bus :zp #'%sbc! nil))
    (#xE6 (%rmw-op! cpu bus :zp #'%inc-value! 5))
    (#xE7 (%rmw-op! cpu bus :zp #'%isc-value! 5))
    (#xE8
     (setf (cpu-x cpu) (mod (1+ (cpu-x cpu)) 256))
     (%update-zn! cpu (cpu-x cpu))
     2)
    (#xE9 (%read-op! cpu bus :immediate #'%sbc! nil))
    (#xEA 2)
    (#xEB (%read-op! cpu bus :immediate #'%sbc! nil))
    (#xEC (%read-op! cpu bus :abs #'%cmp-x! nil))
    (#xED (%read-op! cpu bus :abs #'%sbc! nil))
    (#xEE (%rmw-op! cpu bus :abs #'%inc-value! 6))
    (#xEF (%rmw-op! cpu bus :abs #'%isc-value! 6))
    (#xF0 (%branch! cpu bus (%flag-set-p cpu +flag-zero+)))
    (#xF1 (%read-op! cpu bus :indy #'%sbc! t))
    (#xF3 (%rmw-op! cpu bus :indy #'%isc-value! 8))
    (#xF4 (%nop-op! cpu bus :zpx 4))
    (#xF5 (%read-op! cpu bus :zpx #'%sbc! nil))
    (#xF6 (%rmw-op! cpu bus :zpx #'%inc-value! 6))
    (#xF7 (%rmw-op! cpu bus :zpx #'%isc-value! 6))
    (#xF8 (%set-flag! cpu +flag-decimal+ t) 2)
    (#xF9 (%read-op! cpu bus :absy #'%sbc! t))
    (#xFA 2)
    (#xFB (%rmw-op! cpu bus :absy #'%isc-value! 7))
    (#xFC (%nop-op! cpu bus :absx 4))
    (#xFD (%read-op! cpu bus :absx #'%sbc! t))
    (#xFE (%rmw-op! cpu bus :absx #'%inc-value! 7))
    (#xFF (%rmw-op! cpu bus :absx #'%isc-value! 7))
    (otherwise nil)))
