(in-package #:cl-nes)

(defun cpu-step! (cpu bus)
  (if (cpu-stopped-p cpu)
      0
      (let* ((address (cpu-pc cpu))
             (opcode (%fetch-byte cpu bus))
             (cycles
               (case opcode
                 (#x00
                  (setf (cpu-pc cpu) (logand (1+ (cpu-pc cpu)) #xFFFF))
                  (%push-word! cpu bus (cpu-pc cpu))
                  (%push-byte! cpu bus (%status-for-stack cpu t))
                  (%set-flag! cpu +flag-interrupt-disable+ t)
                   (setf (cpu-pc cpu)
                         (logior (bus-read bus #xFFFE)
                                 (ash (bus-read bus #xFFFF) 8)))
                   7)
                 (#x01 (%read-op! cpu bus :indx #'%ora! nil))
                 (#x03 (%rmw-op! cpu bus :indx #'%slo-value! 8))
                 (#x05 (%read-op! cpu bus :zp #'%ora! nil))
                 (#x06 (%rmw-op! cpu bus :zp #'%asl-value! 5))
                 (#x07 (%rmw-op! cpu bus :zp #'%slo-value! 5))
                 (#x08 (%push-byte! cpu bus (%status-for-stack cpu t)) 3)
                 (#x09 (%read-op! cpu bus :immediate #'%ora! nil))
                 (#x0B (%read-op! cpu bus :immediate #'%aac! nil))
                 ((#x04 #x44 #x64) (%nop-op! cpu bus :zp 3))
                 ((#x14 #x34 #x54 #x74 #xD4 #xF4)
                  (%nop-op! cpu bus :zpx 4))
                 ((#x80 #x82 #x89 #xC2 #xE2)
                  (%nop-op! cpu bus :immediate 2))
                 (#x0A
                   (setf (cpu-a cpu) (%asl-value! cpu (cpu-a cpu)))
                   2)
                 (#x0D (%read-op! cpu bus :abs #'%ora! nil))
                 (#x0E (%rmw-op! cpu bus :abs #'%asl-value! 6))
                 (#x0C (%nop-op! cpu bus :abs 4))
                 (#x0F (%rmw-op! cpu bus :abs #'%slo-value! 6))
                 (#x10 (%branch! cpu bus (not (%flag-set-p cpu +flag-negative+))))
                 (#x11 (%read-op! cpu bus :indy #'%ora! t))
                 (#x13 (%rmw-op! cpu bus :indy #'%slo-value! 8))
                 (#x15 (%read-op! cpu bus :zpx #'%ora! nil))
                 (#x16 (%rmw-op! cpu bus :zpx #'%asl-value! 6))
                 (#x17 (%rmw-op! cpu bus :zpx #'%slo-value! 6))
                 (#x18 (%set-flag! cpu +flag-carry+ nil) 2)
                 (#x19 (%read-op! cpu bus :absy #'%ora! t))
                 (#x1B (%rmw-op! cpu bus :absy #'%slo-value! 7))
                 ((#x1A #x3A #x5A #x7A #xDA #xFA) 2)
                 ((#x1C #x3C #x5C #x7C #xDC #xFC)
                  (%nop-op! cpu bus :absx 4))
                 (#x1D (%read-op! cpu bus :absx #'%ora! t))
                 (#x1E (%rmw-op! cpu bus :absx #'%asl-value! 7))
                 (#x1F (%rmw-op! cpu bus :absx #'%slo-value! 7))

                 (#x20
                  (let ((target (%fetch-word cpu bus)))
                    (%push-word! cpu bus (logand (1- (cpu-pc cpu)) #xFFFF))
                    (setf (cpu-pc cpu) target)
                    6))
                 (#x21 (%read-op! cpu bus :indx #'%and! nil))
                 (#x23 (%rmw-op! cpu bus :indx #'%rla-value! 8))
                 (#x24
                  (multiple-value-bind (operand ignored)
                      (%address-for-mode cpu bus :zp)
                    (declare (ignore ignored))
                    (%bit! cpu (bus-read bus operand))
                    3))
                 (#x25 (%read-op! cpu bus :zp #'%and! nil))
                 (#x26 (%rmw-op! cpu bus :zp #'%rol-value! 5))
                 (#x27 (%rmw-op! cpu bus :zp #'%rla-value! 5))
                 (#x28
                  (%restore-status! cpu (%pop-byte! cpu bus))
                  4)
                 (#x29 (%read-op! cpu bus :immediate #'%and! nil))
                 (#x2B (%read-op! cpu bus :immediate #'%aac! nil))
                 (#x2A
                  (setf (cpu-a cpu) (%rol-value! cpu (cpu-a cpu)))
                  2)
                 (#x2C
                  (%bit! cpu (bus-read bus (%fetch-word cpu bus)))
                  4)
                 (#x2D (%read-op! cpu bus :abs #'%and! nil))
                 (#x2E (%rmw-op! cpu bus :abs #'%rol-value! 6))
                 (#x2F (%rmw-op! cpu bus :abs #'%rla-value! 6))
                 (#x30 (%branch! cpu bus (%flag-set-p cpu +flag-negative+)))
                 (#x31 (%read-op! cpu bus :indy #'%and! t))
                 (#x33 (%rmw-op! cpu bus :indy #'%rla-value! 8))
                 (#x35 (%read-op! cpu bus :zpx #'%and! nil))
                 (#x36 (%rmw-op! cpu bus :zpx #'%rol-value! 6))
                 (#x37 (%rmw-op! cpu bus :zpx #'%rla-value! 6))
                 (#x38 (%set-flag! cpu +flag-carry+ t) 2)
                 (#x39 (%read-op! cpu bus :absy #'%and! t))
                 (#x3B (%rmw-op! cpu bus :absy #'%rla-value! 7))
                 (#x3D (%read-op! cpu bus :absx #'%and! t))
                 (#x3E (%rmw-op! cpu bus :absx #'%rol-value! 7))
                 (#x3F (%rmw-op! cpu bus :absx #'%rla-value! 7))

                 (#x40
                  (%restore-status! cpu (%pop-byte! cpu bus) nil)
                  (setf (cpu-pc cpu) (%pop-word! cpu bus))
                  6)
                 (#x41 (%read-op! cpu bus :indx #'%eor! nil))
                 (#x43 (%rmw-op! cpu bus :indx #'%sre-value! 8))
                 (#x45 (%read-op! cpu bus :zp #'%eor! nil))
                 (#x46 (%rmw-op! cpu bus :zp #'%lsr-value! 5))
                 (#x47 (%rmw-op! cpu bus :zp #'%sre-value! 5))
                 (#x48 (%push-byte! cpu bus (cpu-a cpu)) 3)
                 (#x49 (%read-op! cpu bus :immediate #'%eor! nil))
                 (#x4B (%read-op! cpu bus :immediate #'%asr! nil))
                 (#x4A
                  (setf (cpu-a cpu) (%lsr-value! cpu (cpu-a cpu)))
                  2)
                 (#x4C
                  (setf (cpu-pc cpu) (%fetch-word cpu bus))
                  3)
                 (#x4D (%read-op! cpu bus :abs #'%eor! nil))
                 (#x4E (%rmw-op! cpu bus :abs #'%lsr-value! 6))
                 (#x4F (%rmw-op! cpu bus :abs #'%sre-value! 6))
                 (#x50 (%branch! cpu bus (not (%flag-set-p cpu +flag-overflow+))))
                 (#x51 (%read-op! cpu bus :indy #'%eor! t))
                 (#x53 (%rmw-op! cpu bus :indy #'%sre-value! 8))
                 (#x55 (%read-op! cpu bus :zpx #'%eor! nil))
                 (#x56 (%rmw-op! cpu bus :zpx #'%lsr-value! 6))
                 (#x57 (%rmw-op! cpu bus :zpx #'%sre-value! 6))
                 (#x58
                  (let ((was-disabled
                          (%flag-set-p cpu +flag-interrupt-disable+)))
                    (%set-flag! cpu +flag-interrupt-disable+ nil)
                    (when was-disabled
                      (setf (cpu-irq-delay cpu) 1))
                    2))
                 (#x59 (%read-op! cpu bus :absy #'%eor! t))
                 (#x5B (%rmw-op! cpu bus :absy #'%sre-value! 7))
                 (#x5D (%read-op! cpu bus :absx #'%eor! t))
                 (#x5E (%rmw-op! cpu bus :absx #'%lsr-value! 7))
                 (#x5F (%rmw-op! cpu bus :absx #'%sre-value! 7))

                 (#x60
                  (setf (cpu-pc cpu) (logand (1+ (%pop-word! cpu bus)) #xFFFF))
                  6)
                 (#x61 (%read-op! cpu bus :indx #'%adc! nil))
                 (#x63 (%rmw-op! cpu bus :indx #'%rra-value! 8))
                 (#x65 (%read-op! cpu bus :zp #'%adc! nil))
                 (#x66 (%rmw-op! cpu bus :zp #'%ror-value! 5))
                 (#x67 (%rmw-op! cpu bus :zp #'%rra-value! 5))
                 (#x68
                  (setf (cpu-a cpu) (%pop-byte! cpu bus))
                  (%update-zn! cpu (cpu-a cpu))
                  4)
                 (#x69 (%read-op! cpu bus :immediate #'%adc! nil))
                 (#x6B (%read-op! cpu bus :immediate #'%arr! nil))
                 (#x6A
                  (setf (cpu-a cpu) (%ror-value! cpu (cpu-a cpu)))
                  2)
                 (#x6C (%jump-indirect cpu bus))
                 (#x6D (%read-op! cpu bus :abs #'%adc! nil))
                 (#x6E (%rmw-op! cpu bus :abs #'%ror-value! 6))
                 (#x6F (%rmw-op! cpu bus :abs #'%rra-value! 6))
                 (#x70 (%branch! cpu bus (%flag-set-p cpu +flag-overflow+)))
                 (#x71 (%read-op! cpu bus :indy #'%adc! t))
                 (#x73 (%rmw-op! cpu bus :indy #'%rra-value! 8))
                 (#x75 (%read-op! cpu bus :zpx #'%adc! nil))
                 (#x76 (%rmw-op! cpu bus :zpx #'%ror-value! 6))
                 (#x77 (%rmw-op! cpu bus :zpx #'%rra-value! 6))
                 (#x78
                  (let ((was-disabled
                          (%flag-set-p cpu +flag-interrupt-disable+)))
                    (%set-flag! cpu +flag-interrupt-disable+ t)
                    (unless was-disabled
                      (setf (cpu-irq-delay cpu) 1))
                    2))
                 (#x79 (%read-op! cpu bus :absy #'%adc! t))
                 (#x7B (%rmw-op! cpu bus :absy #'%rra-value! 7))
                 (#x7D (%read-op! cpu bus :absx #'%adc! t))
                 (#x7E (%rmw-op! cpu bus :absx #'%ror-value! 7))
                 (#x7F (%rmw-op! cpu bus :absx #'%rra-value! 7))

                 (#x81 (%write-op! cpu bus :indx (cpu-a cpu)))
                 (#x83 (%write-op! cpu bus :indx (logand (cpu-a cpu) (cpu-x cpu))))
                 (#x84 (%write-op! cpu bus :zp (cpu-y cpu)))
                 (#x85 (%write-op! cpu bus :zp (cpu-a cpu)))
                 (#x86 (%write-op! cpu bus :zp (cpu-x cpu)))
                 (#x87 (%write-op! cpu bus :zp (logand (cpu-a cpu) (cpu-x cpu))))
                 (#x88
                  (setf (cpu-y cpu) (mod (1- (cpu-y cpu)) 256))
                  (%update-zn! cpu (cpu-y cpu))
                  2)
                 (#x8A
                  (setf (cpu-a cpu) (cpu-x cpu))
                  (%update-zn! cpu (cpu-a cpu))
                  2)
                 (#x8C (%write-op! cpu bus :abs (cpu-y cpu)))
                 (#x8D (%write-op! cpu bus :abs (cpu-a cpu)))
                 (#x8E (%write-op! cpu bus :abs (cpu-x cpu)))
                 (#x8F (%write-op! cpu bus :abs (logand (cpu-a cpu) (cpu-x cpu))))
                 (#x90 (%branch! cpu bus (not (%flag-set-p cpu +flag-carry+))))
                 (#x91 (%write-op! cpu bus :indy (cpu-a cpu)))
                 (#x94 (%write-op! cpu bus :zpx (cpu-y cpu)))
                 (#x95 (%write-op! cpu bus :zpx (cpu-a cpu)))
                 (#x96 (%write-op! cpu bus :zpy (cpu-x cpu)))
                 (#x97 (%write-op! cpu bus :zpy (logand (cpu-a cpu) (cpu-x cpu))))
                 (#x98
                  (setf (cpu-a cpu) (cpu-y cpu))
                  (%update-zn! cpu (cpu-a cpu))
                  2)
                 (#x99 (%write-op! cpu bus :absy (cpu-a cpu)))
                 (#x9A
                   (setf (cpu-sp cpu) (cpu-x cpu))
                   2)
                 (#x9C (%unstable-store-op! cpu bus (cpu-x cpu) (cpu-y cpu)))
                 (#x9E (%unstable-store-op! cpu bus (cpu-y cpu) (cpu-x cpu)))
                 (#x9D (%write-op! cpu bus :absx (cpu-a cpu)))

                 (#xA0 (%read-op! cpu bus :immediate
                                  (lambda (cpu value)
                                    (%update-zn! cpu (setf (cpu-y cpu) value)))
                                  nil))
                 (#xA1 (%read-op! cpu bus :indx #'%load-a! nil))
                 (#xA2 (%read-op! cpu bus :immediate #'%load-x! nil))
                 (#xA3 (%read-op! cpu bus :indx #'%lax! nil))
                 (#xA4 (%read-op! cpu bus :zp #'%load-y! nil))
                 (#xA5 (%read-op! cpu bus :zp #'%load-a! nil))
                 (#xA6 (%read-op! cpu bus :zp #'%load-x! nil))
                 (#xA7 (%read-op! cpu bus :zp #'%lax! nil))
                 (#xA8
                  (setf (cpu-y cpu) (cpu-a cpu))
                  (%update-zn! cpu (cpu-y cpu))
                  2)
                 (#xA9 (%read-op! cpu bus :immediate #'%load-a! nil))
                 (#xAA
                  (setf (cpu-x cpu) (cpu-a cpu))
                  (%update-zn! cpu (cpu-x cpu))
                  2)
                 (#xAC (%read-op! cpu bus :abs #'%load-y! nil))
                 (#xAD (%read-op! cpu bus :abs #'%load-a! nil))
                 (#xAE (%read-op! cpu bus :abs #'%load-x! nil))
                 (#xAB (%read-op! cpu bus :immediate #'%atx! nil))
                 (#xB0 (%branch! cpu bus (%flag-set-p cpu +flag-carry+)))
                 (#xB1 (%read-op! cpu bus :indy #'%load-a! t))
                 (#xB3 (%read-op! cpu bus :indy #'%lax! t))
                 (#xB4 (%read-op! cpu bus :zpx #'%load-y! nil))
                 (#xB5 (%read-op! cpu bus :zpx #'%load-a! nil))
                 (#xB6 (%read-op! cpu bus :zpy #'%load-x! nil))
                 (#xB7 (%read-op! cpu bus :zpy #'%lax! nil))
                 (#xB8 (%set-flag! cpu +flag-overflow+ nil) 2)
                 (#xB9 (%read-op! cpu bus :absy #'%load-a! t))
                 (#xBA
                  (setf (cpu-x cpu) (cpu-sp cpu))
                  (%update-zn! cpu (cpu-x cpu))
                  2)
                 (#xBC (%read-op! cpu bus :absx #'%load-y! t))
                 (#xBD (%read-op! cpu bus :absx #'%load-a! t))
                 (#xBE (%read-op! cpu bus :absy #'%load-x! t))
                 (#xAF (%read-op! cpu bus :abs #'%lax! nil))
                 (#xBF (%read-op! cpu bus :absy #'%lax! t))

                 (#xC0 (%read-op! cpu bus :immediate #'%cmp-y! nil))
                 (#xC1 (%read-op! cpu bus :indx #'%cmp-a! nil))
                 (#xC3 (%rmw-op! cpu bus :indx #'%dcp-value! 8))
                 (#xC4 (%read-op! cpu bus :zp #'%cmp-y! nil))
                 (#xC5 (%read-op! cpu bus :zp #'%cmp-a! nil))
                 (#xC6 (%rmw-op! cpu bus :zp #'%dec-value! 5))
                 (#xC7 (%rmw-op! cpu bus :zp #'%dcp-value! 5))
                 (#xC8
                  (setf (cpu-y cpu) (mod (1+ (cpu-y cpu)) 256))
                  (%update-zn! cpu (cpu-y cpu))
                  2)
                 (#xC9 (%read-op! cpu bus :immediate #'%cmp-a! nil))
                 (#xCA
                  (setf (cpu-x cpu) (mod (1- (cpu-x cpu)) 256))
                  (%update-zn! cpu (cpu-x cpu))
                  2)
                 (#xCC (%read-op! cpu bus :abs #'%cmp-y! nil))
                 (#xCD (%read-op! cpu bus :abs #'%cmp-a! nil))
                 (#xCE (%rmw-op! cpu bus :abs #'%dec-value! 6))
                 (#xCB (%read-op! cpu bus :immediate #'%axs! nil))
                 (#xCF (%rmw-op! cpu bus :abs #'%dcp-value! 6))
                 (#xD0 (%branch! cpu bus (not (%flag-set-p cpu +flag-zero+))))
                 (#xD1 (%read-op! cpu bus :indy #'%cmp-a! t))
                 (#xD3 (%rmw-op! cpu bus :indy #'%dcp-value! 8))
                 (#xD5 (%read-op! cpu bus :zpx #'%cmp-a! nil))
                 (#xD6 (%rmw-op! cpu bus :zpx #'%dec-value! 6))
                 (#xD7 (%rmw-op! cpu bus :zpx #'%dcp-value! 6))
                 (#xD8 (%set-flag! cpu +flag-decimal+ nil) 2)
                 (#xD9 (%read-op! cpu bus :absy #'%cmp-a! t))
                 (#xDB (%rmw-op! cpu bus :absy #'%dcp-value! 7))
                 (#xDD (%read-op! cpu bus :absx #'%cmp-a! t))
                 (#xDE (%rmw-op! cpu bus :absx #'%dec-value! 7))
                 (#xDF (%rmw-op! cpu bus :absx #'%dcp-value! 7))

                 (#xE0 (%read-op! cpu bus :immediate #'%cmp-x! nil))
                 (#xE1 (%read-op! cpu bus :indx #'%sbc! nil))
                 (#xE3 (%rmw-op! cpu bus :indx #'%isc-value! 8))
                 (#xE4 (%read-op! cpu bus :zp #'%cmp-x! nil))
                 (#xE5 (%read-op! cpu bus :zp #'%sbc! nil))
                 (#xE6 (%rmw-op! cpu bus :zp #'%inc-value! 5))
                 (#xE7 (%rmw-op! cpu bus :zp #'%isc-value! 5))
                 (#xE8
                  (setf (cpu-x cpu) (mod (1+ (cpu-x cpu)) 256))
                  (%update-zn! cpu (cpu-x cpu))
                  2)
                 (#xE9 (%read-op! cpu bus :immediate #'%sbc! nil))
                 (#xEB (%read-op! cpu bus :immediate #'%sbc! nil))
                 (#xEA 2)
                 (#xEC (%read-op! cpu bus :abs #'%cmp-x! nil))
                 (#xED (%read-op! cpu bus :abs #'%sbc! nil))
                 (#xEE (%rmw-op! cpu bus :abs #'%inc-value! 6))
                 (#xEF (%rmw-op! cpu bus :abs #'%isc-value! 6))
                 (#xF0 (%branch! cpu bus (%flag-set-p cpu +flag-zero+)))
                 (#xF1 (%read-op! cpu bus :indy #'%sbc! t))
                 (#xF3 (%rmw-op! cpu bus :indy #'%isc-value! 8))
                 (#xF5 (%read-op! cpu bus :zpx #'%sbc! nil))
                 (#xF6 (%rmw-op! cpu bus :zpx #'%inc-value! 6))
                 (#xF7 (%rmw-op! cpu bus :zpx #'%isc-value! 6))
                 (#xF8 (%set-flag! cpu +flag-decimal+ t) 2)
                 (#xF9 (%read-op! cpu bus :absy #'%sbc! t))
                 (#xFB (%rmw-op! cpu bus :absy #'%isc-value! 7))
                 (#xFD (%read-op! cpu bus :absx #'%sbc! t))
                 (#xFE (%rmw-op! cpu bus :absx #'%inc-value! 7))
                 (#xFF (%rmw-op! cpu bus :absx #'%isc-value! 7))
                 (otherwise
                  (error 'illegal-opcode
                         :opcode opcode
                         :address address)))))
        (incf (cpu-cycles cpu) cycles)
        cycles)))
