(in-package #:cl-nes)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defparameter +opcode-00-7f-read-specs+
    '((#x01 :indx #'%ora! nil)
      (#x05 :zp #'%ora! nil)
      (#x09 :immediate #'%ora! nil)
      (#x0B :immediate #'%aac! nil)
      (#x0D :abs #'%ora! nil)
      (#x11 :indy #'%ora! t)
      (#x15 :zpx #'%ora! nil)
      (#x19 :absy #'%ora! t)
      (#x1D :absx #'%ora! t)
      (#x21 :indx #'%and! nil)
      (#x25 :zp #'%and! nil)
      (#x29 :immediate #'%and! nil)
      (#x2B :immediate #'%aac! nil)
      (#x2D :abs #'%and! nil)
      (#x31 :indy #'%and! t)
      (#x35 :zpx #'%and! nil)
      (#x39 :absy #'%and! t)
      (#x3D :absx #'%and! t)
      (#x41 :indx #'%eor! nil)
      (#x45 :zp #'%eor! nil)
      (#x49 :immediate #'%eor! nil)
      (#x4B :immediate #'%asr! nil)
      (#x4D :abs #'%eor! nil)
      (#x51 :indy #'%eor! t)
      (#x55 :zpx #'%eor! nil)
      (#x59 :absy #'%eor! t)
      (#x5D :absx #'%eor! t)
      (#x61 :indx #'%adc! nil)
      (#x65 :zp #'%adc! nil)
      (#x69 :immediate #'%adc! nil)
      (#x6B :immediate #'%arr! nil)
      (#x6D :abs #'%adc! nil)
      (#x71 :indy #'%adc! t)
      (#x75 :zpx #'%adc! nil)
      (#x79 :absy #'%adc! t)
      (#x7D :absx #'%adc! t)))
  (defparameter +opcode-00-7f-rmw-specs+
    '((#x03 :indx #'%slo-value! 8)
      (#x06 :zp #'%asl-value! 5)
      (#x07 :zp #'%slo-value! 5)
      (#x0E :abs #'%asl-value! 6)
      (#x0F :abs #'%slo-value! 6)
      (#x13 :indy #'%slo-value! 8)
      (#x16 :zpx #'%asl-value! 6)
      (#x17 :zpx #'%slo-value! 6)
      (#x1B :absy #'%slo-value! 7)
      (#x1E :absx #'%asl-value! 7)
      (#x1F :absx #'%slo-value! 7)
      (#x23 :indx #'%rla-value! 8)
      (#x26 :zp #'%rol-value! 5)
      (#x27 :zp #'%rla-value! 5)
      (#x2E :abs #'%rol-value! 6)
      (#x2F :abs #'%rla-value! 6)
      (#x33 :indy #'%rla-value! 8)
      (#x36 :zpx #'%rol-value! 6)
      (#x37 :zpx #'%rla-value! 6)
      (#x3B :absy #'%rla-value! 7)
      (#x3E :absx #'%rol-value! 7)
      (#x3F :absx #'%rla-value! 7)
      (#x43 :indx #'%sre-value! 8)
      (#x46 :zp #'%lsr-value! 5)
      (#x47 :zp #'%sre-value! 5)
      (#x4E :abs #'%lsr-value! 6)
      (#x4F :abs #'%sre-value! 6)
      (#x53 :indy #'%sre-value! 8)
      (#x56 :zpx #'%lsr-value! 6)
      (#x57 :zpx #'%sre-value! 6)
      (#x5B :absy #'%sre-value! 7)
      (#x5E :absx #'%lsr-value! 7)
      (#x5F :absx #'%sre-value! 7)
      (#x63 :indx #'%rra-value! 8)
      (#x66 :zp #'%ror-value! 5)
      (#x67 :zp #'%rra-value! 5)
      (#x6E :abs #'%ror-value! 6)
      (#x6F :abs #'%rra-value! 6)
      (#x73 :indy #'%rra-value! 8)
      (#x76 :zpx #'%ror-value! 6)
      (#x77 :zpx #'%rra-value! 6)
      (#x7B :absy #'%rra-value! 7)
      (#x7E :absx #'%ror-value! 7)
      (#x7F :absx #'%rra-value! 7)))
  (defparameter +opcode-00-7f-branch-specs+
    '((#x10 (not (%flag-set-p cpu +flag-negative+)))
      (#x30 (%flag-set-p cpu +flag-negative+))
      (#x50 (not (%flag-set-p cpu +flag-overflow+)))
      (#x70 (%flag-set-p cpu +flag-overflow+))))
  (defparameter +opcode-00-7f-flag-specs+
    '((#x18 +flag-carry+ nil)
      (#x38 +flag-carry+ t)))
  (defparameter +opcode-00-7f-accumulator-specs+
    '((#x0A %asl-value!)
      (#x2A %rol-value!)
      (#x4A %lsr-value!)
      (#x6A %ror-value!)))
  (defparameter +opcode-00-7f-literal-specs+
    '(((#x04 #x44 #x64) (%nop-op! cpu bus :zp 3))
      ((#x14 #x34 #x54 #x74) (%nop-op! cpu bus :zpx 4))
      (#x0C (%nop-op! cpu bus :abs 4))
      ((#x1A #x3A #x5A #x7A) 2)
      ((#x1C #x3C #x5C #x7C) (%nop-op! cpu bus :absx 4)))))
