(in-package #:cl-nes)

(defun %dispatch-cpu-opcode-80-ff (cpu bus opcode)
  (define-cpu-opcodes (cpu bus opcode)
    (:nop (#x80 #x82 #x89 #xC2 #xE2) :immediate 2)
    (:write #x81 :indx (cpu-a cpu))
    (:write #x83 :indx (logand (cpu-a cpu) (cpu-x cpu)))
    (:write #x84 :zp (cpu-y cpu))
    (:write #x85 :zp (cpu-a cpu))
    (:write #x86 :zp (cpu-x cpu))
    (:write #x87 :zp (logand (cpu-a cpu) (cpu-x cpu)))
    (#x88
     (setf (cpu-y cpu) (mod (1- (cpu-y cpu)) 256))
     (%update-zn! cpu (cpu-y cpu))
     2)
    (#x8A
     (setf (cpu-a cpu) (cpu-x cpu))
     (%update-zn! cpu (cpu-a cpu))
     2)
    (:write #x8C :abs (cpu-y cpu))
    (:write #x8D :abs (cpu-a cpu))
    (:write #x8E :abs (cpu-x cpu))
    (:write #x8F :abs (logand (cpu-a cpu) (cpu-x cpu)))
    (:branch #x90 (not (%flag-set-p cpu +flag-carry+)))
    (:write #x91 :indy (cpu-a cpu))
    (:write #x94 :zpx (cpu-y cpu))
    (:write #x95 :zpx (cpu-a cpu))
    (:write #x96 :zpy (cpu-x cpu))
    (:write #x97 :zpy (logand (cpu-a cpu) (cpu-x cpu)))
    (#x98
     (setf (cpu-a cpu) (cpu-y cpu))
     (%update-zn! cpu (cpu-a cpu))
     2)
    (:write #x99 :absy (cpu-a cpu))
    (#x9A
     (setf (cpu-sp cpu) (cpu-x cpu))
     2)
    (#x9C (%unstable-store-op! cpu bus (cpu-x cpu) (cpu-y cpu)))
    (:write #x9D :absx (cpu-a cpu))
    (#x9E (%unstable-store-op! cpu bus (cpu-y cpu) (cpu-x cpu)))

    (:read #xA0 :immediate
     (lambda (cpu value)
       (%update-zn! cpu (setf (cpu-y cpu) value)))
     nil)
    (:read #xA1 :indx #'%load-a! nil)
    (:read #xA2 :immediate #'%load-x! nil)
    (:read #xA3 :indx #'%lax! nil)
    (:read #xA4 :zp #'%load-y! nil)
    (:read #xA5 :zp #'%load-a! nil)
    (:read #xA6 :zp #'%load-x! nil)
    (:read #xA7 :zp #'%lax! nil)
    (#xA8
     (setf (cpu-y cpu) (cpu-a cpu))
     (%update-zn! cpu (cpu-y cpu))
     2)
    (:read #xA9 :immediate #'%load-a! nil)
    (#xAA
     (setf (cpu-x cpu) (cpu-a cpu))
     (%update-zn! cpu (cpu-x cpu))
     2)
    (:read #xAB :immediate #'%atx! nil)
    (:read #xAC :abs #'%load-y! nil)
    (:read #xAD :abs #'%load-a! nil)
    (:read #xAE :abs #'%load-x! nil)
    (:read #xAF :abs #'%lax! nil)
    (:branch #xB0 (%flag-set-p cpu +flag-carry+))
    (:read #xB1 :indy #'%load-a! t)
    (:read #xB3 :indy #'%lax! t)
    (:read #xB4 :zpx #'%load-y! nil)
    (:read #xB5 :zpx #'%load-a! nil)
    (:read #xB6 :zpy #'%load-x! nil)
    (:read #xB7 :zpy #'%lax! nil)
    (#xB8 (%set-flag! cpu +flag-overflow+ nil) 2)
    (:read #xB9 :absy #'%load-a! t)
    (#xBA
     (setf (cpu-x cpu) (cpu-sp cpu))
     (%update-zn! cpu (cpu-x cpu))
     2)
    (:read #xBC :absx #'%load-y! t)
    (:read #xBD :absx #'%load-a! t)
    (:read #xBE :absy #'%load-x! t)
    (:read #xBF :absy #'%lax! t)

    (:read #xC0 :immediate #'%cmp-y! nil)
    (:read #xC1 :indx #'%cmp-a! nil)
    (:rmw #xC3 :indx #'%dcp-value! 8)
    (:read #xC4 :zp #'%cmp-y! nil)
    (:read #xC5 :zp #'%cmp-a! nil)
    (:rmw #xC6 :zp #'%dec-value! 5)
    (:rmw #xC7 :zp #'%dcp-value! 5)
    (#xC8
     (setf (cpu-y cpu) (mod (1+ (cpu-y cpu)) 256))
     (%update-zn! cpu (cpu-y cpu))
     2)
    (:read #xC9 :immediate #'%cmp-a! nil)
    (#xCA
     (setf (cpu-x cpu) (mod (1- (cpu-x cpu)) 256))
     (%update-zn! cpu (cpu-x cpu))
     2)
    (:read #xCB :immediate #'%axs! nil)
    (:read #xCC :abs #'%cmp-y! nil)
    (:read #xCD :abs #'%cmp-a! nil)
    (:rmw #xCE :abs #'%dec-value! 6)
    (:rmw #xCF :abs #'%dcp-value! 6)
    (:branch #xD0 (not (%flag-set-p cpu +flag-zero+)))
    (:read #xD1 :indy #'%cmp-a! t)
    (:rmw #xD3 :indy #'%dcp-value! 8)
    (:nop #xD4 :zpx 4)
    (:read #xD5 :zpx #'%cmp-a! nil)
    (:rmw #xD6 :zpx #'%dec-value! 6)
    (:rmw #xD7 :zpx #'%dcp-value! 6)
    (#xD8 (%set-flag! cpu +flag-decimal+ nil) 2)
    (:read #xD9 :absy #'%cmp-a! t)
    (#xDA 2)
    (:rmw #xDB :absy #'%dcp-value! 7)
    (:nop #xDC :absx 4)
    (:read #xDD :absx #'%cmp-a! t)
    (:rmw #xDE :absx #'%dec-value! 7)
    (:rmw #xDF :absx #'%dcp-value! 7)

    (:read #xE0 :immediate #'%cmp-x! nil)
    (:read #xE1 :indx #'%sbc! nil)
    (:rmw #xE3 :indx #'%isc-value! 8)
    (:read #xE4 :zp #'%cmp-x! nil)
    (:read #xE5 :zp #'%sbc! nil)
    (:rmw #xE6 :zp #'%inc-value! 5)
    (:rmw #xE7 :zp #'%isc-value! 5)
    (#xE8
     (setf (cpu-x cpu) (mod (1+ (cpu-x cpu)) 256))
     (%update-zn! cpu (cpu-x cpu))
     2)
    (:read #xE9 :immediate #'%sbc! nil)
    (#xEA 2)
    (:read #xEB :immediate #'%sbc! nil)
    (:read #xEC :abs #'%cmp-x! nil)
    (:read #xED :abs #'%sbc! nil)
    (:rmw #xEE :abs #'%inc-value! 6)
    (:rmw #xEF :abs #'%isc-value! 6)
    (:branch #xF0 (%flag-set-p cpu +flag-zero+))
    (:read #xF1 :indy #'%sbc! t)
    (:rmw #xF3 :indy #'%isc-value! 8)
    (:nop #xF4 :zpx 4)
    (:read #xF5 :zpx #'%sbc! nil)
    (:rmw #xF6 :zpx #'%inc-value! 6)
    (:rmw #xF7 :zpx #'%isc-value! 6)
    (#xF8 (%set-flag! cpu +flag-decimal+ t) 2)
    (:read #xF9 :absy #'%sbc! t)
    (#xFA 2)
    (:rmw #xFB :absy #'%isc-value! 7)
    (:nop #xFC :absx 4)
    (:read #xFD :absx #'%sbc! t)
    (:rmw #xFE :absx #'%inc-value! 7)
    (:rmw #xFF :absx #'%isc-value! 7)
    (otherwise nil)))
