(in-package #:cl-nes)

(defun %background-pixel (ppu x y)
  (let* ((base-table (logand (ppu-control ppu) 3))
         (base-x (mod base-table 2))
         (base-y (floor base-table 2))
         (world-x (+ x (ppu-scroll-x ppu)))
         (world-y (mod (+ y (ppu-scroll-y ppu)) (* +ppu-height+ 2)))
         (page-x (floor world-x 256))
         (page-y (floor world-y +ppu-height+))
         (logical-x (mod (+ base-x page-x) 2))
         (logical-y (mod (+ base-y page-y) 2))
         (table (+ (* logical-y 2) logical-x))
         (local-x (mod world-x 256))
         (local-y (mod world-y +ppu-height+))
         (tile-x (floor local-x 8))
         (tile-y (floor local-y 8))
         (nametable-base (+ #x2000 (* table #x400)))
         (tile-address (+ nametable-base (* tile-y 32) tile-x))
         (tile (ppu-read-vram ppu tile-address))
         (pattern-base (if (logbitp 4 (ppu-control ppu)) #x1000 0))
         (row (mod local-y 8))
         (low (ppu-read-vram ppu (+ pattern-base (* tile 16) row)))
         (high (ppu-read-vram ppu (+ pattern-base (* tile 16) row 8)))
         (bit (- 7 (mod local-x 8)))
         (color (logior (ldb (byte 1 bit) low)
                        (ash (ldb (byte 1 bit) high) 1)))
         (backdrop (logand (ppu-read-vram ppu #x3F00) #x3F)))
    (if (or (not (logbitp 1 (ppu-mask ppu)))
            (and (< x 8) (not (logbitp 2 (ppu-mask ppu)))))
        (values backdrop nil)
        (if (zerop color)
            (values backdrop nil)
            (let* ((attribute-address
                     (+ nametable-base #x3C0
                        (* (floor tile-y 4) 8)
                        (floor tile-x 4)))
                   (attribute (ppu-read-vram ppu attribute-address))
                   (quadrant (+ (if (>= (mod tile-x 4) 2) 1 0)
                                (if (>= (mod tile-y 4) 2) 2 0)))
                   (palette-number (ldb (byte 2 (* quadrant 2)) attribute)))
              (values
               (logand
                (ppu-read-vram ppu (+ #x3F00 (* palette-number 4) color))
                #x3F)
               t))))))

(defun %render-background! (ppu)
  (let ((framebuffer (ppu-framebuffer ppu))
        (opaque (make-array (* +ppu-width+ +ppu-height+)
                            :element-type 'bit
                            :initial-element 0)))
    (if (logbitp 1 (ppu-mask ppu))
        (loop for y below +ppu-height+ do
          (loop for x below +ppu-width+ do
            (with-ppu-frame-index (index x y)
              (multiple-value-bind (color solid)
                  (%background-pixel ppu x y)
                (setf (aref framebuffer index) color)
                (when solid
                  (setf (aref opaque index) 1))))))
        (fill framebuffer (logand (ppu-read-vram ppu #x3F00) #x3F)))
    opaque))
