(in-package #:cl-nes)

(defconstant +ppu-decay-period+ 1000000)

(defun %ppu-recompute-decay-expiry! (ppu)
  (let ((next-expiry most-positive-fixnum))
    (dotimes (bit 8)
      (let ((deadline (aref (ppu-decay-deadlines ppu) bit)))
        (when (< deadline next-expiry)
          (setf next-expiry deadline))))
    (setf (ppu-decay-next-expiry ppu) next-expiry)))

(defun %ppu-expire-decay! (ppu)
  (let ((now (ppu-decay-clock ppu)))
    (when (<= (ppu-decay-next-expiry ppu) now)
      (dotimes (bit 8)
        (let ((deadline (aref (ppu-decay-deadlines ppu) bit)))
          (when (<= deadline now)
            (setf (ppu-decay-value ppu)
                  (logand (ppu-decay-value ppu)
                          (lognot (ash 1 bit))
                          #xFF)
                  (aref (ppu-decay-deadlines ppu) bit)
                  most-positive-fixnum))))
      (%ppu-recompute-decay-expiry! ppu)))
  ppu)

(defun %ppu-current-decay (ppu)
  (%ppu-expire-decay! ppu)
  (ppu-decay-value ppu))

(defun %ppu-drive-decay! (ppu value &optional (mask #xFF))
  (%ppu-expire-decay! ppu)
  (let ((value (logand value #xFF))
        (mask (logand mask #xFF))
        (deadline (+ (ppu-decay-clock ppu) +ppu-decay-period+)))
    (dotimes (bit 8)
      (let ((bit-mask (ash 1 bit)))
        (when (logbitp bit mask)
          (if (logbitp bit value)
              (setf (ppu-decay-value ppu)
                    (logior (ppu-decay-value ppu) bit-mask))
              (setf (ppu-decay-value ppu)
                    (logand (ppu-decay-value ppu)
                            (lognot bit-mask)
                            #xFF)))
          (setf (aref (ppu-decay-deadlines ppu) bit) deadline))))
    (%ppu-recompute-decay-expiry! ppu))
  value)

(defun %ppu-clock-decay! (ppu ticks)
  (incf (ppu-decay-clock ppu) ticks)
  (%ppu-expire-decay! ppu)
  ppu)
